-- Generated by scripts/build-confirmed-gap-sql.py from reviewed migrations.
-- Run ONCE in Supabase SQL Editor as postgres AFTER the PR #100 prerequisites.
-- Use this bundle OR its individual migrations, never both.
-- This does not repair CLI migration history or the unresolved Storage mapping.
-- Any error rolls back this entire bundle. Do not run isolated fragments.
begin;
set local lock_timeout = '10s';
do $preflight$
begin
 if to_regclass('public.notification_recipients') is null
    or to_regclass('public.notification_inbox') is null
    or to_regprocedure('private.assignment_notice_recipient(uuid,uuid,text)') is null
    or to_regprocedure('public.auth_people_permission(text)') is null
    or to_regprocedure('app_private.org_unlocked(uuid)') is null
    or to_regprocedure('public.auth_agile_container_write(uuid,uuid)') is null
    or not exists(select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='manager_type') then
  raise exception 'PREREQUISITES_REQUIRED: run the read-only production-recovery-verification.sql and resolve missing earlier migrations first';
 end if;
 if to_regclass('public.automation_jobs') is not null
    or to_regclass('public.proposal_decision_emails') is not null
    or to_regprocedure('public.notify_sprint_status_transaction()') is not null then
  raise exception 'BATCH_ALREADY_STARTED: do not replay this bundle over completed individual migrations; verify which migrations have already succeeded';
 end if;
end $preflight$;

-- SOURCE: 20260911163008_production_atomic_sprint_notifications.sql
-- SHA256: a47bfd4e9735f0f6cfd6dee08bb0c8e9dc298aa71387ee61590d698f6babf24f
-- Actual row transitions are the deduplication boundary: retries are no-ops,
-- while a legitimately reopened sprint announces its next start again.
create function public.notify_sprint_status_transaction() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare recipient record; actor uuid; actor_profile text;
begin
 if new.status is not distinct from old.status or new.status not in ('active','completed') then return new; end if;
 actor:=public.auth_app_user_id(); actor_profile:=auth.jwt()->'app_metadata'->>'user_type';
 if not exists(select 1 from public.memberships m where m.organization_id=new.organization_id and m.user_id=actor
  and m.user_type=actor_profile and m.user_type in ('admin','developer') and m.status='active' and m.role<>'client') then
  actor:=null; actor_profile:=null;
 end if;
 -- Every recipient gets a task they actually carry, never another member's
 -- task or an inaccessible supervisor-only sprint-page link.
 for recipient in
  select distinct on (t.developer_id) t.developer_id,t.id,t.project_id
  from public.developer_tasks t where t.organization_id=new.organization_id and t.sprint_id=new.id
   and t.developer_id is not null
   and (new.project_id is null or t.project_id=new.project_id)
   and private.assignment_notice_recipient(new.organization_id,t.developer_id,t.task_type)
  order by t.developer_id,t.id
 loop
  insert into public.notifications(organization_id,developer_id,type,category,title,message,task_id,project_id,
   entity_type,entity_id,actor_id,actor_type,metadata,read)
  values(new.organization_id,recipient.developer_id,
   case when new.status='active' then 'sprint_started' else 'sprint_completed' end,'sprint',
   case when new.status='active' then 'Sprint started' else 'Sprint completed' end,
   case when new.status='active' then format('Sprint "%s" has started — your tasks in it are now in flight.',new.name)
    else format('Sprint "%s" has been completed.',new.name) end,
   recipient.id,recipient.project_id,'task',recipient.id,actor,actor_profile,
   jsonb_build_object('sprintId',new.id,'sprintStatus',new.status),false);
 end loop;
 return new;
end $$;
revoke all on function public.notify_sprint_status_transaction() from public,anon,authenticated;
create trigger sprint_status_notification after update of status on public.sprints
 for each row execute function public.notify_sprint_status_transaction();
-- Leave existing write RLS and billing checks in charge of sprint mutations.
-- This guard prevents browser callers from forging the transaction's events.
create function public.guard_sprint_notice_insert() returns trigger
language plpgsql security invoker set search_path=pg_catalog,public as $$ begin
 if current_user not in ('postgres','supabase_admin','service_role') and new.type in ('sprint_started','sprint_completed') then
  raise exception 'Sprint notifications require the sprint status transaction' using errcode='42501';
 end if;
 return new;
end $$;
revoke all on function public.guard_sprint_notice_insert() from public,anon,authenticated;
create trigger ab_sprint_notice_authority before insert on public.notifications
 for each row execute function public.guard_sprint_notice_insert();

-- SOURCE: 20260911163106_production_notification_entity_privacy.sql
-- SHA256: 22da2724e16a442094875d450027157c651f799def0485fb577200d40335e296
-- Live entity references obey the reader's current rights, including notices
-- inserted by trusted server workflows. Existing task/proof privacy remains
-- independently enforced by notifications_task_current_access.
create or replace function public.notification_entity_visible(p_project uuid,p_task uuid,p_submission uuid,p_entity_type text,p_entity_id text)
returns boolean language plpgsql stable security invoker set search_path=pg_catalog,public as $$
declare org uuid:=public.auth_org(); actor uuid:=public.auth_app_user_id();
 profile text:=auth.jwt()->'app_metadata'->>'user_type'; member public.memberships%rowtype;
 project_ref uuid:=p_project; entity_ref uuid; project_row public.projects%rowtype;
 oversight boolean; project_role text;
begin
 if p_project is null and p_entity_type is distinct from 'project' and p_entity_type is distinct from 'team' and p_entity_type is distinct from 'employee' then return true; end if;
 select * into member from public.memberships where organization_id=org and user_id=actor and user_type=profile
  and status='active' and user_type in ('admin','developer') and role<>'client';
 if not found then return false; end if;
 if p_entity_type in ('project','team','employee') then
  entity_ref:=public.try_uuid(p_entity_id);
  if entity_ref is null then return false; end if;
 end if;
 if p_entity_type='project' then
  if project_ref is not null and project_ref<>entity_ref then return false; end if;
  project_ref:=entity_ref;
 end if;
 if project_ref is not null then
  select * into project_row from public.projects where id=project_ref and organization_id=org;
  if not found then return false; end if;
  -- Task/proof recipients may have independent task.review/bug.triage rights;
  -- their existing task privacy policy is authoritative for those notices.
  if p_task is null and p_submission is null and coalesce(p_entity_type,'') not in ('task','submission') then
   select pm.project_role into project_role from public.project_members pm
    where pm.organization_id=org and pm.project_id=project_ref and pm.user_id=actor and pm.user_type=profile;
   oversight:=coalesce(public.auth_override('project.view_all'),member.role in ('owner','admin','manager','team_lead')
     or coalesce(project_role in ('manager','team_lead'),false),false);
   if not oversight then
    if not coalesce(public.auth_override('project.view_own'),true) then return false; end if;
    if project_role is null
      and not coalesce(profile='developer' and coalesce(project_row.assigned_developer_id,project_row.assigned_to)=actor,false)
      and not coalesce((project_row.created_by=actor and project_row.created_by_type=profile)
        or (project_row.added_by=actor and project_row.added_by_type=profile)
        or (project_row.manager_id=actor and project_row.manager_type=profile),false)
      and not exists(select 1 from public.developer_tasks t where t.organization_id=org and t.project_id=project_ref
        and t.developer_id=actor and profile='developer') then return false; end if;
   end if;
  end if;
 end if;
 if p_entity_type='team' then
  if not exists(select 1 from public.teams t where t.id=entity_ref and t.organization_id=org) then return false; end if;
  oversight:=coalesce(public.auth_override('team_stats.view'),member.role in ('owner','admin','hr'),false)
    or coalesce(public.auth_override('team.view'),member.role in ('owner','admin','manager','team_lead'),false);
  if not oversight and (not coalesce(public.auth_override('team.view_own'),true) or member.team_id is distinct from entity_ref) then return false; end if;
 elsif p_entity_type='employee' then
  if not coalesce(public.auth_override('member.view'),member.role in ('owner','admin','hr'),false) then return false; end if;
  if not exists(select 1 from public.memberships m where m.organization_id=org and m.user_id=entity_ref and m.user_type in ('admin','developer')) then return false; end if;
 end if;
 return true;
end $$;
revoke all on function public.notification_entity_visible(uuid,uuid,uuid,text,text) from public,anon;
grant execute on function public.notification_entity_visible(uuid,uuid,uuid,text,text) to authenticated;
create policy notifications_entity_current_access on public.notifications as restrictive for select to authenticated
using(public.notification_entity_visible(project_id,task_id,submission_id,entity_type,entity_id::text));

-- SOURCE: 20260911163247_production_durable_actor_automation_jobs.sql
-- SHA256: 9c91985611923f0ac2cf19fa9e087a848daa2783e63fa9b3d7ee425a8a2e3709
create table public.automation_jobs(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,
 actor_id uuid not null,actor_type text not null check(actor_type in ('admin','developer')),
 task_id uuid not null references public.developer_tasks(id) on delete cascade,
 rule_id uuid references public.automation_rules(id) on delete set null,
 event text not null,task_snapshot jsonb not null,previous_snapshot jsonb,actions jsonb not null,
 next_action integer not null default 0,status text not null default 'pending' check(status in ('pending','processing','completed','failed','delivery_unknown','cancelled')),
 attempts integer not null default 0,lease uuid,lease_until timestamptz,next_attempt_at timestamptz default now(),last_error text,
 external_started boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index automation_jobs_actor_pending on public.automation_jobs(organization_id,actor_type,actor_id,status,created_at);
alter table public.automation_jobs enable row level security;
revoke all on public.automation_jobs from public,anon,authenticated;
grant select on public.automation_jobs to authenticated;
grant all on public.automation_jobs to service_role;
create policy automation_jobs_own on public.automation_jobs for select to authenticated using(
 organization_id=public.auth_org() and actor_id=public.auth_app_user_id() and actor_type=auth.jwt()->'app_metadata'->>'user_type'
 and exists(select 1 from public.developer_tasks t where t.id=automation_jobs.task_id and t.organization_id=automation_jobs.organization_id)
 and exists(select 1 from public.memberships m where m.organization_id=automation_jobs.organization_id and m.user_id=automation_jobs.actor_id and m.user_type=automation_jobs.actor_type and m.status='active'));
-- Authoring rules is separate from executing their actions as the event actor.
create or replace function public.auth_automation_manage() returns boolean language sql stable security definer set search_path=pg_catalog,public as $$
 select public.auth_org() is not null and not public.auth_is_client()
 and auth.jwt()->'app_metadata'->>'user_type' in ('admin','developer')
 and coalesce(public.auth_override('automation.manage'),public.auth_role() in ('owner','admin'),false);
$$;
revoke all on function public.auth_automation_manage() from public,anon;
grant execute on function public.auth_automation_manage() to authenticated;
create policy automation_author_insert on public.automation_rules as restrictive for insert to authenticated with check(public.auth_automation_manage());
create policy automation_author_update on public.automation_rules as restrictive for update to authenticated using(public.auth_automation_manage()) with check(public.auth_automation_manage());
create policy automation_author_delete on public.automation_rules as restrictive for delete to authenticated using(public.auth_automation_manage());
create or replace function public.guard_automation_rule_content() returns trigger language plpgsql security invoker set search_path=pg_catalog,public as $$ begin
 if tg_op='UPDATE' and (new.organization_id,new.project_id,new.id) is distinct from (old.organization_id,old.project_id,old.id) then raise exception 'Automation rule scope is immutable' using errcode='23514'; end if;
 if tg_op='INSERT' and new.project_id is not null and not exists(select 1 from public.projects p where p.id=new.project_id and p.organization_id=new.organization_id) then raise exception 'Automation project must belong to its organization' using errcode='23514'; end if;
 if tg_op='INSERT' or new.actions is distinct from old.actions then
  if jsonb_typeof(new.actions)<>'array' or jsonb_array_length(new.actions)>50 then raise exception 'Automation requires an action array of at most50 actions' using errcode='23514'; end if;
 end if;
 return new;
end $$;
revoke all on function public.guard_automation_rule_content() from public,anon,authenticated;
create trigger automation_rule_content before insert or update on public.automation_rules for each row execute function public.guard_automation_rule_content();
create or replace function public.capture_actor_automation_jobs() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare actor uuid:=public.auth_app_user_id(); profile text:=auth.jwt()->'app_metadata'->>'user_type';
 events text[]:='{}'; event_name text; rule public.automation_rules%rowtype; previous jsonb; running uuid; running_action jsonb; action_field text; expected_value text;
begin
 if not exists(select 1 from public.memberships m where m.organization_id=new.organization_id and m.user_id=actor and m.user_type=profile and m.status='active' and m.user_type in ('admin','developer') and m.role<>'client') then return new; end if;
 if not app_private.plan_feature(new.organization_id,'automation') then return new; end if;
 running:=public.try_uuid(nullif(current_setting('app.automation_job',true),''));
 if running is not null and tg_op='UPDATE' then
  select j.actions->j.next_action into running_action from public.automation_jobs j where j.id=running and j.organization_id=new.organization_id and j.task_id=new.id
   and j.actor_id=actor and j.actor_type=profile and j.status='processing' and j.lease_until>now();
  action_field:=case running_action->>'type' when 'assign' then 'developer_id' when 'set_status' then 'status' when 'set_priority' then 'priority' when 'add_label' then 'labels' end;
  expected_value:=case running_action->>'type' when 'assign' then running_action->>'userId' when 'set_status' then running_action->>'status' when 'set_priority' then running_action->>'priority' when 'add_label' then nullif(btrim(running_action->>'label'),'') end;
  -- A caller-set GUC alone is not authority. Suppress only the precise stored
  -- action, with every other field unchanged (apart from updated_at).
  if action_field is not null and expected_value is not null
   and (to_jsonb(new)-array[action_field,'updated_at']) is not distinct from (to_jsonb(old)-array[action_field,'updated_at'])
   and ((action_field<>'labels' and to_jsonb(new)->>action_field=expected_value)
     or (action_field='labels' and new.labels is not distinct from case when expected_value=any(coalesce(old.labels,'{}')) then old.labels else array_append(coalesce(old.labels,'{}'),expected_value) end)) then return new; end if;
 end if;
 if tg_op='INSERT' then events:=array['task_created'];
 else
  previous:=to_jsonb(old);
  if new.status is distinct from old.status then events:=array_append(events,'status_changed'); end if;
  if new.developer_id is distinct from old.developer_id then events:=array_append(events,'assigned'); end if;
  if new.priority is distinct from old.priority then events:=array_append(events,'priority_changed'); end if;
 end if;
 foreach event_name in array events loop
  for rule in select * from public.automation_rules r where r.organization_id=new.organization_id and r.enabled
   and (r.project_id is null or r.project_id=new.project_id) and r.trigger->>'event'=event_name order by r.created_at,r.id loop
   if nullif(rule.trigger->>'taskType','') is not null and rule.trigger->>'taskType'<>coalesce(new.task_type,'feature') then continue; end if;
   if nullif(rule.trigger->>'priority','') is not null and rule.trigger->>'priority'<>coalesce(new.priority,'medium') then continue; end if;
   if event_name='status_changed' and ((nullif(rule.trigger->>'to','') is not null and rule.trigger->>'to' is distinct from new.status)
    or (nullif(rule.trigger->>'from','') is not null and rule.trigger->>'from' is distinct from old.status)) then continue; end if;
   if event_name='priority_changed' and nullif(rule.trigger->>'toPriority','') is not null and rule.trigger->>'toPriority'<>coalesce(new.priority,'medium') then continue; end if;
   if jsonb_typeof(rule.actions)<>'array' or jsonb_array_length(rule.actions)=0 then continue; end if;
   insert into public.automation_jobs(organization_id,actor_id,actor_type,task_id,rule_id,event,task_snapshot,previous_snapshot,actions)
   values(new.organization_id,actor,profile,new.id,rule.id,event_name,to_jsonb(new),previous,rule.actions);
  end loop;
 end loop;
 return new;
end $$;
revoke all on function public.capture_actor_automation_jobs() from public,anon,authenticated;
create trigger actor_automation_events after insert or update on public.developer_tasks for each row execute function public.capture_actor_automation_jobs();
create or replace function public.claim_actor_automation_job(p_org uuid,p_actor uuid,p_type text,p_retry boolean default false)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare job public.automation_jobs%rowtype;
begin
 if not exists(select 1 from public.memberships m where m.organization_id=p_org and m.user_id=p_actor and m.user_type=p_type and m.status='active' and m.user_type in ('admin','developer') and m.role<>'client') or not app_private.plan_feature(p_org,'automation') then return null; end if;
 -- Never automatically resend an email whose provider outcome may be unknown.
 update public.automation_jobs set status='delivery_unknown',last_error='Email outcome is unknown; verify delivery before deliberately resending.',lease=null,lease_until=null,updated_at=now()
 where organization_id=p_org and actor_id=p_actor and actor_type=p_type and status='processing' and lease_until<now() and external_started;
 select * into job from public.automation_jobs j where j.organization_id=p_org and j.actor_id=p_actor and j.actor_type=p_type
 and (j.status='pending' or (j.status='failed' and (p_retry or (j.attempts<3 and j.next_attempt_at<=now())))
  or (j.status='processing' and j.lease_until<now() and not j.external_started))
 order by j.created_at,j.id for update skip locked limit 1;
 if not found then return null; end if;
 update public.automation_jobs set status='processing',attempts=attempts+1,lease=gen_random_uuid(),lease_until=now()+interval '2 minutes',updated_at=now()
 where id=job.id returning * into job;
 return to_jsonb(job);
end $$;
revoke all on function public.claim_actor_automation_job(uuid,uuid,text,boolean) from public,anon,authenticated;
grant execute on function public.claim_actor_automation_job(uuid,uuid,text,boolean) to service_role;
-- Apply only the stored action, under caller RLS. A verified running-job context
-- suppresses re-triggering; it never supplies a privileged identity or bypass.
create or replace function public.apply_actor_automation_action(p_job uuid,p_lease uuid)
returns jsonb language plpgsql security invoker set search_path=pg_catalog,public as $$
declare job public.automation_jobs%rowtype; task public.developer_tasks%rowtype; action jsonb; desired text; allowed boolean; old_context text; rule_project uuid; rule_enabled boolean;
begin
 select * into job from public.automation_jobs where id=p_job and lease=p_lease and status='processing' and lease_until>now();
 if not found then raise exception 'Automation lease or actor access is no longer valid' using errcode='42501'; end if;
 if not public.auth_plan_feature('automation') then raise exception 'Automation plan feature is unavailable' using errcode='42501'; end if;
 select * into task from public.developer_tasks where id=job.task_id and organization_id=job.organization_id for update;
 if not found then raise exception 'Automation task is no longer accessible' using errcode='42501'; end if;
 select r.project_id,r.enabled into rule_project,rule_enabled from public.automation_rules r where r.id=job.rule_id and r.organization_id=job.organization_id;
 if not found or not coalesce(rule_enabled,false) then raise exception 'Automation rule is no longer enabled or accessible' using errcode='42501'; end if;
 if rule_project is not null and rule_project is distinct from task.project_id then raise exception 'Automation project scope changed since dispatch' using errcode='40001'; end if;
 action:=job.actions->job.next_action;
 old_context:=current_setting('app.automation_job',true);
 perform set_config('app.automation_job',job.id::text,true);
 case action->>'type'
 when 'assign' then
  desired:=action->>'userId';
  if public.try_uuid(desired) is null then raise exception 'Invalid automation assignee' using errcode='22023'; end if;
  if task.developer_id is distinct from public.try_uuid(desired) and task.developer_id::text is distinct from job.task_snapshot->>'developer_id' then raise exception 'Automation task changed since dispatch' using errcode='40001'; end if;
  update public.developer_tasks set developer_id=desired::uuid,updated_at=now() where id=task.id returning * into task;
 when 'set_priority' then
  desired:=action->>'priority';
  if desired not in ('low','medium','high','urgent') or desired is null then raise exception 'Invalid automation priority' using errcode='22023'; end if;
  if task.priority is distinct from desired and task.priority is distinct from job.task_snapshot->>'priority' then raise exception 'Automation task changed since dispatch' using errcode='40001'; end if;
  update public.developer_tasks set priority=desired,updated_at=now() where id=task.id returning * into task;
 when 'set_status' then
  desired:=action->>'status';
  allowed:=desired=task.status or case coalesce(task.status,'pending')
   when 'pending' then desired in ('in_progress','awaiting_approval') when 'in_progress' then desired in ('pending','awaiting_approval')
   when 'awaiting_approval' then desired in ('in_progress','reviewed') when 'reviewed' then desired in ('awaiting_approval','in_progress')
   when 'rejected' then desired='in_progress' else false end;
  if not coalesce(allowed,false) or desired in ('completed','rejected') then raise exception 'Automation status transition is not permitted' using errcode='22023'; end if;
  if task.status is distinct from desired and task.status is distinct from job.task_snapshot->>'status' then raise exception 'Automation task changed since dispatch' using errcode='40001'; end if;
  update public.developer_tasks set status=desired,updated_at=now() where id=task.id returning * into task;
 when 'add_label' then
  desired:=nullif(btrim(action->>'label'),'');
  if desired is null then raise exception 'Automation label is required' using errcode='22023'; end if;
  update public.developer_tasks set labels=case when desired=any(coalesce(labels,'{}')) then labels else array_append(coalesce(labels,'{}'),desired) end,updated_at=now() where id=task.id returning * into task;
 else raise exception 'Action requires the notification/email dispatcher' using errcode='22023';
 end case;
 if not found then raise exception 'Automation task was not changed; check current permissions' using errcode='42501'; end if;
 perform set_config('app.automation_job',coalesce(old_context,''),true);
 return to_jsonb(task);
end $$;
revoke all on function public.apply_actor_automation_action(uuid,uuid) from public,anon;
grant execute on function public.apply_actor_automation_action(uuid,uuid) to authenticated;

-- SOURCE: 20260911163440_production_atomic_proposal_decisions.sql
-- SHA256: b490b642e5fd040e47d99d748cd647fe4446aaf7988845c29e942b86d9469e5a
-- Proposal decisions, project creation, client linkage and delivery intent commit
-- together. Only the verified server boundary may invoke this transaction.
create table public.proposal_decision_emails (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 proposal_id uuid not null references public.project_proposals(id) on delete cascade,
 client_id uuid not null references public.clients(id) on delete cascade,
 decision text not null check(decision in ('accepted','rejected','needs_info')),
 title text not null, reason text, created_at timestamptz not null default now(),
 delivered_at timestamptz, attempts integer not null default 0, next_attempt_at timestamptz not null default now(),
 lease_id uuid, lease_until timestamptz, last_error text
);
alter table public.proposal_decision_emails enable row level security;
revoke all on public.proposal_decision_emails from public,anon,authenticated;
grant all on public.proposal_decision_emails to service_role;
create index proposal_decision_emails_pending on public.proposal_decision_emails(next_attempt_at) where delivered_at is null;
-- RLS cannot hide internal_notes. Browser overview uses only these public
-- columns; full staff details remain behind the verified proposals API.
revoke select on public.project_proposals from public,anon,authenticated;
grant select(id,organization_id,client_id,title,description,budget,currency,desired_deadline,status,decision_reason,decided_by,decided_at,assigned_manager_id,project_id,attachment_path,attachment_name,attachment_type,attachment_size,created_at,updated_at,estimated_cost,estimated_hours,estimated_timeline_days,estimated_by,estimated_at) on public.project_proposals to authenticated;
-- A direct client insert cannot pre-populate the staff's estimate or notes.
revoke insert on public.project_proposals from public,anon,authenticated;
grant insert(id,organization_id,client_id,title,description,budget,currency,desired_deadline,status,attachment_path,attachment_name,attachment_type,attachment_size) on public.project_proposals to authenticated;
create policy proposal_decisions_server_only on public.project_proposals as restrictive for update to authenticated using(false) with check(false);

create or replace function public.decide_project_proposal(p_org uuid,p_proposal uuid,p_actor uuid,p_actor_type text,p_decision text,
 p_reason text default null,p_manager uuid default null,p_manager_type text default null,p_cost numeric default null,
 p_hours numeric default null,p_days integer default null,p_internal_notes text default null)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare m public.memberships%rowtype; mgr public.memberships%rowtype; p public.project_proposals%rowtype;
 project_row public.projects%rowtype; manager_type text; notice_id uuid;
begin
 perform app_private.lock_quota(p_org);
 select * into m from public.memberships where organization_id=p_org and user_id=p_actor and user_type=p_actor_type and status='active' for share;
 if not found or p_actor_type not in ('admin','developer') or not coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='proposal.decide'),m.role in ('owner','admin','manager'),false) then
  raise exception 'PROPOSAL_FORBIDDEN' using errcode='42501'; end if;
 if p_decision is null or p_decision not in ('accepted','rejected','needs_info','in_review','estimate') or (p_decision in ('rejected','needs_info') and nullif(btrim(p_reason),'') is null) then
  raise exception 'PROPOSAL_INVALID' using errcode='22023'; end if;
 select * into p from public.project_proposals where id=p_proposal and organization_id=p_org for update;
 if not found then raise exception 'PROPOSAL_NOT_FOUND' using errcode='P0002'; end if;
 if p.status='accepted' and p_decision='accepted' then
  select * into project_row from public.projects where id=p.project_id and organization_id=p_org and proposal_id=p.id;
  if not found or not exists(select 1 from public.project_clients where organization_id=p_org and project_id=p.project_id and client_id=p.client_id) then
   raise exception 'PROPOSAL_CONFLICT: accepted project requires repair'; end if;
  return jsonb_build_object('proposal',to_jsonb(p),'project',to_jsonb(project_row),'replayed',true);
 end if;
 if p.status in ('accepted','rejected') then raise exception 'PROPOSAL_CONFLICT: decision is terminal'; end if;
 if p.status='needs_info' and p_decision='needs_info' and nullif(btrim(p_reason),'') is not distinct from nullif(btrim(p.decision_reason),'') then
  return jsonb_build_object('proposal',to_jsonb(p),'replayed',true);
 end if;
 if p_decision='estimate' then
  if (p_cost is null and p_hours is null) or p_cost<0 or p_hours<0 or p_days<0 or
    p_cost::text in ('NaN','Infinity','-Infinity') or p_hours::text in ('NaN','Infinity','-Infinity') then
   raise exception 'PROPOSAL_INVALID: invalid estimate' using errcode='22023'; end if;
  update public.project_proposals set status='in_review',estimated_cost=p_cost,estimated_hours=p_hours,
   estimated_timeline_days=p_days,internal_notes=coalesce(left(p_internal_notes,5000),internal_notes),estimated_by=p_actor,estimated_at=now()
   where id=p.id returning * into p;
  return jsonb_build_object('proposal',to_jsonb(p));
 end if;
 if p_decision='accepted' then
  if not coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='project.create'),m.role in ('owner','admin','manager','team_lead'),false) then raise exception 'PROPOSAL_FORBIDDEN' using errcode='42501'; end if;
  if not app_private.org_unlocked(p_org) then raise exception 'BILLING_LOCKED'; end if;
  perform id from public.clients where id=p.client_id and organization_id=p_org and status='active' for share;
  if not found then raise exception 'PROPOSAL_INVALID: inactive client' using errcode='22023'; end if;
  perform id from public.memberships where organization_id=p_org and user_id=p.client_id and user_type='client' and status='active' for share;
  if not found then raise exception 'PROPOSAL_INVALID: inactive client membership' using errcode='22023'; end if;
  if p_manager is not null then
   if not coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='project.assign_manager'),m.role in ('owner','admin'),false) then raise exception 'PROPOSAL_FORBIDDEN' using errcode='42501'; end if;
   manager_type:=p_manager_type;
   if manager_type is null then
    select case when count(distinct user_type)=1 then min(user_type) end into manager_type from public.memberships where organization_id=p_org and user_id=p_manager;
   end if;
   select * into mgr from public.memberships where organization_id=p_org and user_id=p_manager and user_type=manager_type and status='active' for share;
   if not found or manager_type not in ('admin','developer') or mgr.role not in ('owner','admin','manager','team_lead') then raise exception 'PROPOSAL_INVALID: invalid or ambiguous manager' using errcode='22023'; end if;
  end if;
  -- The existing project quota and typed-manager roster triggers remain active.
  insert into public.projects(organization_id,name,description,status,budget,deadline,created_by,created_by_type,manager_id,manager_type,proposal_id)
  values(p_org,p.title,p.description,'pending',coalesce(p.estimated_cost,p.budget),
   case when p.estimated_timeline_days>0 then (now() at time zone 'UTC')::date+p.estimated_timeline_days else p.desired_deadline end,
   p_actor,p_actor_type,p_manager,manager_type,p.id) returning * into project_row;
  insert into public.project_clients(organization_id,project_id,client_id) values(p_org,project_row.id,p.client_id);
 end if;
 update public.project_proposals set status=p_decision,decision_reason=nullif(btrim(p_reason),''),decided_by=p_actor,decided_at=now(),
  project_id=case when p_decision='accepted' then project_row.id else project_id end,
  assigned_manager_id=case when p_decision='accepted' then p_manager else assigned_manager_id end
  where id=p.id returning * into p;
 if p_decision in ('accepted','rejected','needs_info') then
  insert into public.proposal_decision_emails(organization_id,proposal_id,client_id,decision,title,reason)
  values(p_org,p.id,p.client_id,p_decision,p.title,p.decision_reason) returning id into notice_id;
 end if;
 if p_decision='accepted' and p_manager is not null then
  insert into public.notifications(organization_id,admin_id,admin_recipient_type,developer_id,admin_email,type,category,title,message,entity_type,entity_id,project_id,read)
  values(p_org,case when manager_type='admin' then p_manager end,case when manager_type='admin' then 'admin' end,
   case when manager_type='developer' then p_manager end,case when manager_type='admin' then mgr.email end,
   'project_assigned','assignment','A project has been assigned to you',format('"%s" came from a client proposal and is yours to plan.',project_row.name),'project',project_row.id,project_row.id,false);
 end if;
 return jsonb_build_object('proposal',to_jsonb(p),'project',case when p_decision='accepted' then to_jsonb(project_row) end,'emailQueued',notice_id is not null);
end $$;
revoke all on function public.decide_project_proposal(uuid,uuid,uuid,text,text,text,uuid,text,numeric,numeric,integer,text) from public,anon,authenticated;
grant execute on function public.decide_project_proposal(uuid,uuid,uuid,text,text,text,uuid,text,numeric,numeric,integer,text) to service_role;

create or replace function public.claim_proposal_decision_emails(p_proposal uuid default null,p_limit integer default 25)
returns setof public.proposal_decision_emails language sql security definer set search_path=pg_catalog,public as $$
 update public.proposal_decision_emails e set lease_id=gen_random_uuid(),lease_until=now()+interval '10 minutes',attempts=e.attempts+1
 where e.id in (select id from public.proposal_decision_emails where delivered_at is null and next_attempt_at<=now()
 and (lease_until is null or lease_until<now()) and (p_proposal is null or proposal_id=p_proposal)
 order by created_at,id limit greatest(1,least(coalesce(p_limit,25),100)) for update skip locked) returning e.*;
$$;
create or replace function public.finish_proposal_decision_email(p_id uuid,p_lease uuid,p_delivered boolean)
returns boolean language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 update public.proposal_decision_emails set delivered_at=case when p_delivered then now() end,
 lease_id=null,lease_until=null,next_attempt_at=now()+interval '15 minutes',last_error=case when p_delivered then null else 'Delivery unavailable; retry scheduled' end
 where id=p_id and lease_id=p_lease and delivered_at is null;
 return found;
end $$;
revoke all on function public.claim_proposal_decision_emails(uuid,integer),public.finish_proposal_decision_email(uuid,uuid,boolean) from public,anon,authenticated;
grant execute on function public.claim_proposal_decision_emails(uuid,integer),public.finish_proposal_decision_email(uuid,uuid,boolean) to service_role;

-- SOURCE: 20260911163620_production_atomic_employee_save.sql
-- SHA256: 2c2ccca4bfe8f023777f68d0ab479454052a640ec3fea4112b32a42e116e3a4b
-- Invoker RPC deliberately retains every existing row, rank, billing, cycle
-- and changed-field guard. Identity is resolved from the scoped membership.
create function public.save_employee_record(p_org uuid,p_membership uuid,p_user uuid,p_type text,p_membership_patch jsonb default '{}',p_profile_patch jsonb default '{}')
returns jsonb language plpgsql security invoker set search_path=pg_catalog,public as $$
declare member public.memberships%rowtype; old_profile public.employee_profiles%rowtype;
 fields text; values_sql text; assignments text; k text; required_permission text; saved uuid;
begin
 if p_org is null or p_org is distinct from public.auth_org() or p_type not in ('admin','developer') then
  raise exception 'Employee organization or profile is not accessible' using errcode='42501'; end if;
 if jsonb_typeof(p_membership_patch) is distinct from 'object' or jsonb_typeof(p_profile_patch) is distinct from 'object' then
  raise exception 'Employee patches must be objects' using errcode='22023'; end if;
 if exists(select 1 from jsonb_object_keys(p_membership_patch) keys(field) where keys.field not in ('team_id','department_id','reports_to','status'))
  or exists(select 1 from jsonb_object_keys(p_profile_patch) keys(field) where keys.field not in ('designation','phone','address','skills','employment_status','employment_type','joining_date','work_schedule','photo_url','bio','weekly_hours')) then
  raise exception 'Unsupported employee field; role changes require the role API' using errcode='22023'; end if;
 select * into member from public.memberships where id=p_membership and organization_id=p_org and user_id=p_user and user_type=p_type;
 if not found then raise exception 'Employee not found or update is not permitted' using errcode='42501'; end if;
 if p_membership_patch<>'{}'::jsonb then
  select string_agg(format('%I=r.%I',key,key),',') into assignments from jsonb_object_keys(p_membership_patch) key;
  execute format('update public.memberships m set %s,updated_at=now() from jsonb_populate_record(null::public.memberships,$1) r where m.id=$2 and m.organization_id=$3 returning m.id',assignments)
   into saved using p_membership_patch,p_membership,p_org;
  if saved is null then raise exception 'Employee membership update was not permitted' using errcode='42501'; end if;
 end if;
 if p_profile_patch<>'{}'::jsonb then
  select * into old_profile from public.employee_profiles where organization_id=p_org and user_id=p_user and user_type=p_type;
  if found and old_profile.membership_id is distinct from p_membership then
   raise exception 'Employee profile membership needs repair before saving' using errcode='22023'; end if;
  -- UPDATE trigger enforces changed fields; INSERT has no OLD record, so apply
  -- the same field permissions explicitly to the supplied initial values.
  if old_profile.id is null then
   for k in select jsonb_object_keys(p_profile_patch) loop
    required_permission:=case when k='employment_status' then 'employee.activate' when k='weekly_hours' then 'employment.set_hours' else 'employee.manage' end;
    if not public.auth_people_permission(required_permission) then raise exception 'permission denied: %',required_permission using errcode='42501'; end if;
   end loop;
  end if;
  select string_agg(format('%I',key),','),string_agg(format('r.%I',key),','),string_agg(format('%I=excluded.%I',key,key),',')
   into fields,values_sql,assignments from jsonb_object_keys(p_profile_patch) key;
  execute format('insert into public.employee_profiles(organization_id,membership_id,user_id,user_type,%s) select $2,$3,$4,$5,%s from jsonb_populate_record(null::public.employee_profiles,$1) r on conflict(organization_id,user_id,user_type) do update set %s,updated_at=now() returning id',fields,values_sql,assignments)
   into saved using p_profile_patch,p_org,p_membership,p_user,p_type;
  if saved is null then raise exception 'Employee profile update was not permitted' using errcode='42501'; end if;
 end if;
 return jsonb_build_object('success',true,'membershipId',p_membership,'userId',p_user,'userType',p_type);
end $$;
revoke all on function public.save_employee_record(uuid,uuid,uuid,text,jsonb,jsonb) from public,anon;
grant execute on function public.save_employee_record(uuid,uuid,uuid,text,jsonb,jsonb) to authenticated;
-- Actual changes generate notices in the membership transaction, including
-- direct authorized writers. Ambiguous legacy team leader UUIDs are omitted.
create function public.notify_employee_transition() returns trigger
language plpgsql security definer set search_path=pg_catalog,public as $$
declare recipient public.memberships%rowtype; target_team public.teams%rowtype;
 event_type text; heading text; body text; actor uuid; actor_profile text; employee_name text;
begin
 if new.user_type not in ('admin','developer') then return new; end if;
 actor:=public.auth_app_user_id(); actor_profile:=auth.jwt()->'app_metadata'->>'user_type';
 if not exists(select 1 from public.memberships m where m.organization_id=new.organization_id and m.user_id=actor and m.user_type=actor_profile and m.status='active') then actor:=null; actor_profile:=null; end if;
 employee_name:=coalesce(nullif(new.email,''),'A team member');
 if new.status is distinct from old.status then
  for recipient in select * from public.memberships m where m.organization_id=new.organization_id and m.status='active'
   and m.user_type in ('admin','developer') and m.role in ('owner','admin')
   and coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='member.view'),true)
  loop
   insert into public.notifications(organization_id,admin_id,admin_recipient_type,developer_id,type,category,title,message,entity_type,entity_id,actor_id,actor_type,metadata,read)
   values(new.organization_id,case when recipient.user_type='admin' then recipient.user_id::text end,
    case when recipient.user_type='admin' then 'admin' end,case when recipient.user_type='developer' then recipient.user_id end,
    'employee_status_changed','team','Team member updated',format('%s was set to %s.',employee_name,new.status),'employee',new.user_id,
    actor,actor_profile,jsonb_build_object('employeeType',new.user_type,'membershipId',new.id,'status',new.status),false);
  end loop;
 end if;
 if new.team_id is not null and new.team_id is distinct from old.team_id then
  select * into target_team from public.teams where id=new.team_id and organization_id=new.organization_id;
  if not found then raise exception 'Assigned team must belong to the employee organization' using errcode='23514'; end if;
  for recipient in select * from public.memberships m where m.organization_id=new.organization_id and m.status='active' and m.user_type in ('admin','developer') and m.role<>'client'
   and ((m.user_id=new.user_id and m.user_type=new.user_type)
    or (m.user_id in (target_team.manager_id,target_team.team_lead_id)
     and 1=(select count(*) from public.memberships x where x.organization_id=new.organization_id and x.user_id=m.user_id and x.user_type in ('admin','developer'))))
   and (coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='team_stats.view'),m.role in ('owner','admin','hr'))
    or coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='team.view'),m.role in ('owner','admin','manager','team_lead'))
    or (m.team_id=new.team_id and coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='team.view_own'),true)))
  loop
   if recipient.user_id=new.user_id and recipient.user_type=new.user_type then
    event_type:='team_assigned'; heading:='Added to a team'; body:=format('You were added to %s.',target_team.name);
   else event_type:='team_member_added'; heading:='New team member'; body:=format('%s was added to %s.',employee_name,target_team.name); end if;
   insert into public.notifications(organization_id,admin_id,admin_recipient_type,developer_id,type,category,title,message,entity_type,entity_id,actor_id,actor_type,metadata,read)
   values(new.organization_id,case when recipient.user_type='admin' then recipient.user_id::text end,
    case when recipient.user_type='admin' then 'admin' end,case when recipient.user_type='developer' then recipient.user_id end,
    event_type,'team',heading,body,'team',new.team_id,actor,actor_profile,
    jsonb_build_object('employeeId',new.user_id,'employeeType',new.user_type,'previousTeamId',old.team_id,'teamId',new.team_id),false);
  end loop;
 end if;
 return new;
end $$;
revoke all on function public.notify_employee_transition() from public,anon,authenticated;
create trigger employee_transition_notice after update of status,team_id on public.memberships
 for each row execute function public.notify_employee_transition();
create function public.guard_employee_notice_insert() returns trigger
language plpgsql security invoker set search_path=pg_catalog,public as $$ begin
 if current_user not in ('postgres','supabase_admin','service_role') and new.type in ('employee_status_changed','team_assigned','team_member_added') then
  raise exception 'Employee notifications require the membership transaction' using errcode='42501'; end if;
 return new;
end $$;
revoke all on function public.guard_employee_notice_insert() from public,anon,authenticated;
create trigger ab_employee_notice_authority before insert on public.notifications for each row execute function public.guard_employee_notice_insert();

-- SOURCE: 20260911164338_production_server_notification_event_guard.sql
-- SHA256: 79169a5afc67d2e9c3ff12a52aeaa896bbad9f1c3a1b2e4c096739e4da3d373a
-- These types are written exclusively by verified proposal, client approval,
-- and manager assignment routes. A readable reference is not authority to
-- announce that the underlying business decision happened.
create function public.guard_server_notification_event() returns trigger
language plpgsql security invoker set search_path=pg_catalog,public as $$ begin
 if current_user not in ('postgres','supabase_admin','service_role')
  and new.type in ('proposal_submitted','client_approved','client_changes_requested','project_manager_assigned') then
  raise exception 'Notification event requires its authoritative server workflow' using errcode='42501';
 end if;
 return new;
end $$;
revoke all on function public.guard_server_notification_event() from public,anon,authenticated;
create trigger ab_server_notification_event before insert on public.notifications
 for each row execute function public.guard_server_notification_event();

-- SOURCE: 20260911170307_production_atomic_work_transition_notices.sql
-- SHA256: dbdb02d21aeabe10d97c11ce3448e478d8cbdbba6aa76a316b601dba6208df14
create function private.work_notice_project_reader(p_org uuid,p_user uuid,p_type text) returns boolean
language sql stable security definer set search_path=pg_catalog,public as $$
 select exists(select 1 from public.memberships m where m.organization_id=p_org and m.user_id=p_user and m.user_type=p_type
  and m.status='active' and m.user_type in ('admin','developer') and m.role<>'client'
  and (coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='project.view_own'),true)
   or coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='project.view_all'),m.role in ('owner','admin','manager','team_lead'),false)));
$$;
revoke all on function private.work_notice_project_reader(uuid,uuid,text) from public,anon,authenticated;
create function public.notify_project_assignment_transaction() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,private as $$ begin
 if tg_op='UPDATE' and new.assigned_developer_id is not distinct from old.assigned_developer_id then return new; end if;
 if new.assigned_developer_id is not null and private.work_notice_project_reader(new.organization_id,new.assigned_developer_id,'developer') then
  insert into public.notifications(organization_id,developer_id,type,category,title,message,project_id,entity_type,entity_id,read)
  values(new.organization_id,new.assigned_developer_id,'project_assigned','assignment','Project assigned',
   format('"%s" has been assigned to you.',new.name),new.id,'project',new.id,false);
 end if;
 return new;
end $$;
revoke all on function public.notify_project_assignment_transaction() from public,anon,authenticated;
create trigger project_assignment_notice after insert or update of assigned_developer_id on public.projects
 for each row execute function public.notify_project_assignment_transaction();
create function public.notify_task_status_transaction() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,private as $$ begin
 -- Terminal review outcomes have their own authoritative review notices.
 if new.status is not distinct from old.status or new.status in ('completed','rejected') then return new; end if;
 if new.developer_id is not null and private.assignment_notice_recipient(new.organization_id,new.developer_id,new.task_type) then
  insert into public.notifications(organization_id,developer_id,type,category,title,message,task_id,project_id,metadata,read)
  values(new.organization_id,new.developer_id,'task_status_changed','status','Task status changed',
   format('"%s" moved from %s to %s.',coalesce(new.task_title,'A task'),replace(coalesce(old.status,'pending'),'_',' '),replace(new.status,'_',' ')),
   new.id,new.project_id,jsonb_build_object('previousStatus',old.status,'status',new.status),false);
 end if;
 return new;
end $$;
revoke all on function public.notify_task_status_transaction() from public,anon,authenticated;
create trigger task_status_notice after update of status on public.developer_tasks
 for each row execute function public.notify_task_status_transaction();
create function public.notify_milestone_transaction() returns trigger
language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare project_row public.projects%rowtype; recipient public.memberships%rowtype;
begin
 if new.status is distinct from 'completed' then return new; end if;
 if tg_op='UPDATE' and new.status is not distinct from old.status then return new; end if;
 select * into project_row from public.projects where id=new.project_id and organization_id=new.organization_id;
 if not found then raise exception 'Milestone project must belong to its organization' using errcode='23514'; end if;
 for recipient in select * from public.memberships m where m.organization_id=new.organization_id
  and private.work_notice_project_reader(new.organization_id,m.user_id,m.user_type)
  and ((m.user_type='developer' and m.user_id=coalesce(project_row.assigned_developer_id,project_row.assigned_to))
   or public.project_actor_is_owner(new.organization_id,new.project_id,m.user_id,m.user_type,false)
   or public.project_actor_is_manager(new.organization_id,new.project_id,m.user_id,m.user_type))
 loop
  insert into public.notifications(organization_id,admin_id,admin_recipient_type,developer_id,type,category,title,message,project_id,entity_type,entity_id,metadata,read)
  values(new.organization_id,case when recipient.user_type='admin' then recipient.user_id::text end,
   case when recipient.user_type='admin' then 'admin' end,case when recipient.user_type='developer' then recipient.user_id end,
   'milestone_completed','project','Milestone reached',format('Milestone "%s" on %s is complete.',new.title,project_row.name),
   new.project_id,'milestone',new.id,jsonb_build_object('milestoneId',new.id,'status','completed'),false);
 end loop;
 return new;
end $$;
revoke all on function public.notify_milestone_transaction() from public,anon,authenticated;
create trigger milestone_completion_notice after insert or update of status on public.milestones
 for each row execute function public.notify_milestone_transaction();
create function public.guard_work_transition_notice() returns trigger
language plpgsql security invoker set search_path=pg_catalog,public as $$ begin
 if current_user not in ('postgres','supabase_admin','service_role') and new.type in ('project_assigned','task_status_changed','milestone_completed') then
  raise exception 'Work transition notifications require the authoritative transaction' using errcode='42501'; end if;
 return new;
end $$;
revoke all on function public.guard_work_transition_notice() from public,anon,authenticated;
create trigger ab_work_transition_notice before insert on public.notifications for each row execute function public.guard_work_transition_notice();

-- SOURCE: 20260911171109_production_milestone_write_authority.sql
-- SHA256: 5d416a22fb182d1741731db97eeee9ed496e08a5dc5279ade8c908e9b3118e9e
-- Milestones are planning records, using the same effective task.manage,
-- active typed membership, readable project and billing gate as sprints/epics.
create policy milestone_planning_insert on public.milestones as restrictive for insert to authenticated
 with check(project_id is not null and public.auth_agile_container_write(organization_id,project_id));
create policy milestone_planning_update on public.milestones as restrictive for update to authenticated
 using(public.auth_agile_container_write(organization_id,project_id))
 with check(project_id is not null and public.auth_agile_container_write(organization_id,project_id));
create policy milestone_planning_delete on public.milestones as restrictive for delete to authenticated
 using(public.auth_agile_container_write(organization_id,project_id));
create function public.guard_milestone_content() returns trigger language plpgsql security invoker set search_path=pg_catalog,public as $$ begin
 if tg_op='UPDATE' and row(new.id,new.organization_id,new.project_id) is distinct from row(old.id,old.organization_id,old.project_id) then
  raise exception 'Milestone identity and project scope are immutable' using errcode='23514'; end if;
 if tg_op='INSERT' and not exists(select 1 from public.projects p where p.id=new.project_id and p.organization_id=new.organization_id) then
  raise exception 'Milestone project must belong to its organization' using errcode='23514'; end if;
 if tg_op='INSERT' or new.title is distinct from old.title then
  new.title:=btrim(new.title);
  if new.title is null or new.title='' then raise exception 'Milestone title is required' using errcode='23514'; end if;
 end if;
 if tg_op='INSERT' or new.status is distinct from old.status then
  if new.status is null or new.status not in ('pending','in_progress','completed') then raise exception 'Invalid milestone status' using errcode='23514'; end if;
 end if;
 return new;
end $$;
revoke all on function public.guard_milestone_content() from public,anon,authenticated;
create trigger milestone_content before insert or update on public.milestones for each row execute function public.guard_milestone_content();

commit;
