-- Generated by scripts/build-lifecycle-leave-sql.py from reviewed migrations.
-- Run ONCE as postgres AFTER the PR #101 confirmed-gap migrations succeeded.
-- Use this whole bundle OR its individual migrations, never both.
-- No existing organization is opted into retention or deletion by this bundle.
-- This does not repair CLI migration history or legacy Storage mappings.
-- Any error rolls back the entire bundle; do not run isolated fragments.
begin;
set local lock_timeout = '10s';
do $preflight$
begin
 if to_regclass('public.automation_jobs') is null
    or to_regclass('public.proposal_decision_emails') is null
    or to_regclass('public.leave_requests') is null
    or to_regclass('public.attendance_records') is null
    or to_regclass('storage.objects') is null
    or to_regprocedure('public.apply_actor_automation_action(uuid,uuid)') is null
    or to_regprocedure('public.notify_project_assignment_transaction()') is null
    or to_regprocedure('public.guard_milestone_content()') is null
    or to_regprocedure('app_private.plan_feature(uuid,text)') is null
    or to_regprocedure('public.auth_override(text)') is null then
  raise exception 'PREREQUISITES_REQUIRED: verify PR #101 and earlier schema migrations before this lifecycle/leave batch';
 end if;
 if to_regclass('public.tracking_retention_policies') is not null
    or to_regclass('app_private.organization_deletions') is not null
    or to_regprocedure('public.auth_leave_permission(text)') is not null
    or to_regprocedure('private.assert_automation_executor_safe()') is not null
    or to_regprocedure('public.guard_leave_day_contract()') is not null then
  raise exception 'BATCH_ALREADY_STARTED: do not replay this bundle over completed individual migrations; reconcile completed migrations first';
 end if;
end $preflight$;

-- SOURCE: 20260911180306_production_unattended_actor_automation.sql
-- SHA256: 576aa0b62d0ae720d7b2e25bcfb87ee60a288135f8a225ff3308596307d2d070
-- This role cannot sign in or bypass RLS. It inherits exactly the existing
-- authenticated policies/grants, but no API/login role may SET ROLE into it.
do $$ begin
 if not exists(select 1 from pg_roles where rolname='automation_actor_executor') then
  create role automation_actor_executor nologin nosuperuser nobypassrls nocreatedb nocreaterole inherit;
 end if;
 if exists(select 1 from pg_roles where rolname='automation_actor_executor' and (rolcanlogin or rolsuper or rolbypassrls or rolcreaterole or rolcreatedb or rolreplication)) then
  raise exception 'Unsafe automation executor role attributes'; end if;
end $$;
-- Ownership bypasses RLS even without BYPASSRLS. Reject all preexisting
-- owned objects in this database (including tables/types/schemas) except the
-- one fixed helper, and reject unexpected members who could assume this role.
create function private.assert_automation_executor_safe() returns void
language plpgsql security invoker set search_path=pg_catalog as $$
declare executor oid:=(select oid from pg_roles where rolname='automation_actor_executor');
begin
 if exists(select 1 from pg_auth_members am join pg_roles r on r.oid=am.roleid
   where am.member=executor and r.rolname<>'authenticated') then
  raise exception 'Automation executor inherits unexpected authority'; end if;
 if exists(select 1 from pg_auth_members am join pg_roles r on r.oid=am.member
   where am.roleid=executor and r.rolname<>'postgres') then
  raise exception 'Unexpected role can assume automation executor'; end if;
 if exists(select 1 from pg_shdepend d where d.refclassid='pg_authid'::regclass and d.refobjid=executor and d.deptype='o'
   and d.dbid in (0,(select oid from pg_database where datname=current_database()))
   and not (d.classid='pg_proc'::regclass and d.objid=coalesce(to_regprocedure('private.run_automation_as_actor(uuid,uuid,text,jsonb)')::oid,0))) then
  raise exception 'Automation executor owns unexpected database objects'; end if;
end $$;
revoke all on function private.assert_automation_executor_safe() from public,anon,authenticated,service_role;
select private.assert_automation_executor_safe();
grant authenticated to automation_actor_executor;
grant automation_actor_executor to postgres;
revoke automation_actor_executor from authenticated,anon,service_role,authenticator;
grant usage,create on schema private to automation_actor_executor;

-- Fixed, private operations. The owning role is intentionally NOT postgres:
-- every task read/update and notification INSERT below runs existing RLS and
-- field guards, including explicit denies and current typed actor attribution.
create function private.run_automation_as_actor(p_job uuid,p_lease uuid,p_operation text,p_notice jsonb default null)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public set row_security=on as $$
declare job public.automation_jobs%rowtype; task public.developer_tasks%rowtype; action jsonb; rule public.automation_rules%rowtype;
begin
 select * into job from public.automation_jobs where id=p_job and lease=p_lease and status='processing' and lease_until>now();
 if not found or not public.auth_plan_feature('automation') then raise exception 'Automation actor or lease is no longer authorized' using errcode='42501'; end if;
 if p_operation='apply' then return public.apply_actor_automation_action(p_job,p_lease); end if;
 if p_operation not in ('read','notice') then raise exception 'Unknown automation operation' using errcode='22023'; end if;
 action:=job.actions->job.next_action;
 if action->>'type' not in ('notify','email') then raise exception 'Stored action is not a delivery' using errcode='22023'; end if;
 if action->>'type'='email' and not public.auth_automation_manage() then raise exception 'Email actions require automation.manage' using errcode='42501'; end if;
 select * into task from public.developer_tasks where id=job.task_id and organization_id=job.organization_id;
 if not found then raise exception 'Automation task is no longer accessible' using errcode='42501'; end if;
 select * into rule from public.automation_rules where id=job.rule_id and organization_id=job.organization_id and enabled;
 if not found or (rule.project_id is not null and rule.project_id is distinct from task.project_id) then raise exception 'Automation rule scope is no longer valid' using errcode='42501'; end if;
 if p_operation='notice' then
  begin
  insert into public.notifications(organization_id,developer_id,admin_id,admin_recipient_type,type,title,message,project_id,task_id,dedupe_key,read)
  values(job.organization_id,(p_notice->>'developer_id')::uuid,p_notice->>'admin_id',p_notice->>'admin_recipient_type','automation',
   p_notice->>'title',p_notice->>'message',task.project_id,task.id,'automation:'||job.id||':'||job.next_action,false);
  exception when unique_violation then null;
  end;
 end if;
 return to_jsonb(task);
end $$;
alter function private.run_automation_as_actor(uuid,uuid,text,jsonb) owner to automation_actor_executor;
revoke all on function private.run_automation_as_actor(uuid,uuid,text,jsonb) from public,anon,authenticated,service_role;
grant execute on function private.run_automation_as_actor(uuid,uuid,text,jsonb) to postgres;
revoke create on schema private from automation_actor_executor;

create function public.run_unattended_automation_step(p_job uuid,p_lease uuid,p_operation text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare job public.automation_jobs%rowtype; member public.memberships%rowtype; profile_auth uuid; auth_record jsonb; claims_before text;
 result jsonb; action jsonb; target uuid; target_type text; recipient public.memberships%rowtype; notice jsonb; actor_role text;
begin
 select * into job from public.automation_jobs where id=p_job and lease=p_lease and status='processing' and lease_until>now() for update;
 if not found then raise exception 'Automation lease expired' using errcode='42501'; end if;
 if not app_private.plan_feature(job.organization_id,'automation') or app_private.organization_deleting(job.organization_id) then
  raise exception 'Automation organization is unavailable' using errcode='42501'; end if;
 select * into member from public.memberships where organization_id=job.organization_id and user_id=job.actor_id and user_type=job.actor_type
  and status='active' and user_type in ('admin','developer') and role<>'client' for share;
 if not found then raise exception 'Automation actor is inactive' using errcode='42501'; end if;
 if job.actor_type='admin' then
  select auth_user_id into profile_auth from public.admin_users where id=job.actor_id and organization_id=job.organization_id;
 else
  select auth_user_id into profile_auth from public.developers where id=job.actor_id and organization_id=job.organization_id;
 end if;
 select to_jsonb(u) into auth_record from auth.users u where u.id=profile_auth;
 if auth_record is null or auth_record->>'deleted_at' is not null
  or coalesce((auth_record->>'banned_until')::timestamptz>now(),false)
  or auth_record->'raw_app_meta_data'->>'organization_id' is distinct from job.organization_id::text
  or auth_record->'raw_app_meta_data'->>'app_user_id' is distinct from job.actor_id::text
  or auth_record->'raw_app_meta_data'->>'user_type' is distinct from job.actor_type then
  raise exception 'Automation actor Auth identity is unavailable' using errcode='42501'; end if;
 actor_role:=auth_record->'raw_app_meta_data'->>'role';
 if public.role_rank(actor_role) is null or public.role_rank(member.role) is null then raise exception 'Automation actor role is invalid' using errcode='42501'; end if;
 if public.role_rank(member.role)<public.role_rank(actor_role) then actor_role:=member.role; end if;
 claims_before:=current_setting('request.jwt.claims',true);
 begin
  perform set_config('request.jwt.claims',jsonb_build_object('sub',profile_auth,'role','authenticated','app_metadata',
    jsonb_build_object('organization_id',job.organization_id,'app_user_id',job.actor_id,'user_type',job.actor_type,'role',actor_role))::text,true);
  if p_operation='notice' then
   -- Identity/content come only from the stored job, never worker parameters.
   result:=private.run_automation_as_actor(p_job,p_lease,'read');
   action:=job.actions->job.next_action;
   target:=public.try_uuid(case when action->>'target'='user' then action->>'userId' else coalesce(result->>'developer_id',action->>'userId') end);
   target_type:=nullif(action->>'userType','');
   if action->>'type'='notify' then target_type:=coalesce(target_type,'developer'); end if;
   if (select count(*) from public.memberships where organization_id=job.organization_id and user_id=target and user_type in ('admin','developer')
     and (target_type is null or user_type=target_type))<>1 then raise exception 'Automation recipient is ambiguous or unavailable' using errcode='42501'; end if;
   select * into recipient from public.memberships where organization_id=job.organization_id and user_id=target and user_type in ('admin','developer')
     and (target_type is null or user_type=target_type) and status='active';
   if not found then raise exception 'Automation recipient is inactive' using errcode='42501'; end if;
   notice:=jsonb_build_object('title',coalesce(action->>'subject',action->>'title','Task update'),
    'message',coalesce(action->>'message',format('Task "%s" was updated.',coalesce(result->>'task_title','Untitled'))),
    'developer_id',case when recipient.user_type='developer' then recipient.user_id end,
    'admin_id',case when recipient.user_type='admin' then recipient.user_id end,
    'admin_recipient_type',case when recipient.user_type='admin' then 'admin' end);
   if length(notice->>'title')>500 or length(notice->>'message')>20000 then raise exception 'Invalid automation message' using errcode='22023'; end if;
  end if;
  result:=private.run_automation_as_actor(p_job,p_lease,p_operation,notice);
  perform set_config('request.jwt.claims',coalesce(claims_before,''),true);
  return result;
 exception when others then
  perform set_config('request.jwt.claims',coalesce(claims_before,''),true);
  raise;
 end;
end $$;
revoke all on function public.run_unattended_automation_step(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.run_unattended_automation_step(uuid,uuid,text) to service_role;

create function public.pending_automation_actors(p_limit integer default 25)
returns table(organization_id uuid,actor_id uuid,actor_type text,role text)
language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 -- Actor removal is terminal for queued work, rather than letting an abandoned
 -- actor repeatedly occupy the scheduler. Do not erase uncertain email state.
 update public.automation_jobs j set status=case when j.external_started then 'delivery_unknown' else 'cancelled' end,
  last_error=case when j.external_started then 'Actor unavailable; verify the previous email delivery before resending.' else 'Automation actor is no longer an active staff member.' end,
  lease=null,lease_until=null,next_attempt_at=null,updated_at=now()
 where (j.status in ('pending','failed') or (j.status='processing' and j.lease_until<now()))
 and not exists(select 1 from public.memberships m where m.organization_id=j.organization_id and m.user_id=j.actor_id
  and m.user_type=j.actor_type and m.status='active' and m.role<>'client' and m.user_type in ('admin','developer'));
 return query select j.organization_id,j.actor_id,j.actor_type,m.role
 from public.automation_jobs j join public.memberships m on m.organization_id=j.organization_id and m.user_id=j.actor_id and m.user_type=j.actor_type
 where m.status='active' and m.user_type in ('admin','developer') and m.role<>'client'
 and app_private.plan_feature(j.organization_id,'automation') and not app_private.organization_deleting(j.organization_id)
 and (j.status='pending' or (j.status='failed' and j.attempts<3 and j.next_attempt_at<=now()) or (j.status='processing' and j.lease_until<now()))
 group by j.organization_id,j.actor_id,j.actor_type,m.role order by min(j.updated_at),j.organization_id,j.actor_type,j.actor_id
 limit greatest(1,least(coalesce(p_limit,25),100));
end $$;
revoke all on function public.pending_automation_actors(integer) from public,anon,authenticated;
grant execute on function public.pending_automation_actors(integer) to service_role;

-- SOURCE: 20260911180503_production_tracking_retention_jobs.sql
-- SHA256: ed1b487389b914186ea81b7415a2f6809f36dfa0f8e4341a8768e6087c36ac16
-- Infrastructure only: no existing organization is opted into deletion.
-- Viewing history remains governed by plan limits, independently of retention.
create table public.tracking_retention_policies(
 organization_id uuid primary key references public.organizations(id) on delete cascade,
 mode text not null check(mode in ('disabled','custom','plan')),
 days integer check(days between 1 and 36500), revision bigint not null default 1,
 updated_at timestamptz not null default now(), updated_by uuid not null,
 last_swept_at timestamptz,last_summary jsonb,
 check((mode='custom' and days is not null) or (mode<>'custom' and days is null))
);
alter table public.tracking_retention_policies enable row level security;
revoke all on public.tracking_retention_policies from public,anon,authenticated;
grant select on public.tracking_retention_policies to authenticated;
grant all on public.tracking_retention_policies to service_role;
create function public.auth_retention_owner(p_org uuid) returns boolean language sql stable security definer set search_path=pg_catalog,public as $$
 select p_org=public.auth_org() and exists(select 1 from public.memberships m where m.organization_id=p_org
 and m.user_id=public.auth_app_user_id() and m.user_type=auth.jwt()->'app_metadata'->>'user_type'
 and m.user_type in ('admin','developer') and m.role='owner' and m.status='active'
 and ((m.user_type='admin' and exists(select 1 from public.admin_users a where a.id=m.user_id and a.organization_id=p_org and a.auth_user_id=auth.uid()))
 or (m.user_type='developer' and exists(select 1 from public.developers d where d.id=m.user_id and d.organization_id=p_org and d.auth_user_id=auth.uid())))
 and coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='organization.manage'),true));
$$;
revoke all on function public.auth_retention_owner(uuid) from public,anon;
grant execute on function public.auth_retention_owner(uuid) to authenticated;
create policy retention_owner_read on public.tracking_retention_policies for select to authenticated using(public.auth_retention_owner(organization_id));
create schema if not exists app_private;
create table app_private.tracking_retention_files(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 screenshot_id text not null, snapshot jsonb not null, bucket text not null, path text not null,
 object_id text not null, object_updated_at timestamptz, status text not null default 'processing' check(status in ('processing','failed','completed','cancelled')),
 lease uuid not null default gen_random_uuid(), lease_until timestamptz not null default now()+interval '5 minutes',
 attempts integer not null default 0, claimed_at timestamptz, last_error text, created_at timestamptz not null default now(), completed_at timestamptz
);
create unique index retention_file_active on app_private.tracking_retention_files(bucket,path) where status in ('processing','failed');
create index retention_file_retry on app_private.tracking_retention_files(organization_id,status,lease_until);
alter table app_private.tracking_retention_files enable row level security;
revoke all on app_private.tracking_retention_files from public,anon,authenticated,service_role;

create function app_private.retention_cutoff(p_org uuid) returns timestamptz language plpgsql stable security definer set search_path=pg_catalog,public,app_private as $$
declare policy public.tracking_retention_policies%rowtype; keep_days bigint;
begin
 select * into policy from public.tracking_retention_policies where organization_id=p_org;
 if not found or policy.mode='disabled' then return null; end if;
 keep_days:=case when policy.mode='custom' then policy.days else app_private.plan_limit(p_org,'tracking_history_days') end;
 if keep_days is null or keep_days<1 then return null; end if; -- Unlimited/unknown never means delete everything.
 return now()-make_interval(days=>least(keep_days,36500)::integer);
end $$;
create function app_private.retention_recorded(p_row jsonb) returns timestamptz language plpgsql stable set search_path=pg_catalog as $$
declare value text;
begin
 -- An explicitly open session is never an expired closed record.
 if (p_row ? 'end_time' and nullif(p_row->>'end_time','') is null)
 or (p_row ? 'session_end' and nullif(p_row->>'session_end','') is null) then return null; end if;
 value:=coalesce(nullif(p_row->>'end_time',''),nullif(p_row->>'session_end',''),nullif(p_row->>'timestamp',''),
 nullif(p_row->>'tracked_at',''),nullif(p_row->>'start_time',''),nullif(p_row->>'session_start',''),
 nullif(p_row->>'login_time',''),nullif(p_row->>'created_at',''));
 return value::timestamptz;
exception when invalid_datetime_format or datetime_field_overflow then return null;
end $$;
-- Do not cascade into newer telemetry, delivery evidence or business records.
create function app_private.retention_referenced(p_table text,p_row jsonb) returns boolean language plpgsql stable security definer set search_path=pg_catalog,public as $$
declare fk record; predicate text; referenced boolean;
begin
 for fk in select * from pg_constraint where contype='f' and confrelid=to_regclass('public.'||p_table) loop
  select string_agg(format('(to_jsonb(c)->%L) <> ''null''::jsonb and (to_jsonb(c)->%L)=($1->%L)',ca.attname,ca.attname,pa.attname),' and ')
  into predicate from unnest(fk.conkey,fk.confkey) keys(child,parent)
  join pg_attribute ca on ca.attrelid=fk.conrelid and ca.attnum=keys.child
  join pg_attribute pa on pa.attrelid=fk.confrelid and pa.attnum=keys.parent;
  execute format('select exists(select 1 from %s c where %s)',fk.conrelid::regclass,predicate) into referenced using p_row;
  if referenced then return true; end if;
 end loop;
 return false;
end $$;

create function public.set_tracking_retention(p_org uuid,p_mode text,p_days integer,p_confirm boolean) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare result public.tracking_retention_policies%rowtype;
begin
 if not public.auth_retention_owner(p_org) then raise exception 'Only the permitted organization owner can change retention' using errcode='42501'; end if;
 perform 1 from public.organizations where id=p_org and status='active' for update;
 if not found or app_private.organization_deleting(p_org) then raise exception 'Organization is not active' using errcode='42501'; end if;
 if p_mode is null or p_mode not in ('disabled','custom','plan') or (p_mode='custom' and (p_days is null or p_days not between 1 and 36500))
 or (p_mode<>'custom' and p_days is not null) then raise exception 'Invalid retention policy' using errcode='22023'; end if;
 if p_mode<>'disabled' and p_confirm is distinct from true then raise exception 'Permanent deletion confirmation is required' using errcode='22023'; end if;
 insert into public.tracking_retention_policies(organization_id,mode,days,updated_by) values(p_org,p_mode,p_days,public.auth_app_user_id())
 on conflict(organization_id) do update set mode=excluded.mode,days=excluded.days,revision=tracking_retention_policies.revision+1,updated_by=excluded.updated_by,updated_at=now()
 returning * into result;
 return to_jsonb(result)||jsonb_build_object('inFlight',(select count(*) from app_private.tracking_retention_files where organization_id=p_org and status in ('processing','failed') and claimed_at is not null));
end $$;
revoke all on function public.set_tracking_retention(uuid,text,integer,boolean) from public,anon;
grant execute on function public.set_tracking_retention(uuid,text,integer,boolean) to authenticated;

-- Object claims fence ordinary Storage upserts and screenshot edits until the
-- provider result is reconciled. No managed Storage row is changed through SQL.
create function public.retention_object_available(p_bucket text,p_path text) returns boolean language sql stable security definer set search_path=pg_catalog,app_private as $$
 select not exists(select 1 from app_private.tracking_retention_files where bucket=p_bucket and path=p_path and status in ('processing','failed'));
$$;
revoke all on function public.retention_object_available(text,text) from public,anon;
grant execute on function public.retention_object_available(text,text) to authenticated;
create policy retention_object_insert on storage.objects as restrictive for insert to authenticated with check(public.retention_object_available(bucket_id,name));
create policy retention_object_update on storage.objects as restrictive for update to authenticated
 using(public.retention_object_available(bucket_id,name)) with check(public.retention_object_available(bucket_id,name));
create function public.guard_retention_screenshot() returns trigger language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare item app_private.tracking_retention_files%rowtype;
begin
 select * into item from app_private.tracking_retention_files where status in ('processing','failed')
 and ((tg_op<>'INSERT' and screenshot_id=to_jsonb(old)->>'id') or (tg_op<>'DELETE' and path=to_jsonb(new)->>'storage_path')) limit 1;
 if found then
  raise exception 'Screenshot cleanup is in progress; retry after reconciliation' using errcode='55000'; end if;
 if tg_op='DELETE' then return old; end if; return new;
end $$;
revoke all on function public.guard_retention_screenshot() from public,anon,authenticated;
create trigger retention_screenshot_fence before insert or update or delete on public.screenshots for each row execute function public.guard_retention_screenshot();

-- Small transactions; no provider call occurs while holding database locks.
create function public.sweep_tracking_retention(p_org uuid,p_limit integer default 100) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare cutoff timestamptz; tbl text; row_data jsonb; obj record; n integer:=0; queued integer:=0; skipped integer:=0; matches integer; refs integer;
begin
 if p_limit not between 1 and 500 or p_limit is null then raise exception 'Invalid retention batch size' using errcode='22023'; end if;
 perform 1 from public.organizations where id=p_org and status='active' for update;
 if not found or app_private.organization_deleting(p_org) then return jsonb_build_object('deleted',0,'queued',0,'skipped',0); end if;
 update public.tracking_retention_policies set last_swept_at=now() where organization_id=p_org;
 cutoff:=app_private.retention_cutoff(p_org);
 if cutoff is null then return jsonb_build_object('deleted',0,'queued',0,'skipped',0); end if;
 -- Audit logs, submissions, projects, HR and financial records are NOT telemetry.
 foreach tbl in array array['keyboard_stats','mouse_activities','app_usage','browser_usage','developer_logins','developer_activities','productivity_sessions'] loop
  if to_regclass('public.'||tbl) is null then continue; end if;
  for row_data in execute format('select to_jsonb(t) from public.%I t where organization_id=$1 and app_private.retention_recorded(to_jsonb(t))<$2 limit $3 for update skip locked',tbl) using p_org,cutoff,p_limit loop
   if row_data->>'id' is null or app_private.retention_referenced(tbl,row_data) then skipped:=skipped+1; continue; end if;
   execute format('delete from public.%I t where organization_id=$1 and to_jsonb(t)->>''id''=$2',tbl) using p_org,row_data->>'id';
   n:=n+1;
  end loop;
 end loop;
 for row_data in select to_jsonb(s) from public.screenshots s where s.organization_id=p_org
  and app_private.retention_recorded(to_jsonb(s))<cutoff
  and not exists(select 1 from app_private.tracking_retention_files f where f.screenshot_id=s.id::text and f.status in ('processing','failed'))
  limit p_limit for update skip locked loop
  if app_private.retention_referenced('screenshots',row_data) then skipped:=skipped+1; continue; end if;
  -- Only canonical private monitoring objects have independently enforceable
  -- ownership. A mutable screenshot path cannot authorize deleting documents
  -- or legacy public-bucket bytes (even when no other record references them).
  if nullif(row_data->>'storage_path','') is null or nullif(row_data->>'developer_id','') is null
   or split_part(row_data->>'storage_path','/',1)<>p_org::text
   or split_part(row_data->>'storage_path','/',2)<>row_data->>'developer_id'
   or split_part(row_data->>'storage_path','/',3)='' then skipped:=skipped+1; continue; end if;
  -- Ambiguous paths/foreign references are preserved, never guessed.
  if exists(select 1 from public.screenshots s where s.storage_path=row_data->>'storage_path' and s.organization_id is distinct from p_org) then skipped:=skipped+1; continue; end if;
  select count(*) into refs from public.screenshots s where s.storage_path=row_data->>'storage_path';
  if refs>1 then
   delete from public.screenshots s where s.organization_id=p_org and s.id::text=row_data->>'id'; n:=n+1; continue;
  end if;
  select count(*) into matches from storage.objects o where o.name=row_data->>'storage_path' and o.bucket_id='monitoring';
  if matches=0 then
   -- No bytes exist at the canonical monitoring key; only the expired record remains.
   delete from public.screenshots s where s.organization_id=p_org and s.id::text=row_data->>'id'; n:=n+1; continue;
  end if;
  if matches<>1 then skipped:=skipped+1; continue; end if;
  select o.* into obj from storage.objects o where o.name=row_data->>'storage_path' and o.bucket_id='monitoring' for update;
  if (obj.bucket_id='monitoring' and split_part(obj.name,'/',1)<>p_org::text)
   or coalesce(obj.updated_at,obj.created_at)>=cutoff then skipped:=skipped+1; continue; end if;
  insert into app_private.tracking_retention_files(organization_id,screenshot_id,snapshot,bucket,path,object_id,object_updated_at)
   values(p_org,row_data->>'id',row_data,obj.bucket_id,obj.name,obj.id::text,obj.updated_at);
  queued:=queued+1;
 end loop;
 update public.tracking_retention_policies set last_summary=jsonb_build_object('deleted',n,'queued',queued,'skipped',skipped) where organization_id=p_org;
 return jsonb_build_object('deleted',n,'queued',queued,'skipped',skipped);
end $$;
revoke all on function public.sweep_tracking_retention(uuid,integer) from public,anon,authenticated;
grant execute on function public.sweep_tracking_retention(uuid,integer) to service_role;

create function public.claim_retention_file(p_org uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare job app_private.tracking_retention_files%rowtype; cutoff timestamptz; present boolean;
begin
 perform 1 from public.organizations where id=p_org and status='active' for update;
 if not found or app_private.organization_deleting(p_org) then return null; end if;
 select * into job from app_private.tracking_retention_files where organization_id=p_org and status in ('processing','failed') and lease_until<=now()
 order by created_at,id for update skip locked limit 1;
 if not found then return null; end if;
 cutoff:=app_private.retention_cutoff(p_org);
 select exists(select 1 from storage.objects where bucket_id=job.bucket and name=job.path) into present;
 if present and job.claimed_at is null and (cutoff is null or app_private.retention_recorded(job.snapshot)>=cutoff) then
  update app_private.tracking_retention_files set status='cancelled',completed_at=now(),last_error='Policy no longer selects this file' where id=job.id;
  return jsonb_build_object('cancelled',true);
 end if;
 if present and not exists(select 1 from storage.objects where bucket_id=job.bucket and name=job.path and id::text=job.object_id and updated_at is not distinct from job.object_updated_at) then
  update app_private.tracking_retention_files set status='cancelled',completed_at=now(),last_error='Object changed; retained for a new scan' where id=job.id;
  return jsonb_build_object('cancelled',true);
 end if;
 update app_private.tracking_retention_files set status='processing',claimed_at=coalesce(claimed_at,now()),lease=gen_random_uuid(),lease_until=now()+interval '5 minutes',attempts=attempts+1 where id=job.id returning * into job;
 return jsonb_build_object('id',job.id,'lease',job.lease,'bucket',job.bucket,'path',job.path,'remove',present);
end $$;
revoke all on function public.claim_retention_file(uuid) from public,anon,authenticated;
grant execute on function public.claim_retention_file(uuid) to service_role;

create function public.finish_retention_file(p_job uuid,p_lease uuid,p_error text default null) returns boolean
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare job app_private.tracking_retention_files%rowtype; current_row jsonb;
begin
 select * into job from app_private.tracking_retention_files where id=p_job and lease=p_lease and status='processing' for update;
 if not found then return false; end if;
 if exists(select 1 from storage.objects where bucket_id=job.bucket and name=job.path) then
  update app_private.tracking_retention_files set status='failed',last_error=left(coalesce(p_error,'Storage deletion not confirmed'),1000),lease_until=now()+interval '5 minutes' where id=job.id;
  return false;
 end if;
 select to_jsonb(s) into current_row from public.screenshots s where s.organization_id=job.organization_id and s.id::text=job.screenshot_id for update;
 if current_row is not null and app_private.retention_referenced('screenshots',current_row) then raise exception 'Screenshot has a new dependent record; reconciliation required'; end if;
 if current_row is not null and current_row<>job.snapshot then raise exception 'Screenshot changed during retention; manual reconciliation required'; end if;
 -- Marking completed and deleting the protected record share one transaction.
 update app_private.tracking_retention_files set status='completed',completed_at=now(),last_error=null where id=job.id;
 if current_row is not null then delete from public.screenshots s where s.organization_id=job.organization_id and s.id::text=job.screenshot_id; end if;
 return true;
end $$;
revoke all on function public.finish_retention_file(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.finish_retention_file(uuid,uuid,text) to service_role;
-- A freshly queued item is available immediately; only a worker claim leases it.
alter table app_private.tracking_retention_files alter column lease_until set default now();
revoke all on all functions in schema app_private from public,anon,authenticated;

create function public.retention_organizations(p_limit integer default 10) returns table(organization_id uuid)
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$begin
 return query select o.id from public.organizations o left join public.tracking_retention_policies p on p.organization_id=o.id
 where o.status='active' and not app_private.organization_deleting(o.id)
 and (p.mode in ('custom','plan') or exists(select 1 from app_private.tracking_retention_files f where f.organization_id=o.id and f.status in ('processing','failed')))
 order by p.last_swept_at nulls first,o.id limit greatest(1,least(coalesce(p_limit,10),50));
end $$;
revoke all on function public.retention_organizations(integer) from public,anon,authenticated;
grant execute on function public.retention_organizations(integer) to service_role;
create function public.get_tracking_retention(p_org uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare policy jsonb; counts jsonb;
begin
 if not public.auth_retention_owner(p_org) then raise exception 'Retention settings are owner-only' using errcode='42501'; end if;
 select to_jsonb(p) into policy from public.tracking_retention_policies p where organization_id=p_org;
 select jsonb_build_object('processing',count(*) filter(where status='processing'),'failed',count(*) filter(where status='failed'),
 'completed',count(*) filter(where status='completed'),'cancelled',count(*) filter(where status='cancelled')) into counts
 from app_private.tracking_retention_files where organization_id=p_org;
 return jsonb_build_object('policy',coalesce(policy,jsonb_build_object('mode','disabled','days',null)),'files',counts,'cutoff',app_private.retention_cutoff(p_org));
end $$;
revoke all on function public.get_tracking_retention(uuid) from public,anon;
grant execute on function public.get_tracking_retention(uuid) to authenticated;

-- SOURCE: 20260911180705_production_typed_leave_authority.sql
-- SHA256: e83edf7d2ff33173dfaf156852679afd3cf613e1268df4023d6e81fdeb023afe
create function public.auth_leave_permission(p_key text) returns boolean language sql stable security definer set search_path=pg_catalog,public as $$
 select exists(select 1 from public.memberships m where m.organization_id=public.auth_org() and m.user_id=public.auth_app_user_id()
  and m.user_type=auth.jwt()->'app_metadata'->>'user_type' and m.status='active' and m.user_type in ('admin','developer') and m.role<>'client')
 and case when p_key in ('leave.view_own','leave.request_own') then coalesce(public.auth_override(p_key),true)
  when p_key in ('leave.view_all','leave.approve') then coalesce(public.auth_override(p_key),public.auth_role() in ('owner','admin','hr','manager'),false) else false end;
$$;
revoke all on function public.auth_leave_permission(text) from public,anon;
grant execute on function public.auth_leave_permission(text) to authenticated;
drop policy if exists leave_requests_read on public.leave_requests;
drop policy if exists leave_requests_write_own on public.leave_requests;
drop policy if exists leave_requests_decide on public.leave_requests;
create policy leave_requests_read on public.leave_requests for select to authenticated using(organization_id=public.auth_org()
 and (public.auth_leave_permission('leave.view_all') or (user_id=public.auth_app_user_id() and user_type=auth.jwt()->'app_metadata'->>'user_type' and public.auth_leave_permission('leave.view_own'))));
create policy leave_requests_insert on public.leave_requests for insert to authenticated with check(organization_id=public.auth_org() and user_id=public.auth_app_user_id()
 and user_type=auth.jwt()->'app_metadata'->>'user_type' and status='pending' and public.auth_leave_permission('leave.request_own') and public.auth_org_unlocked());
create policy leave_requests_update on public.leave_requests for update to authenticated using(organization_id=public.auth_org() and status='pending' and public.auth_org_unlocked()
 and (public.auth_leave_permission('leave.approve') or (user_id=public.auth_app_user_id() and user_type=auth.jwt()->'app_metadata'->>'user_type' and public.auth_leave_permission('leave.request_own'))))
 with check(organization_id=public.auth_org() and public.auth_org_unlocked());
-- No browser DELETE policy: withdrawal remains the auditable cancelled state.
create function public.guard_leave_request() returns trigger language plpgsql security invoker set search_path=pg_catalog,public as $$
declare mine boolean; trusted boolean:=current_user in ('postgres','service_role','supabase_admin');
begin
 if tg_op='UPDATE' and row(new.id,new.organization_id,new.user_id,new.user_type,new.leave_type_id) is distinct from row(old.id,old.organization_id,old.user_id,old.user_type,old.leave_type_id) then
  raise exception 'Leave identity is immutable' using errcode='42501'; end if;
 if tg_op='INSERT' or row(new.start_date,new.end_date,new.days) is distinct from row(old.start_date,old.end_date,old.days) then
  if new.start_date is null or new.end_date is null or new.end_date<new.start_date or new.end_date-new.start_date>=365 or new.days is null
   or new.days::text in ('NaN','Infinity','-Infinity') or new.days<=0 or new.days>new.end_date-new.start_date+1 then
   raise exception 'Invalid leave dates or day amount' using errcode='22023'; end if;
 end if;
 if tg_op='INSERT' and (not exists(select 1 from public.leave_types t where t.id=new.leave_type_id and t.organization_id=new.organization_id and t.active)
  or not exists(select 1 from public.memberships m where m.organization_id=new.organization_id and m.user_id=new.user_id and m.user_type=new.user_type and m.status='active' and m.role<>'client')) then
  raise exception 'Leave type and staff member must be active in this organization' using errcode='42501'; end if;
 if not trusted then
  mine:=new.user_id=public.auth_app_user_id() and new.user_type=auth.jwt()->'app_metadata'->>'user_type';
  if tg_op='INSERT' then
   if new.status<>'pending' or not mine or not public.auth_leave_permission('leave.request_own') then raise exception 'Leave must be requested for yourself as pending' using errcode='42501'; end if;
   new.decided_by:=null; new.decided_at:=null; new.decision_note:=null;
  else
   if old.status<>'pending' then raise exception 'Leave was already decided' using errcode='40001'; end if;
   if new.status in ('approved','rejected') then
    if mine or not public.auth_leave_permission('leave.approve') then raise exception 'Leave decision permission required; self-approval is forbidden' using errcode='42501'; end if;
   elsif new.status='cancelled' then
    if not ((mine and public.auth_leave_permission('leave.request_own')) or (not mine and public.auth_leave_permission('leave.approve'))) then raise exception 'Leave cancellation not permitted' using errcode='42501'; end if;
   elsif new.status='pending' then
    if not mine or not public.auth_leave_permission('leave.request_own') then raise exception 'Only the requester may edit pending leave' using errcode='42501'; end if;
   else raise exception 'Invalid leave status' using errcode='22023'; end if;
   if new.status<>'pending' and row(new.start_date,new.end_date,new.days,new.reason) is distinct from row(old.start_date,old.end_date,old.days,old.reason) then raise exception 'A decision cannot rewrite the request' using errcode='42501'; end if;
   if new.status='pending' then new.decided_by:=null; new.decided_at:=null; new.decision_note:=null;
   else new.decided_by:=public.auth_app_user_id(); new.decided_at:=now(); end if;
  end if;
 end if;
 return new;
end $$;
revoke all on function public.guard_leave_request() from public,anon,authenticated;
create trigger aa_leave_request_authority before insert or update on public.leave_requests for each row execute function public.guard_leave_request();
-- Serialize requests for a typed person before checking overlap. The query
-- after this transaction lock sees the preceding committed request.
create or replace function public.leave_no_overlap() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$ begin
 if new.status not in ('pending','approved') then return new; end if;
 perform pg_advisory_xact_lock(hashtextextended(new.organization_id::text||':'||new.user_type||':'||new.user_id::text,617));
 if exists(select 1 from public.leave_requests r where r.organization_id=new.organization_id and r.user_id=new.user_id and r.user_type=new.user_type
  and r.id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid) and r.status in ('pending','approved') and r.start_date<=new.end_date and r.end_date>=new.start_date) then
  raise exception 'Overlapping leave: pending or approved request already covers these dates' using errcode='23505'; end if;
 return new;
end $$;
revoke all on function public.leave_no_overlap() from public,anon,authenticated;
-- Attendance must use the same typed identity as the approving leave request.
alter table public.attendance_records drop constraint if exists attendance_one_per_day;
create unique index attendance_typed_day on public.attendance_records(organization_id,user_type,user_id,work_date);
create or replace function public.leave_apply_to_attendance() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare d date;
begin
 if new.status<>'approved' or (tg_op='UPDATE' and old.status='approved') then return new; end if;
 d:=new.start_date;
 while d<=new.end_date loop
  insert into public.attendance_records(organization_id,user_id,user_type,work_date,status,source,note)
  values(new.organization_id,new.user_id,new.user_type,d,'on_leave','system','Approved leave #'||left(new.id::text,8))
  on conflict(organization_id,user_type,user_id,work_date) do update set status='on_leave',source='system',updated_at=now()
   where public.attendance_records.status in ('absent','on_leave');
  d:=d+1;
 end loop;
 return new;
end $$;
revoke all on function public.leave_apply_to_attendance() from public,anon,authenticated;
create function public.auth_attendance_permission(k text) returns boolean language sql stable security definer set search_path=pg_catalog,public as $$
 select exists(select 1 from public.memberships m where m.organization_id=public.auth_org() and m.user_id=public.auth_app_user_id()
  and m.user_type=auth.jwt()->'app_metadata'->>'user_type' and m.status='active' and m.user_type in ('admin','developer') and m.role<>'client')
 and case when k in ('attendance.view_own','attendance.log_own') then coalesce(public.auth_override(k),true)
 when k='attendance.view_all' then coalesce(public.auth_override(k),public.auth_role() in ('owner','admin','hr','manager'),false)
 when k='attendance.manage' then coalesce(public.auth_override(k),public.auth_role() in ('owner','admin','hr'),false) else false end;
$$;
revoke all on function public.auth_attendance_permission(text) from public,anon;
grant execute on function public.auth_attendance_permission(text) to authenticated;
drop policy if exists attendance_read on public.attendance_records;
drop policy if exists attendance_write_own on public.attendance_records;
drop policy if exists attendance_write_hr on public.attendance_records;
create policy attendance_effective_access on public.attendance_records for all to authenticated using(organization_id=public.auth_org()) with check(organization_id=public.auth_org());
create policy attendance_typed_read on public.attendance_records as restrictive for select to authenticated using(organization_id=public.auth_org()
 and (public.auth_attendance_permission('attendance.view_all') or (user_id=public.auth_app_user_id() and user_type=auth.jwt()->'app_metadata'->>'user_type' and public.auth_attendance_permission('attendance.view_own'))));
create policy attendance_typed_insert on public.attendance_records as restrictive for insert to authenticated with check(organization_id=public.auth_org() and public.auth_org_unlocked()
 and (public.auth_attendance_permission('attendance.manage') or (user_id=public.auth_app_user_id() and user_type=auth.jwt()->'app_metadata'->>'user_type' and public.auth_attendance_permission('attendance.log_own'))));
create policy attendance_typed_update on public.attendance_records as restrictive for update to authenticated using(organization_id=public.auth_org() and public.auth_org_unlocked()
 and (public.auth_attendance_permission('attendance.manage') or (user_id=public.auth_app_user_id() and user_type=auth.jwt()->'app_metadata'->>'user_type' and public.auth_attendance_permission('attendance.log_own'))))
 with check(organization_id=public.auth_org() and public.auth_org_unlocked() and (public.auth_attendance_permission('attendance.manage') or (user_id=public.auth_app_user_id() and user_type=auth.jwt()->'app_metadata'->>'user_type' and public.auth_attendance_permission('attendance.log_own'))));
create policy attendance_typed_delete on public.attendance_records as restrictive for delete to authenticated using(organization_id=public.auth_org() and public.auth_org_unlocked() and public.auth_attendance_permission('attendance.manage'));
create function public.guard_attendance_identity() returns trigger language plpgsql security invoker set search_path=pg_catalog,public as $$ begin
 if row(new.id,new.organization_id,new.user_id,new.user_type,new.work_date) is distinct from row(old.id,old.organization_id,old.user_id,old.user_type,old.work_date) then
  raise exception 'Attendance identity and date are immutable' using errcode='42501'; end if;
 return new;
end $$;
revoke all on function public.guard_attendance_identity() from public,anon,authenticated;
create trigger attendance_identity before update on public.attendance_records for each row execute function public.guard_attendance_identity();
-- Keep existing balance semantics but never aggregate colliding profile IDs.
create or replace view public.leave_balances_v with(security_invoker=true) as
select lt.organization_id,r.user_id,lt.id as leave_type_id,lt.code,lt.name,extract(year from r.start_date)::int as leave_year,lt.annual_quota_days,
 coalesce(sum(r.days) filter(where r.status='approved'),0)::numeric(6,1) as taken_days,
 coalesce(sum(r.days) filter(where r.status='pending'),0)::numeric(6,1) as pending_days,
 case when lt.annual_quota_days is null then null else (lt.annual_quota_days-coalesce(sum(r.days) filter(where r.status='approved'),0))::numeric(6,1) end as remaining_days,
 r.user_type
from public.leave_requests r join public.leave_types lt on lt.id=r.leave_type_id and lt.organization_id=r.organization_id
 group by lt.organization_id,r.user_id,r.user_type,lt.id,lt.code,lt.name,extract(year from r.start_date),lt.annual_quota_days;

-- SOURCE: 20260911180815_production_organization_deletion_lifecycle.sql
-- SHA256: 7b2289547b16c39b0da59a0d92f7d6938e0c93e528b3de9b668870033769dc3b
-- Durable records intentionally have no organization FK: recovery and read-only
-- receipts survive deleting the tenant. No Auth or Storage rows are mutated here.
create table app_private.organization_deletions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null unique,organization_name text not null,
 actor_id uuid not null,actor_type text not null,auth_user_id uuid not null,receipt_hash text not null unique,
 status text not null default 'pending' check(status in ('pending','processing','retry','completed')),
 stage text not null default 'billing' check(stage in ('billing','storage','auth','database','completed')),
 stripe_customer_id text,stripe_subscription_id text,lease uuid,lease_until timestamptz,
 attempts integer not null default 0,next_attempt_at timestamptz not null default now(),last_error text,
 created_at timestamptz not null default now(),completed_at timestamptz);
create table app_private.organization_deletion_items(
 id uuid primary key default gen_random_uuid(),job_id uuid not null references app_private.organization_deletions on delete cascade,
 kind text not null check(kind in ('storage','auth')),resource_id text not null,bucket text,path text,profile_id uuid,profile_type text,invitation_id uuid,
 status text not null default 'pending' check(status in ('pending','done','retained')),unique(job_id,kind,resource_id));
alter table app_private.organization_deletions enable row level security;
alter table app_private.organization_deletion_items enable row level security;
revoke all on app_private.organization_deletions,app_private.organization_deletion_items from public,anon,authenticated,service_role;
create function app_private.organization_deleting(p_org uuid) returns boolean language sql stable security definer set search_path=pg_catalog,app_private as $$
 select exists(select 1 from app_private.organization_deletions where organization_id=p_org);
$$;
revoke all on function app_private.organization_deleting(uuid) from public,anon,authenticated;
grant execute on function app_private.organization_deleting(uuid) to service_role;
-- Membership flags make service API authentication fail closed without a new
-- unbounded lookup on every route. The dedicated recovery endpoint opts in.
alter table public.memberships add column deletion_blocked boolean not null default false;
create or replace function public.auth_org() returns uuid language sql stable security definer set search_path=pg_catalog,public,app_private as $$
 select m.organization_id from public.memberships m where auth.uid() is not null
 and m.organization_id=nullif(auth.jwt()->'app_metadata'->>'organization_id','')::uuid
 and m.user_id=nullif(auth.jwt()->'app_metadata'->>'app_user_id','')::uuid
 and m.user_type=auth.jwt()->'app_metadata'->>'user_type' and m.status='active' and not m.deletion_blocked
 and public.role_rank(m.role) is not null and (m.user_type='client')=(m.role='client')
 and not app_private.organization_deleting(m.organization_id) limit 1;
$$;
-- Independent of the optional Storage accounting migration. Resolve only
-- evidenced application paths; conflicting legacy references never authorize.
create function app_private.deletion_storage_org(p_bucket text,p_name text) returns uuid
language plpgsql stable security definer set search_path=pg_catalog,public as $$
declare segment text:=split_part(p_name,'/',1); candidate uuid; legacy uuid; n int;
begin
 if p_bucket not in ('task-submissions','monitoring','org-files','invoices') then return null; end if;
 if p_bucket='monitoring' and not exists(select 1 from public.developers where organization_id::text=segment and id::text=split_part(p_name,'/',2) and split_part(p_name,'/',3)<>'') then return null; end if;
 if p_bucket='task-submissions' then
  if segment='pm' then segment:=split_part(p_name,'/',2);
  elsif segment='submissions' then
   select organization_id into candidate from public.developers where id::text=split_part(p_name,'/',2);
   return candidate;
  end if;
 end if;
 select id into candidate from public.organizations where id::text=segment;
 if p_bucket in ('screenshots','documents','monitoring') then
  select count(distinct organization_id),min(organization_id::text)::uuid into n,legacy from public.screenshots where storage_path=p_name;
  if n>1 or (candidate is not null and legacy is not null and candidate<>legacy) then return null; end if;
  -- Mutable screenshot rows are not independent ownership proof. Legacy
  -- paths remain unresolved and block deletion when referenced by this org.
 end if;
 return candidate;
end $$;
revoke all on function app_private.deletion_storage_org(text,text) from public,anon,authenticated;
create function app_private.deletion_worker_context(p_org uuid) returns boolean language sql stable security definer set search_path=pg_catalog,app_private as $$
 select (current_setting('role',true)='service_role' or (coalesce(current_setting('role',true),'none') in ('none','postgres','supabase_admin') and session_user in ('postgres','supabase_admin')))
 and exists(select 1 from app_private.organization_deletions where organization_id=p_org and lease::text=current_setting('app.deletion_lease',true) and lease_until>now() and status='processing');
$$;
create function public.guard_organization_deleting() returns trigger language plpgsql security invoker set search_path=pg_catalog,public,app_private as $$
declare org uuid; old_org uuid;
begin
 if tg_table_name='organizations' then
  if tg_op<>'DELETE' then org:=new.id; end if;if tg_op<>'INSERT' then old_org:=old.id; end if;
 else
  if tg_op<>'DELETE' then org:=(to_jsonb(new)->>'organization_id')::uuid; end if;
  if tg_op<>'INSERT' then old_org:=(to_jsonb(old)->>'organization_id')::uuid; end if;
 end if;
 -- Serialize writes with the start snapshot using the same physical quota lock.
 if org is not null and exists(select 1 from public.organizations where id=org) then perform app_private.lock_quota(org); end if;
 if old_org is not null and old_org is distinct from org and exists(select 1 from public.organizations where id=old_org) then perform app_private.lock_quota(old_org); end if;
 if (app_private.organization_deleting(org) and not (app_private.deletion_worker_context(org)))
 or (app_private.organization_deleting(old_org) and not (app_private.deletion_worker_context(old_org))) then
  raise exception 'Organization deletion is in progress' using errcode='42501'; end if;
 if tg_table_name='memberships' and ((tg_op='INSERT' and (to_jsonb(new)->>'deletion_blocked')::boolean) or (tg_op='UPDATE' and to_jsonb(new)->'deletion_blocked' is distinct from to_jsonb(old)->'deletion_blocked')) and not app_private.deletion_worker_context(org) then raise exception 'Deletion access flag is managed by the deletion lifecycle' using errcode='42501'; end if;
 if tg_op='DELETE' then return old; end if;return new;
end $$;
-- Trigger must resolve the private predicate without giving clients ledger access.
alter function public.guard_organization_deleting() security definer;
revoke all on function public.guard_organization_deleting() from public,anon,authenticated;
do $$ declare t record;begin
 for t in select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
 where n.nspname='public' and c.relkind='r' and (c.relname='organizations' or exists(select 1 from pg_attribute a where a.attrelid=c.oid and a.attname='organization_id' and not a.attisdropped)) loop
  execute format('create trigger aaa_organization_deleting before insert or update or delete on public.%I for each row execute function public.guard_organization_deleting()',t.relname);
 end loop;
end $$;
create function public.guard_deleting_storage() returns trigger language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare org uuid;begin
 org:=app_private.deletion_storage_org(new.bucket_id,new.name);
 if org is not null then perform app_private.lock_quota(org); end if;
 if tg_op='UPDATE' and app_private.deletion_storage_org(old.bucket_id,old.name) is not null and app_private.deletion_storage_org(old.bucket_id,old.name) is distinct from org then perform app_private.lock_quota(app_private.deletion_storage_org(old.bucket_id,old.name)); end if;
 if app_private.organization_deleting(org) or (tg_op='UPDATE' and app_private.organization_deleting(app_private.deletion_storage_org(old.bucket_id,old.name))) then raise exception 'Organization deletion is in progress' using errcode='42501'; end if;
 return new;
end $$;
revoke all on function public.guard_deleting_storage() from public,anon,authenticated;
create trigger aaa_organization_deleting before insert or update on storage.objects for each row execute function public.guard_deleting_storage();

create function public.guard_deleting_auth_link() returns trigger language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare linked_org uuid;begin
 if new.auth_user_id is not null then
  select o.id into linked_org from auth.users u join public.organizations o on o.id::text=u.raw_app_meta_data->>'organization_id' where u.id=new.auth_user_id;
  if linked_org is not null then perform app_private.lock_quota(linked_org); end if;
 end if;
 if new.auth_user_id is not null and (tg_op='INSERT' or new.auth_user_id is distinct from old.auth_user_id) and exists(
 select 1 from app_private.organization_deletion_items i join app_private.organization_deletions j on j.id=i.job_id
 where i.kind='auth' and i.resource_id=new.auth_user_id::text and i.status<>'retained' and j.status<>'completed') then
 raise exception 'Auth identity is scheduled for deletion' using errcode='42501'; end if;return new;
end $$;
revoke all on function public.guard_deleting_auth_link() from public,anon,authenticated;
create trigger deleting_auth_link before insert or update of auth_user_id on public.admin_users for each row execute function public.guard_deleting_auth_link();
create trigger deleting_auth_link before insert or update of auth_user_id on public.developers for each row execute function public.guard_deleting_auth_link();
create trigger deleting_auth_link before insert or update of auth_user_id on public.clients for each row execute function public.guard_deleting_auth_link();

create function public.guard_deleting_invitation_attempt() returns trigger language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare org uuid;begin
 select organization_id into org from public.invitations where id=new.invitation_id;
 if org is not null then perform app_private.lock_quota(org); end if;
 if app_private.organization_deleting(org) and not app_private.deletion_worker_context(org) then raise exception 'Organization deletion is in progress' using errcode='42501'; end if;
 return new;
end $$;
revoke all on function public.guard_deleting_invitation_attempt() from public,anon,authenticated;
do $$ begin if to_regclass('app_private.invitation_attempts') is not null then
 execute 'create trigger deleting_invitation_attempt before insert or update on app_private.invitation_attempts for each row execute function public.guard_deleting_invitation_attempt()';
end if;end $$;

create function public.start_organization_deletion(p_org uuid,p_actor uuid,p_type text,p_auth uuid,p_name text,p_receipt_hash text)
returns uuid language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare m public.memberships%rowtype; j app_private.organization_deletions%rowtype; org_name text; linked uuid; busy boolean; nonce uuid:=gen_random_uuid();
begin
 perform app_private.lock_quota(p_org);
 select * into m from public.memberships where organization_id=p_org and user_id=p_actor and user_type=p_type and status='active' for update;
 if not found or m.role<>'owner' or p_type not in ('admin','developer') or not coalesce((select allowed from public.user_permissions where membership_id=m.id and permission_key='organization.delete'),true) then raise exception 'Deletion requires the active owner' using errcode='42501'; end if;
 if p_type='admin' then select auth_user_id into linked from public.admin_users where id=p_actor and organization_id=p_org;
 else select auth_user_id into linked from public.developers where id=p_actor and organization_id=p_org; end if;
 if linked is distinct from p_auth or not exists(select 1 from auth.users where id=p_auth and raw_app_meta_data->>'organization_id'=p_org::text and raw_app_meta_data->>'app_user_id'=p_actor::text and raw_app_meta_data->>'user_type'=p_type and raw_app_meta_data->>'role'='owner') then raise exception 'Owner identity must be verified' using errcode='42501'; end if;
 select * into j from app_private.organization_deletions where organization_id=p_org for update;
 if found then
  if p_name is distinct from j.organization_name or p_receipt_hash is null or p_receipt_hash !~ '^[0-9a-f]{64}$' then raise exception 'Confirm the exact organization name' using errcode='22023'; end if;
  update app_private.organization_deletions set receipt_hash=p_receipt_hash where id=j.id;return j.id; end if;
 select name into org_name from public.organizations where id=p_org for update;
 if not found or p_name is distinct from org_name or p_receipt_hash !~ '^[0-9a-f]{64}$' then raise exception 'Confirm the exact organization name' using errcode='22023'; end if;
 if exists(select 1 from storage.objects o where app_private.deletion_storage_org(o.bucket_id,o.name) is null and
  (exists(select 1 from public.screenshots s where s.organization_id=p_org and s.storage_path=o.name)
   or exists(select 1 from auth.users u where u.id::text=coalesce(to_jsonb(o)->>'owner_id',to_jsonb(o)->>'owner') and u.raw_app_meta_data->>'organization_id'=p_org::text))) then
  raise exception 'Legacy or ambiguous storage ownership requires repair before organization deletion' using errcode='22023'; end if;
 if to_regclass('app_private.invitation_attempts') is not null then
  execute 'select exists(select 1 from app_private.invitation_attempts a join public.invitations i on i.id=a.invitation_id where i.organization_id=$1 and a.completed_at is null and a.lease_until>now())' into busy using p_org;
  if busy then raise exception 'Invitation acceptance is in progress; retry deletion shortly' using errcode='22023'; end if;
 end if;
 insert into app_private.organization_deletions(organization_id,organization_name,actor_id,actor_type,auth_user_id,receipt_hash,status,lease,lease_until,stripe_customer_id,stripe_subscription_id)
 select p_org,org_name,p_actor,p_type,p_auth,p_receipt_hash,'processing',nonce,now()+interval '10 minutes',s.stripe_customer_id,s.stripe_subscription_id
 from (select 1) x left join public.organization_subscriptions s on s.organization_id=p_org returning * into j;
 perform set_config('app.deletion_lease',nonce::text,true);
 update public.memberships set deletion_blocked=true where organization_id=p_org;
 insert into app_private.organization_deletion_items(job_id,kind,resource_id,bucket,path)
 select j.id,'storage',o.id::text,o.bucket_id,o.name from storage.objects o where app_private.deletion_storage_org(o.bucket_id,o.name)=p_org;
 -- Include only linked profiles in this org. Shared or mismatched links are
 -- marked retained at execution; no password or Auth credential is inspected.
 insert into app_private.organization_deletion_items(job_id,kind,resource_id,profile_id,profile_type)
 select j.id,'auth',auth_user_id::text,id,kind from (
 select id,auth_user_id,'admin'::text kind from public.admin_users where organization_id=p_org and auth_user_id is not null
 union all select id,auth_user_id,'developer' from public.developers where organization_id=p_org and auth_user_id is not null
 union all select id,auth_user_id,'client' from public.clients where organization_id=p_org and auth_user_id is not null) p
 on conflict(job_id,kind,resource_id) do nothing;
 if to_regclass('app_private.invitation_attempts') is not null then
  execute $q$insert into app_private.organization_deletion_items(job_id,kind,resource_id,profile_id,profile_type,invitation_id)
   select $1,'auth',a.auth_user_id::text,a.profile_id,case when i.role='admin' then 'admin' when i.role='client' then 'client' else 'developer' end,i.id
   from app_private.invitation_attempts a join public.invitations i on i.id=a.invitation_id where i.organization_id=$2
   on conflict(job_id,kind,resource_id) do nothing$q$ using j.id,p_org;
 end if;
 update app_private.organization_deletions set status='pending',lease=null,lease_until=null where id=j.id;
 return j.id;
end $$;

create function public.organization_deletion_status(p_org uuid default null,p_auth uuid default null,p_receipt_hash text default null)
returns jsonb language sql stable security definer set search_path=pg_catalog,app_private as $$
 select jsonb_build_object('id',j.id,'status',j.status,'stage',j.stage,'createdAt',j.created_at,'completedAt',j.completed_at,'lastError',j.last_error,'organizationName',j.organization_name,
 'counts',jsonb_build_object('storagePending',count(*) filter(where i.kind='storage' and i.status='pending'),'storageDone',count(*) filter(where i.kind='storage' and i.status='done'),
 'authPending',count(*) filter(where i.kind='auth' and i.status='pending'),'authDone',count(*) filter(where i.kind='auth' and i.status='done'),'authRetained',count(*) filter(where i.kind='auth' and i.status='retained')))
 from app_private.organization_deletions j left join app_private.organization_deletion_items i on i.job_id=j.id
 where (p_receipt_hash is not null and j.receipt_hash=p_receipt_hash) or (j.organization_id=p_org and j.auth_user_id=p_auth) group by j.id;
$$;
create function public.organization_deletion_active(p_org uuid) returns boolean language sql stable security definer set search_path=pg_catalog,app_private as $$ select app_private.organization_deleting(p_org) $$;
create function public.handle_deletion_billing_event(p_org uuid,p_customer text,p_subscription text,p_reconcile boolean default false)
returns boolean language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare j app_private.organization_deletions%rowtype;begin
 select * into j from app_private.organization_deletions where (p_org is null or organization_id=p_org)
 and ((p_customer is not null and stripe_customer_id=p_customer) or (p_subscription is not null and stripe_subscription_id=p_subscription)) for update;
 if not found then return false; end if;
 -- Signed late billable events never resurrect a deleted workspace. Recheck
 -- provider cancellation through the durable worker, even after DB teardown.
 if p_reconcile and j.stage<>'billing' then
  update app_private.organization_deletions set stage='billing',status='pending',lease=null,lease_until=null,next_attempt_at=now(),completed_at=null where id=j.id;
 end if;
 return true;
end $$;
create function public.claim_organization_deletion(p_org uuid default null,p_retry boolean default false)
returns jsonb language plpgsql security definer set search_path=pg_catalog,app_private as $$
declare j app_private.organization_deletions%rowtype;begin
 update app_private.organization_deletion_items i set status='pending' from app_private.organization_deletions archived_job,auth.users u
 where i.job_id=archived_job.id and archived_job.status='completed' and i.kind='auth' and i.status='done' and u.id::text=i.resource_id
 and u.raw_app_meta_data->>'organization_id'=archived_job.organization_id::text and u.raw_app_meta_data->>'app_user_id'=i.profile_id::text and u.raw_app_meta_data->>'user_type'=i.profile_type;
 update app_private.organization_deletions archived_job set status='pending',stage='auth',completed_at=null,next_attempt_at=now()
 where status='completed' and exists(select 1 from app_private.organization_deletion_items where job_id=archived_job.id and status='pending');
 select * into j from app_private.organization_deletions where status<>'completed' and (p_org is null or organization_id=p_org)
 and (lease_until is null or lease_until<now()) and (p_retry or next_attempt_at<=now()) order by created_at for update skip locked limit 1;
 if not found then return null; end if;
 update app_private.organization_deletions set status='processing',lease=gen_random_uuid(),lease_until=now()+interval '10 minutes',attempts=attempts+1 where id=j.id returning * into j;
 return to_jsonb(j)-'receipt_hash';
end $$;
create function public.organization_deletion_items(p_job uuid,p_lease uuid,p_kind text)
returns jsonb language sql stable security definer set search_path=pg_catalog,app_private as $$
 select coalesce(jsonb_agg(to_jsonb(i)),'[]') from (select i.* from app_private.organization_deletion_items i join app_private.organization_deletions j on j.id=i.job_id
 where j.id=p_job and j.lease=p_lease and j.lease_until>now() and j.status='processing' and i.kind=p_kind and i.status='pending'
 order by (i.resource_id=j.auth_user_id::text),i.id limit 25) i;
$$;
create function public.check_deletion_storage_item(p_job uuid,p_lease uuid,p_item uuid)
returns text language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare j app_private.organization_deletions%rowtype;i app_private.organization_deletion_items%rowtype;begin
 select * into j from app_private.organization_deletions where id=p_job and lease=p_lease and lease_until>now() and status='processing';
 if not found then raise exception 'Deletion lease expired' using errcode='42501'; end if;
 select * into i from app_private.organization_deletion_items where id=p_item and job_id=j.id and kind='storage' and status='pending';
 if not found then raise exception 'Deletion item missing'; end if;
 if exists(select 1 from storage.objects where id::text=i.resource_id and bucket_id=i.bucket and name=i.path and app_private.deletion_storage_org(bucket_id,name)=j.organization_id) then return 'present'; end if;
 if not exists(select 1 from storage.objects where id::text=i.resource_id or (bucket_id=i.bucket and name=i.path)) then return 'absent'; end if;
 raise exception 'Storage identity changed; refusing deletion';
end $$;
create function public.check_deletion_auth_identity(p_job uuid,p_lease uuid,p_item uuid)
returns boolean language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare j app_private.organization_deletions%rowtype;i app_private.organization_deletion_items%rowtype;n int;begin
 select * into j from app_private.organization_deletions where id=p_job and lease=p_lease and lease_until>now() and status='processing';
 if not found then raise exception 'Deletion lease expired' using errcode='42501'; end if;
 select * into i from app_private.organization_deletion_items where id=p_item and job_id=j.id and kind='auth' and status='pending';
 if not found then return false; end if;
 select count(*) into n from (select id,organization_id,auth_user_id,'admin'::text kind from public.admin_users union all select id,organization_id,auth_user_id,'developer' from public.developers union all select id,organization_id,auth_user_id,'client' from public.clients) p
 where auth_user_id::text=i.resource_id and (organization_id is distinct from j.organization_id or id is distinct from i.profile_id or kind is distinct from i.profile_type);
 if n<>0 or exists(select 1 from public.memberships where user_id=i.profile_id and user_type=i.profile_type and organization_id<>j.organization_id) then return false; end if;
 return exists(select 1 from auth.users where id::text=i.resource_id and raw_app_meta_data->>'organization_id'=j.organization_id::text and raw_app_meta_data->>'app_user_id'=i.profile_id::text and raw_app_meta_data->>'user_type'=i.profile_type and (i.invitation_id is null or raw_app_meta_data->>'invitation_id'=i.invitation_id::text));
end $$;
create function public.finish_organization_deletion_step(p_job uuid,p_lease uuid,p_stage text default null,p_item uuid default null,p_retained boolean default false,p_error boolean default false)
returns boolean language plpgsql security definer set search_path=pg_catalog,app_private as $$
declare j app_private.organization_deletions%rowtype;begin
 select * into j from app_private.organization_deletions where id=p_job and lease=p_lease and lease_until>now() and status='processing' for update;
 if not found then raise exception 'Deletion lease expired' using errcode='42501'; end if;
 if p_item is not null then update app_private.organization_deletion_items set status=case when p_retained then 'retained' else 'done' end where id=p_item and job_id=j.id; end if;
 if p_error then update app_private.organization_deletions set status='retry',last_error='Cleanup could not finish. No completed step will be undone; retry is available.',next_attempt_at=now()+interval '5 minutes',lease=null,lease_until=null where id=j.id;
 elsif p_stage is not null then
  if p_stage not in ('storage','auth','database') then raise exception 'Invalid deletion stage'; end if;
  update app_private.organization_deletions set stage=p_stage,status='pending',lease=null,lease_until=null,next_attempt_at=now(),last_error=null where id=j.id;
 end if;
 return true;
end $$;

-- Accepted proposal provenance survives an explicitly deleted project.
alter table public.project_proposals add column deleted_project_id uuid,add column deleted_project_name text,add column project_deleted_at timestamptz;
create function public.preserve_deleted_proposal_project() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$ begin
 update public.project_proposals set deleted_project_id=old.id,deleted_project_name=old.name,project_deleted_at=now()
 where project_id=old.id and organization_id=old.organization_id and status='accepted';
 return old;
end $$;
revoke all on function public.preserve_deleted_proposal_project() from public,anon,authenticated;
create trigger preserve_proposal_project before delete on public.projects for each row execute function public.preserve_deleted_proposal_project();
create or replace function public.tg_proposal_guard() returns trigger language plpgsql set search_path=pg_catalog,public as $$ begin
 new.updated_at:=now();
 if new.status in ('rejected','needs_info') and nullif(btrim(new.decision_reason),'') is null then raise exception 'A decision needs a reason' using errcode='23514'; end if;
 if new.status='accepted' and new.project_id is null and not (tg_op='UPDATE' and old.status='accepted' and new.deleted_project_id is not null and new.project_deleted_at is not null
 and not exists(select 1 from public.projects where id=new.deleted_project_id)) then raise exception 'An accepted proposal must reference its project or its verified deletion history' using errcode='23514'; end if;
 if tg_op='UPDATE' and old.status='accepted' and new.status<>'accepted' then raise exception 'An accepted proposal cannot be un-accepted' using errcode='23514'; end if;
 if tg_op='UPDATE' and old.project_deleted_at is not null and ((new.deleted_project_id,new.deleted_project_name,new.project_deleted_at) is distinct from (old.deleted_project_id,old.deleted_project_name,old.project_deleted_at) or (new.project_id is distinct from old.project_id and not (old.project_id=old.deleted_project_id and new.project_id is null and not exists(select 1 from public.projects where id=old.deleted_project_id)))) then raise exception 'Deleted project provenance is immutable' using errcode='23514'; end if;
 if new.project_deleted_at is not null and (tg_op='INSERT' or old.project_deleted_at is null) and not (tg_op='UPDATE' and pg_trigger_depth()>1 and old.project_id=new.deleted_project_id and exists(select 1 from public.projects where id=new.deleted_project_id and name=new.deleted_project_name)) then raise exception 'Deletion history is created only by deleting its project' using errcode='23514'; end if;
 if new.status is distinct from old.status and new.status in ('accepted','rejected','needs_info') then new.decided_at:=coalesce(new.decided_at,now()); end if;
 return new;
end $$;
grant select(deleted_project_id,deleted_project_name,project_deleted_at) on public.project_proposals to authenticated;

create function public.finalize_organization_deletion(p_job uuid,p_lease uuid)
returns boolean language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare j app_private.organization_deletions%rowtype;t record;remaining int;changed int;passes int:=0;
begin
 select * into j from app_private.organization_deletions where id=p_job and lease=p_lease and lease_until>now() and status='processing' and stage='database' for update;
 if not found then raise exception 'Deletion lease or stage invalid' using errcode='42501'; end if;
 if exists(select 1 from app_private.organization_deletion_items where job_id=j.id and status='pending') then raise exception 'External cleanup is incomplete'; end if;
 if exists(select 1 from storage.objects where app_private.deletion_storage_org(bucket_id,name)=j.organization_id) then raise exception 'Storage cleanup is incomplete'; end if;
 if exists(select 1 from public.organizations where id=j.organization_id) then perform app_private.lock_quota(j.organization_id); end if;perform set_config('app.deletion_lease',p_lease::text,true);
 if to_regclass('app_private.tracking_retention_files') is not null then
  execute 'update app_private.tracking_retention_files r set status=''cancelled'' where organization_id=$1 and status in (''processing'',''failed'') and not exists(select 1 from storage.objects o where o.id::text=r.object_id)' using j.organization_id;
 end if;
 -- Private optional accounting rows are safe to remove only for absent objects.
 if to_regclass('app_private.storage_usage') is not null then
  execute 'delete from app_private.storage_usage u where organization_id=$1 and not exists(select 1 from storage.objects o where o.id::text=u.object_id)' using j.organization_id;
 end if;
 -- Existing legacy tables use SET NULL or no org FK. Delete exact-org rows
 -- explicitly; dependency passes preserve constraint checks and future tables.
 loop
  remaining:=0;changed:=0;passes:=passes+1;
  for t in select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'
   and exists(select 1 from pg_attribute a where a.attrelid=c.oid and a.attname='organization_id' and not a.attisdropped)
   order by case when c.relname='project_proposals' then 0 when c.relname='memberships' then 2 else 1 end,c.relname loop
   begin
    execute format('delete from public.%I where organization_id=$1',t.relname) using j.organization_id;
    get diagnostics remaining=row_count;changed:=changed+remaining;
   exception when foreign_key_violation then null; end;
  end loop;
  remaining:=0;
  for t in select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'
   and exists(select 1 from pg_attribute a where a.attrelid=c.oid and a.attname='organization_id' and not a.attisdropped) loop
   execute format('select count(*) from public.%I where organization_id=$1',t.relname) into changed using j.organization_id;remaining:=remaining+changed;
  end loop;
  exit when remaining=0;
  if passes>=20 then raise exception 'Organization dependencies require repair'; end if;
 end loop;
 delete from public.organizations where id=j.organization_id;
 update app_private.organization_deletions set status='completed',stage='completed',completed_at=now(),last_error=null,lease=null,lease_until=null where id=j.id;
 return true;
end $$;
do $$ declare f record;begin
 for f in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('organization_deletion_active','handle_deletion_billing_event','start_organization_deletion','organization_deletion_status','claim_organization_deletion','organization_deletion_items','check_deletion_auth_identity','check_deletion_storage_item','finish_organization_deletion_step','finalize_organization_deletion') loop
 execute format('revoke all on function %s from public,anon,authenticated',f.signature);execute format('grant execute on function %s to service_role',f.signature);
 end loop;
end $$;

-- SOURCE: 20260911182229_production_existing_leave_day_contract.sql
-- SHA256: db536fac6fd5ec21567f585ea4a56d011d36a8d85f5dc106a3a2a3ca127fbfe8
-- Preserve the existing MyLeave contract: calendar-day spans; only a single
-- calendar date may be a half-day. No holiday/workweek rule is introduced.
create function public.guard_leave_day_contract() returns trigger
language plpgsql security invoker set search_path=pg_catalog,public as $$ begin
 if tg_op='INSERT' or row(new.start_date,new.end_date,new.days) is distinct from row(old.start_date,old.end_date,old.days)
  or (new.status='approved' and old.status is distinct from 'approved') then
  if new.start_date=new.end_date then
   if new.days not in (0.5,1) or new.days is null then
    raise exception 'Single-date leave must be 0.5 or 1 day. Correct the request before approval.' using errcode='22023'; end if;
  elsif new.days is distinct from (new.end_date-new.start_date+1)::numeric then
   raise exception 'Multi-date leave must equal its full calendar-day span. Withdraw and resubmit the corrected request before approval.' using errcode='22023';
  end if;
 end if;
 return new;
end $$;
revoke all on function public.guard_leave_day_contract() from public,anon,authenticated;
create trigger ab_leave_day_contract before insert or update on public.leave_requests for each row execute function public.guard_leave_day_contract();
create or replace function public.leave_apply_to_attendance() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare d date;
begin
 if new.status<>'approved' or (tg_op='UPDATE' and old.status='approved') then return new; end if;
 -- Attendance has no fraction field. Do not overwrite a real check-in or create
 -- a false full-day absence for half-day leave. Its approved 0.5 remains in
 -- leave_requests and both capacity queries already account for that amount.
 if new.start_date=new.end_date and new.days=0.5 then return new; end if;
 d:=new.start_date;
 while d<=new.end_date loop
  insert into public.attendance_records(organization_id,user_id,user_type,work_date,status,source,note)
  values(new.organization_id,new.user_id,new.user_type,d,'on_leave','system','Approved leave #'||left(new.id::text,8))
  on conflict(organization_id,user_type,user_id,work_date) do update set status='on_leave',source='system',updated_at=now()
   where public.attendance_records.status in ('absent','on_leave');
  d:=d+1;
 end loop;
 return new;
end $$;
revoke all on function public.leave_apply_to_attendance() from public,anon,authenticated;

commit;
