import { NextResponse } from 'next/server';
import { sendEmail } from '@/utils/emailService';
import { renderTemplate } from '@/utils/emailTemplates';

export const dynamic = 'force-dynamic';

/**
 * SECURITY (audit finding H7): this route sends mail from the company's real
 * Gmail account and cannot require a JWT — it runs before the user is signed
 * in. It was previously an open relay: recipient, display name, company and
 * message type were all caller-controlled, enabling branded phishing and
 * quota exhaustion.
 *
 * Hardening applied here, none of which changes the legitimate flow:
 *   - recipient must be a syntactically valid address,
 *   - the caller can no longer choose the message at all: the body is one
 *     fixed template (`email_verification`) rendered by src/utils/
 *     emailTemplates.js. `type` and `role` used to select the subject, title
 *     and body text and were clamped to allowlists for that reason; they are
 *     no longer read, which is strictly stronger than clamping them,
 *   - the only caller-supplied strings that reach the message are the name,
 *     the company and the recipient, and all three are HTML-escaped and
 *     length-capped by the template module (one copy of `escapeHtml`, the one
 *     this file used to duplicate),
 *   - the code must be a short numeric string,
 *   - per-IP and per-recipient rate limits.
 *
 * STILL OUTSTANDING — the code itself: it is generated by the browser
 * (src/app/admin/registration/page.js) and compared by the browser. This route
 * only relays whatever number it is handed. Nothing server-side issues the
 * code, stores it, or knows when it was issued, so nothing server-side can
 * enforce the ten-minute expiry the email now states: the countdown on the
 * page is honest about the code the browser generated and no more. The route
 * is NOT the place to fix that on its own — see the note on TTL below.
 */

const MAX_PER_WINDOW = 5;
const WINDOW_MS = 10 * 60 * 1000; // 10 minutes

/**
 * How long the page tells the user the code lasts. It is stated in the email
 * so it must come from one place; the page uses the same ten minutes.
 *
 * This is COPY, not enforcement. Enforcement would need the code minted here,
 * stored server-side with an `expires_at`, and checked by a verify endpoint
 * that /api/auth/signup trusts — a change to signup's contract, which is out
 * of scope for this pass.
 */
const CODE_TTL_MINUTES = 10;

// Best-effort in-process limiter. Serverless instances each keep their own
// counter, so this caps abuse rather than eliminating it; a shared store would
// be needed for a hard guarantee.
const hits = new Map();

function rateLimited(key) {
  const now = Date.now();
  const bucket = (hits.get(key) || []).filter((t) => now - t < WINDOW_MS);
  bucket.push(now);
  hits.set(key, bucket);
  if (hits.size > 5000) hits.clear(); // crude memory bound
  return bucket.length > MAX_PER_WINDOW;
}

export async function POST(request) {
  try {
    const body = await request.json().catch(() => ({}));
    const rawEmail = typeof body.email === 'string' ? body.email.trim() : '';
    const rawCode = String(body.code ?? '');

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(rawEmail) || rawEmail.length > 254) {
      return NextResponse.json({ error: 'A valid email address is required' }, { status: 400 });
    }
    if (!/^\d{4,8}$/.test(rawCode)) {
      return NextResponse.json({ error: 'Invalid verification code' }, { status: 400 });
    }

    const ip =
      request.headers.get('x-forwarded-for')?.split(',')[0].trim() ||
      request.headers.get('x-real-ip') ||
      'unknown';
    if (rateLimited(`ip:${ip}`) || rateLimited(`to:${rawEmail.toLowerCase()}`)) {
      return NextResponse.json(
        { error: 'Too many verification emails requested. Please try again shortly.' },
        { status: 429 }
      );
    }

    const email = rawEmail;
    const code = rawCode;

    // One template, one subject, no branch on anything the caller sent. The
    // values below are handed over RAW on purpose: `renderTemplate` escapes and
    // length-caps every one of them, and escaping here as well would put
    // `&amp;lt;` in front of the recipient.
    const { subject, html, text } = renderTemplate('email_verification', {
      userName: body.userName,
      orgName: body.company,
      email,
      code,
      expiresInMinutes: CODE_TTL_MINUTES,
    });

    // The From address and transport come from the provider seam
    // (src/utils/emailProvider.js) instead of being built here, so this route
    // gets retries, rate limiting and an email_log row like every other send.
    //
    // Send through the single send path. It never throws: a failure comes back
    // as { ok: false }, so the 500 below is reserved for real bugs.
    const result = await sendEmail({
      to: email,
      subject,
      html,
      text,
      template: 'email_verification',
    });

    if (!result.ok) {
      // `result.error` is already redacted by the provider seam — no key
      // material can reach a response body through here.
      return NextResponse.json(
        { success: false, error: 'Failed to send verification code', details: result.error },
        { status: 502 }
      );
    }

    return NextResponse.json({
      success: true,
      message: 'Verification code sent successfully',
      to: email,
      messageId: result.messageId,
      mode: result.mode,
    });

  } catch (error) {
    // No `details` here: transport errors used to be echoed straight back to
    // the browser, and an SMTP client will happily quote the credential it
    // just tried in its own message.
    return NextResponse.json(
      { success: false, error: 'Failed to send verification code' },
      { status: 500 }
    );
  }
}