import { NextResponse } from 'next/server';
import { sendEmail } from '@/utils/emailService';

export const dynamic = 'force-dynamic';

/**
 * SECURITY (audit finding H7): this route sends mail from the company's real
 * Gmail account and cannot require a JWT — it runs before the user is signed
 * in. It was previously an open relay: recipient, display name, company and
 * message type were all caller-controlled, enabling branded phishing and
 * quota exhaustion.
 *
 * Hardening applied here, none of which changes the legitimate flow:
 *   - recipient must be a syntactically valid address,
 *   - `type` and `role` are clamped to known values, so the caller cannot
 *     compose arbitrary email content,
 *   - free-text fields are HTML-escaped and length-capped (they are
 *     interpolated into the message body),
 *   - the code must be a short numeric string,
 *   - per-IP and per-recipient rate limits.
 *
 * STILL OUTSTANDING: the verification code is generated by the client and only
 * compared client-side. Moving code generation and verification server-side is
 * a larger change and is not attempted here.
 */

const ALLOWED_TYPES = ['login', 'registration'];
const ALLOWED_ROLES = ['user', 'admin', 'developer', 'client', 'employee', 'manager', 'team_lead', 'hr', 'owner'];
const MAX_PER_WINDOW = 5;
const WINDOW_MS = 10 * 60 * 1000; // 10 minutes

// Best-effort in-process limiter. Serverless instances each keep their own
// counter, so this caps abuse rather than eliminating it; a shared store would
// be needed for a hard guarantee.
const hits = new Map();

function rateLimited(key) {
  const now = Date.now();
  const bucket = (hits.get(key) || []).filter((t) => now - t < WINDOW_MS);
  bucket.push(now);
  hits.set(key, bucket);
  if (hits.size > 5000) hits.clear(); // crude memory bound
  return bucket.length > MAX_PER_WINDOW;
}

function escapeHtml(value, maxLen = 80) {
  return String(value ?? '')
    .slice(0, maxLen)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export async function POST(request) {
  try {
    const body = await request.json().catch(() => ({}));
    const rawEmail = typeof body.email === 'string' ? body.email.trim() : '';
    const rawCode = String(body.code ?? '');

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(rawEmail) || rawEmail.length > 254) {
      return NextResponse.json({ error: 'A valid email address is required' }, { status: 400 });
    }
    if (!/^\d{4,8}$/.test(rawCode)) {
      return NextResponse.json({ error: 'Invalid verification code' }, { status: 400 });
    }

    const ip =
      request.headers.get('x-forwarded-for')?.split(',')[0].trim() ||
      request.headers.get('x-real-ip') ||
      'unknown';
    if (rateLimited(`ip:${ip}`) || rateLimited(`to:${rawEmail.toLowerCase()}`)) {
      return NextResponse.json(
        { error: 'Too many verification emails requested. Please try again shortly.' },
        { status: 429 }
      );
    }

    const email = rawEmail;
    const code = rawCode;
    const userName = escapeHtml(body.userName || 'there');
    const company = escapeHtml(body.company || '');
    const type = ALLOWED_TYPES.includes(body.type) ? body.type : 'login';
    const role = ALLOWED_ROLES.includes(body.role) ? body.role : 'user';

    // Determine email subject and content based on type
    const getEmailContent = () => {
      if (type === "login") {
        return {
          subject: `Login Verification Code: ${code}`,
          title: `${role.charAt(0).toUpperCase() + role.slice(1)} Login Verification`,
          greeting: `Hello <strong>${userName}</strong>,`,
          message: `Your verification code for ${role} login is:`
        };
      } else {
        return {
          subject: `Admin Registration Verification Code: ${code}`,
          title: 'Admin Registration Verification',
          greeting: `Hello <strong>${userName}</strong>,`,
          message: 'Your verification code for admin registration is:'
        };
      }
    };

    const emailContent = getEmailContent();

    // The From address and transport now come from the provider seam
    // (src/utils/emailProvider.js) instead of being built here, so this route
    // gets retries, rate limiting and an email_log row like every other send.
    const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: #009578; color: white; padding: 20px; text-align: center; border-radius: 10px 10px 0 0;">
            <h1>${emailContent.title}</h1>
          </div>
          
          <div style="padding: 30px; background: white;">
            <p>${emailContent.greeting}</p>
            
            <p>${emailContent.message}</p>
            
            <div style="background: #f4f4f4; padding: 25px; text-align: center; font-size: 32px; font-weight: bold; letter-spacing: 10px; margin: 20px 0; border-radius: 8px; border: 2px dashed #009578;">
              ${code}
            </div>
            
            <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;">
              <p><strong>Name:</strong> ${userName}</p>
              <p><strong>Company:</strong> ${company}</p>
              <p><strong>Email:</strong> ${escapeHtml(email, 254)}</p>
              <p><strong>Role:</strong> ${role.charAt(0).toUpperCase() + role.slice(1)}</p>
            </div>
            
          
          </div>
          
         
        </div>
      `;

    // Send through the single send path. It never throws: a failure comes back
    // as { ok: false }, so the 500 below is reserved for real bugs.
    const result = await sendEmail({
      to: email,
      subject: emailContent.subject,
      html,
      template: 'verification',
    });

    if (!result.ok) {
      // `result.error` is already redacted by the provider seam — no key
      // material can reach a response body through here.
      return NextResponse.json(
        { success: false, error: 'Failed to send verification code', details: result.error },
        { status: 502 }
      );
    }

    return NextResponse.json({
      success: true,
      message: 'Verification code sent successfully',
      to: email,
      messageId: result.messageId,
      mode: result.mode,
    });

  } catch (error) {
    // No `details` here: transport errors used to be echoed straight back to
    // the browser, and an SMTP client will happily quote the credential it
    // just tried in its own message.
    return NextResponse.json(
      { success: false, error: 'Failed to send verification code' },
      { status: 500 }
    );
  }
}