import { beforeEach, expect, it, vi } from 'vitest';
const h=vi.hoisted(()=>({values:[],refs:[],effects:[],cursor:0,refCursor:0,identity:'first',denied:[],fetch:vi.fn(),authChanged:null}));
vi.mock('react',async()=>({...await vi.importActual('react'),useState:initial=>{const i=h.cursor++;if(!(i in h.values))h.values[i]=typeof initial==='function'?initial():initial;return[h.values[i],value=>{h.values[i]=typeof value==='function'?value(h.values[i]):value;}];},useRef:initial=>{const i=h.refCursor++;return h.refs[i]||={current:initial};},useEffect:callback=>{h.effects.push(callback);}}));
vi.mock('@/contexts/AuthContext',()=>({useAuth:()=>({authStatus:'authenticated'})}));
vi.mock('@/utils/orgContext',()=>({getOrgContext:()=>({organizationId:'org',identity:h.identity})}));vi.mock('@/utils/reportViewState',()=>({reportIdentity:value=>value.identity}));vi.mock('@/utils/permissions',()=>({allowed:key=>!h.denied.includes(key)}));
vi.mock('@/utils/supabaseClient',()=>({supabase:{auth:{onAuthStateChange:callback=>{h.authChanged=callback;return{data:{subscription:{unsubscribe(){}}}};}}}}));
vi.mock('@/utils/authFetch',()=>({authFetch:h.fetch}));vi.mock('@/components/ui',()=>({Button:'button'}));
globalThis.React=await vi.importActual('react');const {default:View}=await import('@/components/shared/GithubIssueSync');
const props={projectId:'project',link:{repository_id:123,version:1},number:1,token:'github_pat_fixture',onClose:vi.fn()};
function nodes(node,predicate){if(!node||typeof node!=='object')return[];return[...(predicate(node)?[node]:[]),...[].concat(node.props?.children||[]).flat(Infinity).flatMap(child=>nodes(child,predicate))];}
function render(){h.cursor=0;h.refCursor=0;return View(props);}
async function preview(){let tree=render();h.effects[0]();h.effects[1]();tree=render();await nodes(tree,n=>n.type==='button'&&n.props.children==='Preview task refresh')[0].props.onClick();return render();}
const payload=()=>({success:true,project_id:'project',organization_id:'org',version:1,snapshot:{import_id:'import'},expected:'a'.repeat(32),fingerprint:'b'.repeat(64),fields:[{field:'title',baseline:'Old',local:'Local',incoming:'Remote',conflict:true,suggested:'',action:'keep'},{field:'description',baseline:'Body',local:'Body',incoming:'<script>plain</script>',conflict:false,suggested:'auto',action:'update'}]});
beforeEach(()=>{Object.assign(h,{values:[],refs:[],effects:[],identity:'first',denied:[]});h.fetch.mockReset();h.fetch.mockImplementation(async()=>Response.json(payload()));});
it('requires a conflict choice and renders source as plain text',async()=>{let tree=await preview();expect(nodes(tree,n=>n.type==='pre').map(n=>n.props.children)).toContain('<script>plain</script>');expect(nodes(tree,n=>n.type==='button'&&n.props.type==='submit')[0].props.disabled).toBe(true);const select=nodes(tree,n=>n.type==='select')[0];expect(nodes(select,n=>n.type==='option').map(n=>n.props.value)).not.toContain('auto');select.props.onChange({target:{value:'local'}});tree=render();expect(nodes(tree,n=>n.type==='button'&&n.props.type==='submit')[0].props.disabled).toBeFalsy();});
it('retries an uncertain write with the same id and keeps token out of URLs',async()=>{let tree=await preview();nodes(tree,n=>n.type==='select')[0].props.onChange({target:{value:'github'}});h.fetch.mockRejectedValue(new Error('Connection lost'));await nodes(render(),n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,0));await nodes(render(),n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,0));const first=JSON.parse(h.fetch.mock.calls[1][1].body),second=JSON.parse(h.fetch.mock.calls[2][1].body);expect(first.id).toBeTruthy();expect(second.id).toBe(first.id);expect(first.title).toBe('github');expect(first.githubToken).toBe('github_pat_fixture');expect(h.fetch.mock.calls.every(c=>!c[0].includes('github_pat_fixture'))).toBe(true);});
it('hides preview on tenant change or read permission revocation',async()=>{await preview();h.identity='second';expect(nodes(render(),n=>n.type==='pre')).toHaveLength(0);h.denied=['task.view_all','task.review'];expect(render()).toBeNull();});
it('discards a pending response after sign-out notification',async()=>{let resolve;h.fetch.mockImplementation(()=>new Promise(r=>resolve=r));render();h.effects[0]();h.effects[1]();const pending=nodes(render(),n=>n.type==='button')[0].props.onClick();h.authChanged();resolve(Response.json(payload()));await pending;expect(nodes(render(),n=>n.type==='pre')).toHaveLength(0);});
