import { beforeEach,expect,it,vi } from 'vitest';
const state=vi.hoisted(()=>({auth:null,rpc:vi.fn(),process:vi.fn()}));
vi.mock('@/utils/serverAuth',()=>({getAuthedOrg:vi.fn(async()=>state.auth),serviceClient:()=>({rpc:state.rpc,from:()=>{const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:{name:'Acme'}})};return q;}})}));
vi.mock('@/utils/organizationDeletion',()=>({processOrganizationDeletion:(...args)=>state.process(...args)}));
import {GET,POST,PATCH} from '../src/app/api/organizations/delete/route';
const req=(body={},query='')=>new Request(`http://localhost/api/organizations/delete${query}`,{method:'POST',body:JSON.stringify(body)});
beforeEach(()=>{state.auth={orgId:'org',appUserId:'owner',userId:'auth',userType:'admin',role:'owner',overrides:{}};state.rpc.mockReset().mockImplementation(async name=>({data:name==='start_organization_deletion'?'job':null}));state.process.mockReset();});
it.each(['admin','manager','developer','client'])('rejects %s even with explicit deletion grant',async role=>{state.auth.role=role;state.auth.overrides={'organization.delete':true};expect((await POST(req({confirmName:'Acme'}))).status).toBe(403);expect(state.rpc).not.toHaveBeenCalled();});
it('honors owner explicit deny and refuses missing exact-name input',async()=>{state.auth.overrides={'organization.delete':false};expect((await POST(req({confirmName:'Acme'}))).status).toBe(403);state.auth.overrides={};expect((await POST(req())).status).toBe(400);});
it('passes verified typed identity and stores only receipt hash',async()=>{const res=await POST(req({confirmName:'Acme',orgId:'foreign'}));const data=await res.json();expect(res.status).toBe(202);expect(data.receiptToken).toMatch(/^[a-f0-9]{64}$/);const args=state.rpc.mock.calls[0][1];expect(args).toMatchObject({p_org:'org',p_actor:'owner',p_type:'admin',p_auth:'auth',p_name:'Acme'});expect(args.p_receipt_hash).not.toBe(data.receiptToken);expect(state.process).not.toHaveBeenCalled();});
it('supports a read-only receipt after Auth deletion without returning internal lease data',async()=>{state.auth=null;state.rpc.mockResolvedValue({data:{id:'job',status:'completed',organizationName:'Acme'}});const res=await GET(req({},'?receipt='+'a'.repeat(64)));expect(res.status).toBe(200);expect((await res.json()).canDelete).toBe(false);expect((await PATCH(req({},'?receipt='+'a'.repeat(64)))).status).toBe(401);});
it('does not disclose status for invalid receipts',async()=>{expect((await GET(req({},'?receipt=wrong'))).status).toBe(404);expect(state.rpc).not.toHaveBeenCalled();});
it('allows authenticated owner retry only for their recorded job',async()=>{expect((await PATCH(req())).status).toBe(404);state.rpc.mockResolvedValue({data:{id:'job',organizationName:'Acme'}});expect((await PATCH(req())).status).toBe(200);expect(state.process).toHaveBeenCalledWith(expect.anything(),{orgId:'org',retry:true});});
it('sanitizes failed start without losing a recorded job or invoking providers',async()=>{state.rpc.mockResolvedValue({error:{code:'XX000',message:'private details'}});const res=await POST(req({confirmName:'Acme'}));expect(res.status).toBe(503);expect(JSON.stringify(await res.json())).not.toContain('private details');expect(state.process).not.toHaveBeenCalled();});
it('explains pending provisioning without starting destructive cleanup',async()=>{
  state.rpc.mockResolvedValue({error:{code:'55000',message:'PROVISIONING_PENDING: internal details'}});
  const res=await POST(req({confirmName:'Acme'}));
  expect(res.status).toBe(409);
  expect(await res.json()).toMatchObject({code:'provisioning_pending',error:expect.stringContaining('original details')});
  expect(state.process).not.toHaveBeenCalled();
  expect(state.rpc).toHaveBeenCalledTimes(1);
});
