import { expect, it } from 'vitest';
import { signalReportingVisibility, filterForViewer } from '../src/utils/signals';
const lead={user_id:'lead',user_type:'developer',email:'lead@example.test',status:'active'};
const report={user_id:'report',user_type:'developer',email:'report@example.test',status:'active',reports_to:'lead'};
it('grants typed manager only its unambiguous reports under both subject aliases',()=>{const result=signalReportingVisibility([lead,report],{appUserId:'lead',userType:'developer'});expect([...result.visiblePeople]).toEqual(['report','report@example.test']);expect(result.reportsTo).toEqual({report:'lead','report@example.test':'lead'});expect(signalReportingVisibility([lead,report],{appUserId:'lead',userType:'admin'}).visiblePeople.size).toBe(0);});
it('blocks legacy manager UUID collision even when the other profile is suspended',()=>{const collision={...lead,user_type:'admin',email:'other@example.test',status:'suspended'};for(const userType of ['admin','developer']){const result=signalReportingVisibility([lead,collision,report],{appUserId:'lead',userType});expect(result.visiblePeople.size).toBe(0);expect(result.reportsTo).toEqual({});}});
it('supports uniquely addressed manager email without passing ambiguous UUID to cron',()=>{const collision={...lead,user_type:'admin',email:'other@example.test'};const result=signalReportingVisibility([lead,collision,{...report,reports_to:'lead@example.test'}],{appUserId:'lead',userType:'developer'});expect(result.visiblePeople.has('report')).toBe(true);expect(result.reportsTo.report).toBe('lead@example.test');});
it('omits ambiguous email subjects and inactive reports',()=>{const collision={...report,user_id:'another',user_type:'admin'};const result=signalReportingVisibility([lead,report,collision],{appUserId:'lead',userType:'developer'});expect(result.visiblePeople.has('report@example.test')).toBe(false);expect(result.visiblePeople.has('report')).toBe(true);expect(signalReportingVisibility([lead,{...report,status:'suspended'}],{appUserId:'lead',userType:'developer'}).visiblePeople.size).toBe(0);});
it('honors effective signal grant without widening all-person or billing visibility',()=>{const rows=[{kind:'risk',subject:{type:'project',id:'p'}},{kind:'activity_drop',subject:{type:'person',id:'report'}},{kind:'activity_drop',subject:{type:'person',id:'other'}},{kind:'plan_pressure',subject:{type:'organization',id:'org'}}];expect(filterForViewer(rows,{role:'developer',canView:true,visiblePeople:new Set(['report'])})).toEqual(rows.slice(0,2));expect(filterForViewer(rows,{role:'owner',canView:false})).toEqual([]);});
