alter table public.projects add column if not exists workspace_id uuid, add column if not exists manager_id uuid, add column if not exists priority text default 'medium', add column if not exists start_date date, add column if not exists end_date date, add column if not exists budget numeric(14,2), add column if not exists tags text[] default '{}', add column if not exists archived boolean default false, add column if not exists is_template boolean default false;
alter table public.developer_tasks add column if not exists parent_task_id uuid, add column if not exists sprint_id uuid, add column if not exists epic_id uuid, add column if not exists priority text default 'medium', add column if not exists story_points integer, add column if not exists estimated_hours numeric(8,2), add column if not exists actual_hours numeric(8,2), add column if not exists due_date date, add column if not exists tags text[] default '{}', add column if not exists labels text[] default '{}', add column if not exists custom_fields jsonb default '{}'::jsonb, add column if not exists position numeric, add column if not exists is_recurring boolean default false, add column if not exists recurrence jsonb default '{}'::jsonb;
create table if not exists public.workspaces (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, description text, color text, icon text, created_by uuid, created_at timestamptz default now());
create table if not exists public.sprints (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, name text not null, goal text, status text default 'planned' check (status in ('planned','active','completed')), start_date date, end_date date, sort_order integer default 0, created_by uuid, created_at timestamptz default now());
create table if not exists public.epics (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, name text not null, description text, color text, status text default 'open' check (status in ('open','in_progress','done')), created_by uuid, created_at timestamptz default now());
create table if not exists public.task_dependencies (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_id uuid not null references public.developer_tasks(id) on delete cascade, depends_on_task_id uuid not null references public.developer_tasks(id) on delete cascade, type text default 'blocks' check (type in ('blocks','blocked_by','relates_to')), created_at timestamptz default now(), unique (task_id, depends_on_task_id, type));
create table if not exists public.task_checklists (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_id uuid not null references public.developer_tasks(id) on delete cascade, text text not null, done boolean default false, sort_order integer default 0, created_at timestamptz default now());
create table if not exists public.task_comments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_id uuid not null references public.developer_tasks(id) on delete cascade, author_id uuid, author_type text, author_name text, body text not null, mentions uuid[] default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.task_watchers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_id uuid not null references public.developer_tasks(id) on delete cascade, user_id uuid not null, user_type text, role text default 'watcher', created_at timestamptz default now(), unique (task_id, user_id, role));
create table if not exists public.task_attachments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_id uuid not null references public.developer_tasks(id) on delete cascade, file_name text, file_path text, file_type text, file_size bigint, uploaded_by uuid, created_at timestamptz default now());
create table if not exists public.project_labels (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, name text not null, color text default '#6C82FF', created_at timestamptz default now());
create table if not exists public.project_custom_fields (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, name text not null, field_type text default 'text' check (field_type in ('text','number','date','select','checkbox','user')), options jsonb default '[]'::jsonb, sort_order integer default 0, created_at timestamptz default now());
create table if not exists public.automation_rules (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, name text not null, enabled boolean default true, trigger jsonb not null default '{}'::jsonb, actions jsonb not null default '[]'::jsonb, created_by uuid, created_at timestamptz default now());
create table if not exists public.saved_views (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete cascade, user_id uuid, name text not null, view_type text default 'board' check (view_type in ('board','list','table','calendar','timeline','gantt','workload')), config jsonb default '{}'::jsonb, is_shared boolean default false, created_at timestamptz default now());
create table if not exists public.session_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, session_id text, task_id uuid references public.developer_tasks(id) on delete set null, developer_id uuid, started_at timestamptz default now(), ended_at timestamptz, created_at timestamptz default now());
create index if not exists idx_session_tasks_session on public.session_tasks(session_id);
create index if not exists idx_session_tasks_task on public.session_tasks(task_id);
create index if not exists idx_sprints_project on public.sprints(project_id);
create index if not exists idx_epics_project on public.epics(project_id);
create index if not exists idx_dev_tasks_parent on public.developer_tasks(parent_task_id);
create index if not exists idx_dev_tasks_sprint on public.developer_tasks(sprint_id);
alter table public.developer_tasks add column if not exists task_type text default 'feature';
alter table public.developer_tasks drop constraint if exists developer_tasks_task_type_check;
alter table public.developer_tasks add constraint developer_tasks_task_type_check check (task_type in ('feature','bug','improvement','research','documentation','story'));
create table if not exists public.pm_activity (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid, entity_type text not null, entity_id uuid, action text not null, actor_id uuid, actor_name text, meta jsonb default '{}'::jsonb, created_at timestamptz default now());
create index if not exists idx_pm_activity_project on public.pm_activity(project_id);
create index if not exists idx_pm_activity_entity on public.pm_activity(entity_type, entity_id);
create index if not exists idx_pm_activity_created on public.pm_activity(created_at desc);
create table if not exists public.task_time_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, task_id uuid references public.developer_tasks(id) on delete cascade, project_id uuid, developer_id uuid, started_at timestamptz not null default now(), ended_at timestamptz, seconds integer, source text default 'web_timer', note text, created_at timestamptz default now());
create index if not exists idx_time_logs_task on public.task_time_logs(task_id);
create index if not exists idx_time_logs_dev on public.task_time_logs(developer_id);
create index if not exists idx_time_logs_proj on public.task_time_logs(project_id);
alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.workspaces enable row level security;
drop trigger if exists trg_stamp_org on public.workspaces;
create trigger trg_stamp_org before insert on public.workspaces for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.workspaces;
create policy org_isolation on public.workspaces for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.sprints enable row level security;
drop trigger if exists trg_stamp_org on public.sprints;
create trigger trg_stamp_org before insert on public.sprints for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.sprints;
create policy org_isolation on public.sprints for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.epics enable row level security;
drop trigger if exists trg_stamp_org on public.epics;
create trigger trg_stamp_org before insert on public.epics for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.epics;
create policy org_isolation on public.epics for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.task_dependencies enable row level security;
drop trigger if exists trg_stamp_org on public.task_dependencies;
create trigger trg_stamp_org before insert on public.task_dependencies for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.task_dependencies;
create policy org_isolation on public.task_dependencies for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.task_checklists enable row level security;
drop trigger if exists trg_stamp_org on public.task_checklists;
create trigger trg_stamp_org before insert on public.task_checklists for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.task_checklists;
create policy org_isolation on public.task_checklists for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.task_comments enable row level security;
drop trigger if exists trg_stamp_org on public.task_comments;
create trigger trg_stamp_org before insert on public.task_comments for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.task_comments;
create policy org_isolation on public.task_comments for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.task_watchers enable row level security;
drop trigger if exists trg_stamp_org on public.task_watchers;
create trigger trg_stamp_org before insert on public.task_watchers for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.task_watchers;
create policy org_isolation on public.task_watchers for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.task_attachments enable row level security;
drop trigger if exists trg_stamp_org on public.task_attachments;
create trigger trg_stamp_org before insert on public.task_attachments for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.task_attachments;
create policy org_isolation on public.task_attachments for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.project_labels enable row level security;
drop trigger if exists trg_stamp_org on public.project_labels;
create trigger trg_stamp_org before insert on public.project_labels for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.project_labels;
create policy org_isolation on public.project_labels for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.project_custom_fields enable row level security;
drop trigger if exists trg_stamp_org on public.project_custom_fields;
create trigger trg_stamp_org before insert on public.project_custom_fields for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.project_custom_fields;
create policy org_isolation on public.project_custom_fields for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.automation_rules enable row level security;
drop trigger if exists trg_stamp_org on public.automation_rules;
create trigger trg_stamp_org before insert on public.automation_rules for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.automation_rules;
create policy org_isolation on public.automation_rules for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.saved_views enable row level security;
drop trigger if exists trg_stamp_org on public.saved_views;
create trigger trg_stamp_org before insert on public.saved_views for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.saved_views;
create policy org_isolation on public.saved_views for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.session_tasks enable row level security;
drop trigger if exists trg_stamp_org on public.session_tasks;
create trigger trg_stamp_org before insert on public.session_tasks for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.session_tasks;
create policy org_isolation on public.session_tasks for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.pm_activity enable row level security;
drop trigger if exists trg_stamp_org on public.pm_activity;
create trigger trg_stamp_org before insert on public.pm_activity for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.pm_activity;
create policy org_isolation on public.pm_activity for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
alter table public.task_time_logs enable row level security;
drop trigger if exists trg_stamp_org on public.task_time_logs;
create trigger trg_stamp_org before insert on public.task_time_logs for each row execute function public.stamp_org();
drop policy if exists org_isolation on public.task_time_logs;
create policy org_isolation on public.task_time_logs for all to authenticated using (organization_id = public.auth_org() and not public.auth_is_client()) with check (organization_id = public.auth_org() and not public.auth_is_client());
