-- =====================================================================
--  056 - email_verifications: make the signup code mean something
-- =====================================================================
--
--  WHAT IS WRONG TODAY
--
--  The verification code on the create-organization flow is generated by the
--  BROWSER, held in React state, and compared by the BROWSER:
--
--    src/app/admin/registration/page.js:586   Math.random() -> nextCode
--    src/app/admin/registration/page.js:708   if (code !== generatedCode) ...
--
--  /api/send-verification is handed that number and relays it into an email.
--  Nothing on the server issues the code, stores it, or knows when it was
--  issued — which /api/send-verification already says about itself in its own
--  header comment.
--
--  So the check is theatre. Three ways past it, none of them clever:
--
--    * POST straight to /api/auth/signup and never touch the code at all
--    * read `generatedCode` out of React state in devtools
--    * edit the comparison in the browser
--
--  The email states a ten-minute expiry that nothing can enforce, because the
--  only copy of the code lives in the tab that made it up.
--
--  WHAT THIS TABLE DOES
--
--  Moves the code to where it can be checked. The server mints it, stores a
--  HASH of it with an expiry, and /api/auth/signup refuses an address that has
--  not completed verification recently.
--
--  The code is hashed, not stored. It is a 4-8 digit number, so the hash is not
--  much of a secret against anyone who can read the table — but nobody can:
--  the RLS policy below admits no browser role at all, so only the service key
--  ever sees these rows. Hashing means a leaked backup does not hand out live
--  codes, which is worth the two lines it costs.
--
--  RUN PART 1, then PART 2, then PART 3 (verification, changes nothing).
--
-- =====================================================================


-- ---------------------------------------------------------------------
--  PART 1 - The table
-- ---------------------------------------------------------------------

create table if not exists public.email_verifications (
  id            uuid primary key default gen_random_uuid(),
  -- Normalised (lower(btrim(...))) by the route before it is written, so a
  -- lookup never has to guess at casing or stray whitespace.
  email         text        not null,
  code_hash     text        not null,
  expires_at    timestamptz not null,
  -- When the correct code was presented. NULL means "issued, not yet proven".
  verified_at   timestamptz,
  -- When a signup actually consumed the verification, so one verified code
  -- cannot create two organizations.
  consumed_at   timestamptz,
  -- Wrong guesses against THIS row. The verify route refuses past a small
  -- number, which is what stops a 4-digit code being walked in 10000 tries.
  attempts      smallint    not null default 0,
  ip            text,
  created_at    timestamptz not null default now()
);

-- The verify and signup routes both look up "the newest live row for this
-- address", so that is the index.
create index if not exists idx_email_verifications_email_created
  on public.email_verifications (email, created_at desc);

-- Housekeeping: expired, unconsumed rows are of no further use.
create index if not exists idx_email_verifications_expires
  on public.email_verifications (expires_at)
  where consumed_at is null;


-- ---------------------------------------------------------------------
--  PART 2 - Row Level Security: service role only
-- ---------------------------------------------------------------------
--
--  RLS is enabled and NO policy is created. That is deliberate and it is the
--  whole security model of this table:
--
--    * with RLS on and no policy, every ordinary role — `anon` and
--      `authenticated` alike — is refused every row, for every command.
--    * the service role bypasses RLS entirely, so the three server routes that
--      need this table keep working.
--
--  This table is only ever touched from the server. A browser must never be
--  able to read a code, list addresses that have signed up, or mark itself
--  verified — and the way to guarantee that is to grant nothing, rather than
--  to write a policy that tries to describe what a browser may do.
--
--  (Contrast with migration 054's storage work: there the mistake was a policy
--  that said `true`. Here the correct policy count is zero.)

alter table public.email_verifications enable row level security;

-- Belt and braces: even the table-level grants are withdrawn, so a future
-- permissive policy added by mistake still has nothing to act on.
revoke all on public.email_verifications from anon, authenticated;


-- ---------------------------------------------------------------------
--  PART 3 - Verification. Changes nothing.
-- ---------------------------------------------------------------------

--  3a. Expect rls_enabled = t.
select relrowsecurity as rls_enabled
from pg_class where oid = 'public.email_verifications'::regclass;

--  3b. Expect 0 rows. Any policy here weakens the model described above.
select policyname, cmd, roles::text
from pg_policies
where schemaname = 'public' and tablename = 'email_verifications';

--  3c. Expect 0 rows: neither browser role may hold any privilege.
select grantee, privilege_type
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'email_verifications'
  and grantee in ('anon', 'authenticated');
