-- ============================================================================
--  093 - role_permissions: the contract keys
--
--  WHAT CHANGED
--
--  Migration 092 added client contracts, milestones and amendments. Three keys,
--  and they narrow:
--
--    contract.view      owner, admin, manager, finance
--    contract.manage    owner, admin, finance
--    contract.amend     owner, admin
--
--  A MANAGER READS AND DOES NOT WRITE. Delivering against a contract means
--  knowing what it says -- the scope, the dates, the milestones. Committing the
--  company to a number is a different act and belongs with the people who
--  answer for the money.
--
--  AMENDING IS NARROWER STILL. Changing the terms of something already signed
--  is the most consequential edit in this schema, because it changes what both
--  sides are recorded as having agreed. The contract_amendments log is what
--  makes it safe rather than forbidden: the previous value is kept, so a change
--  is a fact rather than a disappearance.
--
--  THIS IS THE LAST OF THE TEN MODULES. 102 keys, from 53.
--
--  WHY A FULL RE-SYNC AGAIN: role_permissions is a MIRROR. Nothing reads it at
--  runtime; it exists so the model is inspectable in SQL, and a partly updated
--  mirror is worse than a plainly stale one.
--
--  RUN AFTER 092.
-- ============================================================================

-- PART 1 -- every row the catalogue defines. 452 rows over 102 keys.
insert into public.role_permissions (role, resource, action, allowed) values
  ('admin', 'asset', 'manage', true),
  ('admin', 'asset', 'view', true),
  ('admin', 'attendance', 'log_own', true),
  ('admin', 'attendance', 'manage', true),
  ('admin', 'attendance', 'view_all', true),
  ('admin', 'attendance', 'view_own', true),
  ('admin', 'automation', 'manage', true),
  ('admin', 'billing', 'manage', true),
  ('admin', 'billing', 'view', true),
  ('admin', 'bug', 'triage', true),
  ('admin', 'candidate', 'manage', true),
  ('admin', 'candidate', 'view', true),
  ('admin', 'capacity', 'allocate', true),
  ('admin', 'capacity', 'view', true),
  ('admin', 'change_request', 'approve', true),
  ('admin', 'change_request', 'create', true),
  ('admin', 'change_request', 'decide', true),
  ('admin', 'change_request', 'view', true),
  ('admin', 'client', 'notify', true),
  ('admin', 'client', 'view', true),
  ('admin', 'contract', 'amend', true),
  ('admin', 'contract', 'manage', true),
  ('admin', 'contract', 'view', true),
  ('admin', 'employee', 'activate', true),
  ('admin', 'employee', 'manage', true),
  ('admin', 'employee', 'onboard', true),
  ('admin', 'employee', 'transfer', true),
  ('admin', 'employment', 'set_hours', true),
  ('admin', 'goal', 'manage', true),
  ('admin', 'hierarchy', 'manage', true),
  ('admin', 'hierarchy', 'view', true),
  ('admin', 'invoice', 'manage', true),
  ('admin', 'invoice', 'view', true),
  ('admin', 'job', 'manage', true),
  ('admin', 'job', 'view', true),
  ('admin', 'leave', 'approve', true),
  ('admin', 'leave', 'manage_types', true),
  ('admin', 'leave', 'request_own', true),
  ('admin', 'leave', 'view_all', true),
  ('admin', 'leave', 'view_own', true),
  ('admin', 'licence', 'manage', true),
  ('admin', 'licence', 'view', true),
  ('admin', 'member', 'create', true),
  ('admin', 'member', 'delete', true),
  ('admin', 'member', 'invite', true),
  ('admin', 'member', 'manage', true),
  ('admin', 'member', 'provision', true),
  ('admin', 'member', 'sync_roles', true),
  ('admin', 'member', 'view', true),
  ('admin', 'monitoring', 'view', true),
  ('admin', 'monitoring', 'view_own', true),
  ('admin', 'organization', 'view', true),
  ('admin', 'pnl', 'view', true),
  ('admin', 'productivity', 'recalculate', true),
  ('admin', 'productivity', 'view_own', true),
  ('admin', 'profile', 'manage_own', true),
  ('admin', 'project', 'assign_manager', true),
  ('admin', 'project', 'board', true),
  ('admin', 'project', 'close', true),
  ('admin', 'project', 'complete', true),
  ('admin', 'project', 'create', true),
  ('admin', 'project', 'delete', true),
  ('admin', 'project', 'hub', true),
  ('admin', 'project', 'manage_members', true),
  ('admin', 'project', 'view_all', true),
  ('admin', 'project', 'view_own', true),
  ('admin', 'proposal', 'decide', true),
  ('admin', 'proposal', 'view', true),
  ('admin', 'report', 'view', true),
  ('admin', 'review', 'view_all', true),
  ('admin', 'review', 'view_own', true),
  ('admin', 'review', 'write', true),
  ('admin', 'review_cycle', 'manage', true),
  ('admin', 'signal', 'view', true),
  ('admin', 'sprint', 'view', true),
  ('admin', 'system', 'audit', true),
  ('admin', 'system', 'health', true),
  ('admin', 'task', 'manage', true),
  ('admin', 'task', 'review', true),
  ('admin', 'task', 'set_client_visibility', true),
  ('admin', 'task', 'update_own', true),
  ('admin', 'task', 'view_all', true),
  ('admin', 'task', 'view_own', true),
  ('admin', 'team', 'manage', true),
  ('admin', 'team', 'view', true),
  ('admin', 'team', 'view_own', true),
  ('admin', 'team_stats', 'view', true),
  ('admin', 'test_case', 'manage', true),
  ('admin', 'test_case', 'view', true),
  ('admin', 'test_run', 'execute', true),
  ('admin', 'test_run', 'manage', true),
  ('admin', 'timesheet', 'approve', true),
  ('admin', 'timesheet', 'log_own', true),
  ('admin', 'timesheet', 'submit_own', true),
  ('admin', 'timesheet', 'view_all', true),
  ('admin', 'timesheet', 'view_own', true),
  ('designer', 'attendance', 'log_own', true),
  ('designer', 'attendance', 'view_own', true),
  ('designer', 'leave', 'request_own', true),
  ('designer', 'leave', 'view_own', true),
  ('designer', 'monitoring', 'view_own', true),
  ('designer', 'productivity', 'view_own', true),
  ('designer', 'profile', 'manage_own', true),
  ('designer', 'project', 'view_own', true),
  ('designer', 'review', 'view_own', true),
  ('designer', 'task', 'submit', true),
  ('designer', 'task', 'update_own', true),
  ('designer', 'task', 'view_own', true),
  ('designer', 'team', 'view_own', true),
  ('designer', 'timesheet', 'log_own', true),
  ('designer', 'timesheet', 'submit_own', true),
  ('designer', 'timesheet', 'view_own', true),
  ('developer', 'attendance', 'log_own', true),
  ('developer', 'attendance', 'view_own', true),
  ('developer', 'leave', 'request_own', true),
  ('developer', 'leave', 'view_own', true),
  ('developer', 'monitoring', 'view_own', true),
  ('developer', 'productivity', 'view_own', true),
  ('developer', 'profile', 'manage_own', true),
  ('developer', 'project', 'view_own', true),
  ('developer', 'review', 'view_own', true),
  ('developer', 'task', 'submit', true),
  ('developer', 'task', 'update_own', true),
  ('developer', 'task', 'view_own', true),
  ('developer', 'team', 'view_own', true),
  ('developer', 'timesheet', 'log_own', true),
  ('developer', 'timesheet', 'submit_own', true),
  ('developer', 'timesheet', 'view_own', true),
  ('devops', 'attendance', 'log_own', true),
  ('devops', 'attendance', 'view_own', true),
  ('devops', 'leave', 'request_own', true),
  ('devops', 'leave', 'view_own', true),
  ('devops', 'monitoring', 'view_own', true),
  ('devops', 'productivity', 'view_own', true),
  ('devops', 'profile', 'manage_own', true),
  ('devops', 'project', 'view_own', true),
  ('devops', 'review', 'view_own', true),
  ('devops', 'task', 'submit', true),
  ('devops', 'task', 'update_own', true),
  ('devops', 'task', 'view_own', true),
  ('devops', 'team', 'view_own', true),
  ('devops', 'timesheet', 'log_own', true),
  ('devops', 'timesheet', 'submit_own', true),
  ('devops', 'timesheet', 'view_own', true),
  ('employee', 'attendance', 'log_own', true),
  ('employee', 'attendance', 'view_own', true),
  ('employee', 'leave', 'request_own', true),
  ('employee', 'leave', 'view_own', true),
  ('employee', 'monitoring', 'view_own', true),
  ('employee', 'productivity', 'view_own', true),
  ('employee', 'profile', 'manage_own', true),
  ('employee', 'project', 'view_own', true),
  ('employee', 'review', 'view_own', true),
  ('employee', 'task', 'submit', true),
  ('employee', 'task', 'update_own', true),
  ('employee', 'task', 'view_own', true),
  ('employee', 'team', 'view_own', true),
  ('employee', 'timesheet', 'log_own', true),
  ('employee', 'timesheet', 'submit_own', true),
  ('employee', 'timesheet', 'view_own', true),
  ('finance', 'asset', 'view', true),
  ('finance', 'attendance', 'log_own', true),
  ('finance', 'attendance', 'view_own', true),
  ('finance', 'billing', 'manage', true),
  ('finance', 'billing', 'view', true),
  ('finance', 'client', 'view', true),
  ('finance', 'contract', 'manage', true),
  ('finance', 'contract', 'view', true),
  ('finance', 'invoice', 'manage', true),
  ('finance', 'invoice', 'view', true),
  ('finance', 'leave', 'request_own', true),
  ('finance', 'leave', 'view_own', true),
  ('finance', 'licence', 'manage', true),
  ('finance', 'licence', 'view', true),
  ('finance', 'monitoring', 'view_own', true),
  ('finance', 'pnl', 'view', true),
  ('finance', 'productivity', 'view_own', true),
  ('finance', 'profile', 'manage_own', true),
  ('finance', 'project', 'view_own', true),
  ('finance', 'review', 'view_own', true),
  ('finance', 'task', 'update_own', true),
  ('finance', 'task', 'view_own', true),
  ('finance', 'team', 'view_own', true),
  ('finance', 'timesheet', 'log_own', true),
  ('finance', 'timesheet', 'submit_own', true),
  ('finance', 'timesheet', 'view_all', true),
  ('finance', 'timesheet', 'view_own', true),
  ('hr', 'asset', 'manage', true),
  ('hr', 'asset', 'view', true),
  ('hr', 'attendance', 'log_own', true),
  ('hr', 'attendance', 'manage', true),
  ('hr', 'attendance', 'view_all', true),
  ('hr', 'attendance', 'view_own', true),
  ('hr', 'candidate', 'manage', true),
  ('hr', 'candidate', 'view', true),
  ('hr', 'capacity', 'view', true),
  ('hr', 'employee', 'activate', true),
  ('hr', 'employee', 'manage', true),
  ('hr', 'employee', 'onboard', true),
  ('hr', 'employee', 'transfer', true),
  ('hr', 'employment', 'set_hours', true),
  ('hr', 'goal', 'manage', true),
  ('hr', 'hierarchy', 'manage', true),
  ('hr', 'hierarchy', 'view', true),
  ('hr', 'job', 'manage', true),
  ('hr', 'job', 'view', true),
  ('hr', 'leave', 'approve', true),
  ('hr', 'leave', 'manage_types', true),
  ('hr', 'leave', 'request_own', true),
  ('hr', 'leave', 'view_all', true),
  ('hr', 'leave', 'view_own', true),
  ('hr', 'licence', 'view', true),
  ('hr', 'member', 'create', true),
  ('hr', 'member', 'invite', true),
  ('hr', 'member', 'manage', true),
  ('hr', 'member', 'provision', true),
  ('hr', 'member', 'view', true),
  ('hr', 'monitoring', 'view_own', true),
  ('hr', 'organization', 'view', true),
  ('hr', 'productivity', 'view_own', true),
  ('hr', 'profile', 'manage_own', true),
  ('hr', 'project', 'view_own', true),
  ('hr', 'review', 'view_all', true),
  ('hr', 'review', 'view_own', true),
  ('hr', 'review', 'write', true),
  ('hr', 'review_cycle', 'manage', true),
  ('hr', 'signal', 'view', true),
  ('hr', 'task', 'update_own', true),
  ('hr', 'task', 'view_own', true),
  ('hr', 'team', 'manage', true),
  ('hr', 'team', 'view_own', true),
  ('hr', 'team_stats', 'view', true),
  ('hr', 'timesheet', 'log_own', true),
  ('hr', 'timesheet', 'submit_own', true),
  ('hr', 'timesheet', 'view_own', true),
  ('manager', 'attendance', 'log_own', true),
  ('manager', 'attendance', 'view_all', true),
  ('manager', 'attendance', 'view_own', true),
  ('manager', 'bug', 'triage', true),
  ('manager', 'capacity', 'allocate', true),
  ('manager', 'capacity', 'view', true),
  ('manager', 'change_request', 'create', true),
  ('manager', 'change_request', 'decide', true),
  ('manager', 'change_request', 'view', true),
  ('manager', 'client', 'notify', true),
  ('manager', 'contract', 'view', true),
  ('manager', 'goal', 'manage', true),
  ('manager', 'hierarchy', 'view', true),
  ('manager', 'job', 'view', true),
  ('manager', 'leave', 'approve', true),
  ('manager', 'leave', 'request_own', true),
  ('manager', 'leave', 'view_all', true),
  ('manager', 'leave', 'view_own', true),
  ('manager', 'member', 'invite', true),
  ('manager', 'member', 'provision', true),
  ('manager', 'monitoring', 'view_own', true),
  ('manager', 'productivity', 'view_own', true),
  ('manager', 'profile', 'manage_own', true),
  ('manager', 'project', 'complete', true),
  ('manager', 'project', 'create', true),
  ('manager', 'project', 'hub', true),
  ('manager', 'project', 'manage_members', true),
  ('manager', 'project', 'view_all', true),
  ('manager', 'project', 'view_own', true),
  ('manager', 'proposal', 'decide', true),
  ('manager', 'proposal', 'view', true),
  ('manager', 'report', 'view', true),
  ('manager', 'review', 'view_own', true),
  ('manager', 'review', 'write', true),
  ('manager', 'signal', 'view', true),
  ('manager', 'sprint', 'view', true),
  ('manager', 'task', 'manage', true),
  ('manager', 'task', 'review', true),
  ('manager', 'task', 'set_client_visibility', true),
  ('manager', 'task', 'update_own', true),
  ('manager', 'task', 'view_all', true),
  ('manager', 'task', 'view_own', true),
  ('manager', 'team', 'view', true),
  ('manager', 'team', 'view_own', true),
  ('manager', 'test_case', 'manage', true),
  ('manager', 'test_case', 'view', true),
  ('manager', 'test_run', 'execute', true),
  ('manager', 'test_run', 'manage', true),
  ('manager', 'timesheet', 'approve', true),
  ('manager', 'timesheet', 'log_own', true),
  ('manager', 'timesheet', 'submit_own', true),
  ('manager', 'timesheet', 'view_all', true),
  ('manager', 'timesheet', 'view_own', true),
  ('owner', 'asset', 'manage', true),
  ('owner', 'asset', 'view', true),
  ('owner', 'attendance', 'log_own', true),
  ('owner', 'attendance', 'manage', true),
  ('owner', 'attendance', 'view_all', true),
  ('owner', 'attendance', 'view_own', true),
  ('owner', 'automation', 'manage', true),
  ('owner', 'billing', 'manage', true),
  ('owner', 'billing', 'purchase', true),
  ('owner', 'billing', 'view', true),
  ('owner', 'bug', 'triage', true),
  ('owner', 'candidate', 'manage', true),
  ('owner', 'candidate', 'view', true),
  ('owner', 'capacity', 'allocate', true),
  ('owner', 'capacity', 'view', true),
  ('owner', 'change_request', 'approve', true),
  ('owner', 'change_request', 'create', true),
  ('owner', 'change_request', 'decide', true),
  ('owner', 'change_request', 'view', true),
  ('owner', 'client', 'notify', true),
  ('owner', 'client', 'view', true),
  ('owner', 'contract', 'amend', true),
  ('owner', 'contract', 'manage', true),
  ('owner', 'contract', 'view', true),
  ('owner', 'employee', 'activate', true),
  ('owner', 'employee', 'manage', true),
  ('owner', 'employee', 'onboard', true),
  ('owner', 'employee', 'transfer', true),
  ('owner', 'employment', 'set_hours', true),
  ('owner', 'goal', 'manage', true),
  ('owner', 'hierarchy', 'manage', true),
  ('owner', 'hierarchy', 'view', true),
  ('owner', 'invoice', 'manage', true),
  ('owner', 'invoice', 'view', true),
  ('owner', 'job', 'manage', true),
  ('owner', 'job', 'view', true),
  ('owner', 'leave', 'approve', true),
  ('owner', 'leave', 'manage_types', true),
  ('owner', 'leave', 'request_own', true),
  ('owner', 'leave', 'view_all', true),
  ('owner', 'leave', 'view_own', true),
  ('owner', 'licence', 'manage', true),
  ('owner', 'licence', 'view', true),
  ('owner', 'member', 'create', true),
  ('owner', 'member', 'delete', true),
  ('owner', 'member', 'invite', true),
  ('owner', 'member', 'manage', true),
  ('owner', 'member', 'provision', true),
  ('owner', 'member', 'sync_roles', true),
  ('owner', 'member', 'view', true),
  ('owner', 'monitoring', 'view', true),
  ('owner', 'monitoring', 'view_own', true),
  ('owner', 'organization', 'delete', true),
  ('owner', 'organization', 'manage', true),
  ('owner', 'organization', 'settings', true),
  ('owner', 'organization', 'view', true),
  ('owner', 'permissions', 'manage', true),
  ('owner', 'pnl', 'view', true),
  ('owner', 'productivity', 'recalculate', true),
  ('owner', 'productivity', 'view_own', true),
  ('owner', 'profile', 'manage_own', true),
  ('owner', 'project', 'assign_manager', true),
  ('owner', 'project', 'board', true),
  ('owner', 'project', 'close', true),
  ('owner', 'project', 'complete', true),
  ('owner', 'project', 'create', true),
  ('owner', 'project', 'delete', true),
  ('owner', 'project', 'hub', true),
  ('owner', 'project', 'manage_members', true),
  ('owner', 'project', 'view_all', true),
  ('owner', 'project', 'view_own', true),
  ('owner', 'proposal', 'decide', true),
  ('owner', 'proposal', 'view', true),
  ('owner', 'report', 'view', true),
  ('owner', 'review', 'view_all', true),
  ('owner', 'review', 'view_own', true),
  ('owner', 'review', 'write', true),
  ('owner', 'review_cycle', 'manage', true),
  ('owner', 'signal', 'view', true),
  ('owner', 'sprint', 'view', true),
  ('owner', 'system', 'audit', true),
  ('owner', 'system', 'health', true),
  ('owner', 'task', 'manage', true),
  ('owner', 'task', 'review', true),
  ('owner', 'task', 'set_client_visibility', true),
  ('owner', 'task', 'update_own', true),
  ('owner', 'task', 'view_all', true),
  ('owner', 'task', 'view_own', true),
  ('owner', 'team', 'manage', true),
  ('owner', 'team', 'view', true),
  ('owner', 'team', 'view_own', true),
  ('owner', 'team_stats', 'view', true),
  ('owner', 'test_case', 'manage', true),
  ('owner', 'test_case', 'view', true),
  ('owner', 'test_run', 'execute', true),
  ('owner', 'test_run', 'manage', true),
  ('owner', 'timesheet', 'approve', true),
  ('owner', 'timesheet', 'log_own', true),
  ('owner', 'timesheet', 'submit_own', true),
  ('owner', 'timesheet', 'view_all', true),
  ('owner', 'timesheet', 'view_own', true),
  ('qa', 'attendance', 'log_own', true),
  ('qa', 'attendance', 'view_own', true),
  ('qa', 'bug', 'triage', true),
  ('qa', 'leave', 'request_own', true),
  ('qa', 'leave', 'view_own', true),
  ('qa', 'monitoring', 'view_own', true),
  ('qa', 'productivity', 'view_own', true),
  ('qa', 'profile', 'manage_own', true),
  ('qa', 'project', 'view_own', true),
  ('qa', 'review', 'view_own', true),
  ('qa', 'task', 'review', true),
  ('qa', 'task', 'submit', true),
  ('qa', 'task', 'update_own', true),
  ('qa', 'task', 'view_own', true),
  ('qa', 'team', 'view_own', true),
  ('qa', 'test_case', 'manage', true),
  ('qa', 'test_case', 'view', true),
  ('qa', 'test_run', 'execute', true),
  ('qa', 'test_run', 'manage', true),
  ('qa', 'timesheet', 'log_own', true),
  ('qa', 'timesheet', 'submit_own', true),
  ('qa', 'timesheet', 'view_own', true),
  ('team_lead', 'attendance', 'log_own', true),
  ('team_lead', 'attendance', 'view_own', true),
  ('team_lead', 'bug', 'triage', true),
  ('team_lead', 'capacity', 'view', true),
  ('team_lead', 'change_request', 'view', true),
  ('team_lead', 'goal', 'manage', true),
  ('team_lead', 'hierarchy', 'view', true),
  ('team_lead', 'job', 'view', true),
  ('team_lead', 'leave', 'request_own', true),
  ('team_lead', 'leave', 'view_own', true),
  ('team_lead', 'monitoring', 'view_own', true),
  ('team_lead', 'productivity', 'view_own', true),
  ('team_lead', 'profile', 'manage_own', true),
  ('team_lead', 'project', 'complete', true),
  ('team_lead', 'project', 'create', true),
  ('team_lead', 'project', 'hub', true),
  ('team_lead', 'project', 'view_all', true),
  ('team_lead', 'project', 'view_own', true),
  ('team_lead', 'proposal', 'view', true),
  ('team_lead', 'report', 'view', true),
  ('team_lead', 'review', 'view_own', true),
  ('team_lead', 'review', 'write', true),
  ('team_lead', 'signal', 'view', true),
  ('team_lead', 'sprint', 'view', true),
  ('team_lead', 'task', 'manage', true),
  ('team_lead', 'task', 'review', true),
  ('team_lead', 'task', 'submit', true),
  ('team_lead', 'task', 'update_own', true),
  ('team_lead', 'task', 'view_all', true),
  ('team_lead', 'task', 'view_own', true),
  ('team_lead', 'team', 'view', true),
  ('team_lead', 'team', 'view_own', true),
  ('team_lead', 'test_case', 'manage', true),
  ('team_lead', 'test_case', 'view', true),
  ('team_lead', 'test_run', 'execute', true),
  ('team_lead', 'test_run', 'manage', true),
  ('team_lead', 'timesheet', 'approve', true),
  ('team_lead', 'timesheet', 'log_own', true),
  ('team_lead', 'timesheet', 'submit_own', true),
  ('team_lead', 'timesheet', 'view_all', true),
  ('team_lead', 'timesheet', 'view_own', true)
on conflict (role, resource, action) do update set allowed = excluded.allowed;


-- ---------------------------------------------------------------------
--  PART 2 - verify (read-only)
-- ---------------------------------------------------------------------
--  Expect 452 rows over 102 distinct keys.
select count(*) as total_rows,
       count(distinct (resource || '.' || action)) as distinct_keys
  from public.role_permissions
 where allowed;


-- ---------------------------------------------------------------------
--  PART 3 - orphans (read-only)
-- ---------------------------------------------------------------------
--  Any row whose key the catalogue no longer defines. Expect zero. A non-zero
--  answer is not automatically wrong -- it means somebody removed a key and the
--  mirror still remembers it -- but it should be a decision, not a surprise.
select rp.role, rp.resource, rp.action
  from public.role_permissions rp
 where (rp.resource || '.' || rp.action) not in (
    'asset.manage',
    'asset.view',
    'attendance.log_own',
    'attendance.manage',
    'attendance.view_all',
    'attendance.view_own',
    'automation.manage',
    'billing.manage',
    'billing.purchase',
    'billing.view',
    'bug.triage',
    'candidate.manage',
    'candidate.view',
    'capacity.allocate',
    'capacity.view',
    'change_request.approve',
    'change_request.create',
    'change_request.decide',
    'change_request.view',
    'client.notify',
    'client.view',
    'contract.amend',
    'contract.manage',
    'contract.view',
    'employee.activate',
    'employee.manage',
    'employee.onboard',
    'employee.transfer',
    'employment.set_hours',
    'goal.manage',
    'hierarchy.manage',
    'hierarchy.view',
    'invoice.manage',
    'invoice.view',
    'job.manage',
    'job.view',
    'leave.approve',
    'leave.manage_types',
    'leave.request_own',
    'leave.view_all',
    'leave.view_own',
    'licence.manage',
    'licence.view',
    'member.create',
    'member.delete',
    'member.invite',
    'member.manage',
    'member.provision',
    'member.sync_roles',
    'member.view',
    'monitoring.view',
    'monitoring.view_own',
    'organization.delete',
    'organization.manage',
    'organization.settings',
    'organization.view',
    'permissions.manage',
    'pnl.view',
    'productivity.recalculate',
    'productivity.view_own',
    'profile.manage_own',
    'project.assign_manager',
    'project.board',
    'project.close',
    'project.complete',
    'project.create',
    'project.delete',
    'project.hub',
    'project.manage_members',
    'project.view_all',
    'project.view_own',
    'proposal.decide',
    'proposal.view',
    'report.view',
    'review.view_all',
    'review.view_own',
    'review.write',
    'review_cycle.manage',
    'signal.view',
    'sprint.view',
    'system.audit',
    'system.health',
    'task.manage',
    'task.review',
    'task.set_client_visibility',
    'task.submit',
    'task.update_own',
    'task.view_all',
    'task.view_own',
    'team.manage',
    'team.view',
    'team.view_own',
    'team_stats.view',
    'test_case.manage',
    'test_case.view',
    'test_run.execute',
    'test_run.manage',
    'timesheet.approve',
    'timesheet.log_own',
    'timesheet.submit_own',
    'timesheet.view_all',
    'timesheet.view_own'
 )
 order by rp.resource, rp.action, rp.role;
