-- Verisade platform administration suite upgrade.
-- Run ONCE in Supabase SQL Editor before deploying this application's new build.
-- Requires the existing platform-owner console migration and owner provisioning.
-- This adds management capabilities; it does not run deletions, refunds or invitations.
-- Generated by scripts/build-platform-admin-sql.py; edit the source migrations.
begin;
select pg_advisory_xact_lock(hashtextextended('verisade-platform-admin-suite-upgrade',0));
do $$ begin
 if to_regclass('app_private.platform_owners') is null then
  raise exception 'Install the existing platform-owner console setup first';
 end if;
 if to_regclass('app_private.platform_staff') is not null then
  raise exception 'Platform admin suite is already installed; do not rerun this upgrade';
 end if;
end $$;

-- Source: 20260920115119_platform_management_access.sql
create table app_private.platform_staff (
 auth_user_id uuid primary key references auth.users(id) on delete restrict,
 role text not null check(role in ('support','billing')), mfa_required boolean not null default true,
 created_at timestamptz not null default now()
);
alter table app_private.platform_owners add column mfa_required boolean not null default false;
create table app_private.platform_revoked_sessions (session_id uuid primary key, auth_user_id uuid not null, revoked_at timestamptz not null default now());
alter table app_private.platform_staff enable row level security;
alter table app_private.platform_revoked_sessions enable row level security;
revoke all on app_private.platform_staff,app_private.platform_revoked_sessions from public,anon,authenticated,service_role;
create function public.platform_session_active(p_auth uuid,p_session uuid) returns boolean language sql stable security definer set search_path=pg_catalog as $$
 select exists(select 1 from auth.sessions s join auth.users u on u.id=s.user_id where s.id=p_session and s.user_id=p_auth and u.deleted_at is null and (u.banned_until is null or u.banned_until<=now())
 and ((to_jsonb(s)->>'not_after') is null or (to_jsonb(s)->>'not_after')::timestamptz>now())
 and not exists(select 1 from app_private.platform_revoked_sessions r where r.session_id=s.id));
$$;
revoke all on function public.platform_session_active(uuid,uuid) from public,anon,authenticated;
grant execute on function public.platform_session_active(uuid,uuid) to service_role;
create function public.platform_access(p_auth uuid,p_session uuid) returns jsonb language plpgsql stable security definer set search_path=pg_catalog as $$
declare r text; required boolean; satisfied boolean; permissions text[];
begin
 if not exists(select 1 from auth.users u join auth.sessions s on s.user_id=u.id where u.id=p_auth and s.id=p_session
 and u.deleted_at is null and u.email_confirmed_at is not null and (u.banned_until is null or u.banned_until<=now())
 and ((to_jsonb(s)->>'not_after') is null or (to_jsonb(s)->>'not_after')::timestamptz>now())
 and not exists(select 1 from app_private.platform_revoked_sessions x where x.session_id=s.id)) then return null; end if;
 select 'owner',mfa_required into r,required from app_private.platform_owners where auth_user_id=p_auth;
 if r is null then select role,mfa_required into r,required from app_private.platform_staff where auth_user_id=p_auth; end if;
 if r is null then return null; end if;
 select (to_jsonb(s)->>'aal')='aal2' and exists(select 1 from auth.mfa_factors f where f.user_id=p_auth and f.status='verified') into satisfied from auth.sessions s where id=p_session;
 permissions:=case r when 'owner' then array['overview.read','organizations.read','organizations.manage','members.manage','projects.read','projects.manage','billing.read','billing.manage','analytics.read','health.read','alerts.manage','team.manage','activity.read']
 when 'support' then array['overview.read','organizations.read','organizations.manage','members.manage','projects.read','projects.manage','health.read','alerts.manage','activity.read']
 else array['organizations.read','billing.read','billing.manage','analytics.read','health.read','alerts.manage'] end;
 return jsonb_build_object('role',r,'permissions',permissions,'mfaRequired',required,'mfaSatisfied',coalesce(satisfied,false));
end $$;
create or replace function public.platform_owner_access(p_auth uuid,p_session uuid) returns boolean language sql stable security definer set search_path=pg_catalog as $$
 select coalesce((a->>'role')='owner' and (not (a->>'mfaRequired')::boolean or (a->>'mfaSatisfied')::boolean),false) from (select public.platform_access(p_auth,p_session) a) s;
$$;
create function app_private.require_platform_permission(p_auth uuid,p_session uuid,p_permission text) returns void language plpgsql security definer set search_path=pg_catalog as $$
declare a jsonb:=public.platform_access(p_auth,p_session);
begin
 if a is null or not (a->'permissions' ? p_permission) then raise exception 'Platform permission required' using errcode='42501'; end if;
 if (a->>'mfaRequired')::boolean and not (a->>'mfaSatisfied')::boolean then raise exception 'MFA_REQUIRED' using errcode='42501'; end if;
end $$;
create function public.platform_record_access(p_auth uuid,p_session uuid,p_permission text,p_path text) returns void language plpgsql security definer set search_path=pg_catalog as $$
begin
 perform app_private.require_platform_permission(p_auth,p_session,p_permission);
 insert into app_private.platform_audit(actor_id,action,reason) values(p_auth,'access.'||p_permission,left(p_path,200));
end $$;
-- Preserve the established workspace authority while revoking old sessions immediately.
alter function app_private.workspace_context(uuid,uuid,boolean) rename to workspace_context_before_platform;
create function app_private.workspace_context(p_auth uuid,p_session uuid,p_allow_deletion boolean default false) returns jsonb language sql stable security definer set search_path=pg_catalog as $$
 select app_private.workspace_context_before_platform(p_auth,p_session,p_allow_deletion)
 where (p_session is null or exists(select 1 from auth.sessions s where s.id=p_session and s.user_id=p_auth and ((to_jsonb(s)->>'not_after') is null or (to_jsonb(s)->>'not_after')::timestamptz>now())))
 and not exists(select 1 from app_private.platform_revoked_sessions where session_id=p_session);
$$;
-- Only the service API / SQL operator may change platform suspension state.
create function public.guard_platform_organization_status() returns trigger language plpgsql set search_path=pg_catalog as $$
begin
 if new.status is distinct from old.status and current_user not in ('postgres','supabase_admin','service_role') then raise exception 'Platform status is managed by the platform team' using errcode='42501'; end if;
 return new;
end $$;
revoke all on function public.guard_platform_organization_status() from public,anon,authenticated;
create trigger platform_organization_status before update of status on public.organizations for each row execute function public.guard_platform_organization_status();
create function public.platform_management_list(p_auth uuid,p_session uuid,p_kind text,p_org uuid default null,p_search text default '',p_page integer default 1,p_status text default '',p_from timestamptz default null,p_to timestamptz default null) returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare result jsonb;
begin
 perform app_private.require_platform_permission(p_auth,p_session,case p_kind when 'team' then 'team.manage' when 'members' then 'members.manage' else 'organizations.read' end);
 if p_page<1 or p_page>100000 or p_status not in ('','all','active','invited','suspended') then raise exception 'Invalid page or status' using errcode='22023'; end if;
 if p_kind='team' then
 with team as (
 select p.auth_user_id,u.email,'owner' role,p.mfa_required from app_private.platform_owners p join auth.users u on u.id=p.auth_user_id
 union all select p.auth_user_id,u.email,p.role,p.mfa_required from app_private.platform_staff p join auth.users u on u.id=p.auth_user_id)
 select jsonb_build_object('total',(select count(*) from team),'page',p_page,'pageSize',20,'items',coalesce((select jsonb_agg(x) from (select * from team order by email,auth_user_id limit 20 offset (p_page-1)*20) x),'[]'::jsonb)) into result;
 elsif p_kind='organization' then select jsonb_build_object('id',id,'name',name,'status',status) into result from public.organizations where id=p_org;
 elsif p_kind='members' then
 select jsonb_build_object('total',(select count(*) from public.memberships m where (p_org is null or m.organization_id=p_org) and (p_status in ('','all') or m.status=p_status) and (p_from is null or m.created_at>=p_from) and (p_to is null or m.created_at<p_to) and strpos(lower(coalesce(m.email,'')),lower(left(p_search,100)))>0), 'page',p_page,'pageSize',20,'items',coalesce((select jsonb_agg(x) from (
 select m.id,m.organization_id,o.name organization_name,m.email,m.role,m.status,m.user_type from public.memberships m join public.organizations o on o.id=m.organization_id where (p_org is null or m.organization_id=p_org) and (p_status in ('','all') or m.status=p_status) and (p_from is null or m.created_at>=p_from) and (p_to is null or m.created_at<p_to) and strpos(lower(coalesce(m.email,'')),lower(left(p_search,100)))>0 order by m.created_at desc,m.id limit 20 offset (p_page-1)*20) x),'[]'::jsonb)) into result;
 else raise exception 'Invalid list' using errcode='22023'; end if;
 return result;
end $$;
create function public.platform_management_mutate(p_auth uuid,p_session uuid,p_action text,p_data jsonb,p_reason text) returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare org uuid; m public.memberships%rowtype; target uuid; desired text; platform_role text; result jsonb:='{"success":true}'::jsonb; invite uuid; token text;
begin
 perform app_private.require_platform_permission(p_auth,p_session,case when p_action like 'team.%' then 'team.manage' when p_action like 'member.%' then 'members.manage' else 'organizations.manage' end);
 if length(btrim(coalesce(p_reason,''))) not between 8 and 500 then raise exception 'Reason must be 8–500 characters' using errcode='22023'; end if;
 platform_role:=public.platform_access(p_auth,p_session)->>'role';
 if p_action='organization.status' then
 org:=(p_data->>'organizationId')::uuid; desired:=p_data->>'status';
 if desired not in ('active','suspended') or desired is null then raise exception 'Invalid status' using errcode='22023'; end if;
 update public.organizations set status=desired,updated_at=now() where id=org;
 if not found then raise exception 'Organization not found' using errcode='22023'; end if;
 elsif p_action in ('member.role','member.status','member.sessions') then
 select * into m from public.memberships where id=(p_data->>'membershipId')::uuid;
 if m.id is null then raise exception 'Member not found' using errcode='22023'; end if;
 org:=m.organization_id; perform pg_advisory_xact_lock(hashtextextended('platform-members:'||org::text,0));
 select * into m from public.memberships where id=m.id for update;
 if m.user_type='admin' then select auth_user_id into target from public.admin_users where id=m.user_id and organization_id=org;
 elsif m.user_type='developer' then select auth_user_id into target from public.developers where id=m.user_id and organization_id=org;
 else select auth_user_id into target from public.clients where id=m.user_id and organization_id=org; end if;
 if target=p_auth then raise exception 'Cannot modify your own membership or sessions' using errcode='42501'; end if;
 if exists(select 1 from app_private.platform_owners where auth_user_id=target) or exists(select 1 from app_private.platform_staff where auth_user_id=target) then raise exception 'Platform staff identities are protected; manage their platform access separately' using errcode='42501'; end if;
 if m.role='owner' and platform_role<>'owner' then raise exception 'Only platform owners may manage workspace owners' using errcode='42501'; end if;
 if m.role='owner' and m.status='active' and p_action<>'member.sessions' and not exists(select 1 from public.memberships where organization_id=org and id<>m.id and role='owner' and status='active') then raise exception 'The last active workspace owner is protected' using errcode='23514'; end if;
 if p_action='member.role' then
 desired:=p_data->>'role';
 if desired is null or desired not in ('owner','admin','manager','hr','finance','team_lead','qa','developer','designer','devops','employee','client') or (m.user_type='client')<>(desired='client') or (desired='owner' and platform_role<>'owner') then raise exception 'Invalid role assignment' using errcode='22023'; end if;
 -- Update the global fallback only if it represents this exact workspace; per-session claims derive fresh membership roles.
 update auth.users set raw_app_meta_data=jsonb_set(raw_app_meta_data,'{role}',to_jsonb(desired)) where id=target and raw_app_meta_data->>'organization_id'=org::text and raw_app_meta_data->>'app_user_id'=m.user_id::text;
 update public.memberships set role=desired,updated_at=now() where id=m.id;
 elsif p_action='member.status' then
 desired:=p_data->>'status'; if desired not in ('active','suspended') or desired is null then raise exception 'Invalid status' using errcode='22023'; end if;
 update public.memberships set status=desired,updated_at=now() where id=m.id;
 else
 if target is null then raise exception 'Member has no linked login' using errcode='22023'; end if;
 insert into app_private.platform_revoked_sessions(session_id,auth_user_id) select id,user_id from auth.sessions where user_id=target on conflict do nothing;
 result:=result||jsonb_build_object('message','Existing application sessions revoked across all workspaces. The user can sign in again.');
 end if;
 elsif p_action='member.invite' then
 org:=(p_data->>'organizationId')::uuid; desired:=p_data->>'role';
 if desired is null or desired not in ('owner','admin','manager','hr','finance','team_lead','qa','developer','designer','devops','employee','client') or desired='owner' or coalesce(p_data->>'email','') !~ '^[^ @]+@[^ @]+\.[^ @]+$' then raise exception 'Invalid invitation' using errcode='22023'; end if;
 if not exists(select 1 from public.organizations where id=org and status='active') then raise exception 'Organization must be active' using errcode='22023'; end if;
 token:=gen_random_uuid()::text;
 insert into public.invitations(organization_id,email,role,token,status,expires_at) values(org,lower(btrim(p_data->>'email')),desired,token,'pending',now()+interval '7 days') returning id into invite;
 result:=jsonb_build_object('success',true,'invitationId',invite,'token',token);
 elsif p_action in ('team.upsert','team.remove','team.mfa') then
 perform pg_advisory_xact_lock(hashtextextended('platform-team',0));
 if p_action='team.mfa' then target:=p_auth;
 elsif p_action='team.upsert' then select id into target from auth.users where lower(email)=lower(btrim(p_data->>'email')) and email_confirmed_at is not null and deleted_at is null and (banned_until is null or banned_until<=now());
 else target:=(p_data->>'authUserId')::uuid; end if;
 if target is null then raise exception 'A verified existing login is required' using errcode='22023'; end if;
 if p_action<>'team.mfa' and target=p_auth then raise exception 'Cannot change your own platform access' using errcode='42501'; end if;
 if p_action='team.mfa' then
 if (p_data->>'mfaRequired')::boolean and not (public.platform_access(p_auth,p_session)->>'mfaSatisfied')::boolean then raise exception 'Verify MFA before requiring it' using errcode='22023'; end if;
 update app_private.platform_owners set mfa_required=(p_data->>'mfaRequired')::boolean where auth_user_id=target;
 else
 if exists(select 1 from app_private.platform_owners where auth_user_id=target) and (select count(*) from app_private.platform_owners)<=1 and (p_action='team.remove' or p_data->>'role' is distinct from 'owner') then raise exception 'Last platform owner is protected' using errcode='23514'; end if;
 desired:=p_data->>'role';
 if p_action='team.upsert' and (desired not in ('owner','support','billing') or desired is null) then raise exception 'Invalid platform role' using errcode='22023'; end if;
 delete from app_private.platform_staff where auth_user_id=target; delete from app_private.platform_owners where auth_user_id=target;
 if p_action='team.upsert' then
 if desired='owner' then insert into app_private.platform_owners(auth_user_id,mfa_required) values(target,coalesce((p_data->>'mfaRequired')::boolean,true));
 else insert into app_private.platform_staff(auth_user_id,role,mfa_required) values(target,desired,coalesce((p_data->>'mfaRequired')::boolean,true)); end if;
 end if;
 end if;
 else raise exception 'Invalid action' using errcode='22023'; end if;
 insert into app_private.platform_audit(actor_id,organization_id,action,reason) values(p_auth,org,p_action,p_reason||coalesce(' [target: '||coalesce(target::text,m.id::text,p_data->>'email')||']',''));
 return result;
end $$;
-- A delegated platform operator must also survive organization cleanup.
do $$ declare definition text; begin
 select pg_get_functiondef('public.check_deletion_auth_identity(uuid,uuid,uuid)'::regprocedure) into definition;
 definition:=replace(definition,'exists(select 1 from app_private.platform_owners where auth_user_id::text=i.resource_id)', '(exists(select 1 from app_private.platform_owners where auth_user_id::text=i.resource_id) or exists(select 1 from app_private.platform_staff where auth_user_id::text=i.resource_id))');
 execute definition;
end $$;
create function public.platform_organizations_filtered(p_auth uuid,p_session uuid,p_search text default '',p_page integer default 1,p_status text default '',p_from timestamptz default null,p_to timestamptz default null,p_org uuid default null) returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare result jsonb;
begin
 perform app_private.require_platform_permission(p_auth,p_session,'organizations.read');
 if p_page<1 or p_page>100000 or p_status not in ('','all','active','suspended') then raise exception 'Invalid filters' using errcode='22023'; end if;
 with matching as (select o.* from public.organizations o where (p_search='' or strpos(lower(o.name),lower(left(p_search,100)))>0 or o.id::text=p_search) and (p_status in ('','all') or o.status=p_status) and (p_org is null or o.id=p_org) and (p_from is null or o.created_at>=p_from) and (p_to is null or o.created_at<p_to))
 select jsonb_build_object('total',(select count(*) from matching),'page',p_page,'pageSize',20,'items',coalesce((select jsonb_agg(x) from (
 select o.id,o.name,o.status,o.created_at,o.industry,o.country,o.timezone,(select count(*) from public.projects p where p.organization_id=o.id) projects,(select count(*) from public.memberships m where m.organization_id=o.id and m.status='active') members,(select count(*) from public.developer_tasks t where t.organization_id=o.id) tasks,(select j.status from app_private.organization_deletions j where j.organization_id=o.id) deletion_status from matching o order by o.created_at desc,o.id limit 20 offset (p_page-1)*20) x),'[]'::jsonb)) into result;
 return result;
end $$;
revoke all on function public.platform_organizations_filtered(uuid,uuid,text,integer,text,timestamptz,timestamptz,uuid) from public,anon,authenticated;
grant execute on function public.platform_organizations_filtered(uuid,uuid,text,integer,text,timestamptz,timestamptz,uuid) to service_role;
-- Existing reporting gets explicit capability guards; destructive RPCs keep owner checks.
do $$ declare r record; definition text; permission text; begin
 for r in select p.oid,p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('platform_overview','platform_organizations','platform_organization_detail','platform_activity') loop
 permission:=case r.proname when 'platform_overview' then 'overview.read' when 'platform_activity' then 'activity.read' else 'organizations.read' end;
 definition:=pg_get_functiondef(r.oid);
 definition:=replace(definition,'perform app_private.require_platform_owner(p_auth,p_session);',format('perform app_private.require_platform_permission(p_auth,p_session,%L);',permission));
 execute definition;
 end loop;
end $$;
do $$ declare r record; begin
 for r in select p.oid::regprocedure sig,n.nspname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='public' and p.proname in ('platform_access','platform_record_access','platform_management_list','platform_management_mutate')) or (n.nspname='app_private' and p.proname in ('require_platform_permission','workspace_context')) loop
 execute format('revoke all on function %s from public,anon,authenticated,service_role',r.sig);
 if r.nspname='public' then execute format('grant execute on function %s to service_role',r.sig); end if;
 end loop;
end $$;

-- Source: 20260920115133_platform_project_management.sql
-- Narrow override for audited platform maintenance, including task cascades.
-- Only a service-role transaction carrying a freshly checked platform identity
-- can use it. Tenant tokens cannot elevate through custom settings.
create or replace function app_private.guard_delivery_write_lock()
returns trigger language plpgsql security definer
set search_path=pg_catalog,public,app_private as $$
declare organizations_to_check uuid[]; target_org uuid;
begin
 if tg_op='INSERT' then organizations_to_check:=array[new.organization_id];
 elsif tg_op='DELETE' then organizations_to_check:=array[old.organization_id];
 else organizations_to_check:=array[old.organization_id,new.organization_id]; end if;
 for target_org in select distinct org from unnest(organizations_to_check) org where org is not null order by org loop
  if tg_op='DELETE' and not exists(select 1 from public.organizations where id=target_org) then continue; end if;
  if current_setting('role',true)='service_role'
    and current_setting('app.platform_project_org',true)=target_org::text then
   perform app_private.require_platform_permission(nullif(current_setting('app.platform_actor',true),'')::uuid,nullif(current_setting('app.platform_session',true),'')::uuid,'projects.manage');
   continue;
  end if;
  perform app_private.lock_quota(target_org);
  if not app_private.org_unlocked(target_org) then raise exception 'BILLING_LOCKED: subscription requires attention' using errcode='P0001'; end if;
 end loop;
 if tg_op='DELETE' then return old; end if; return new;
end $$;
revoke all on function app_private.guard_delivery_write_lock() from public,anon,authenticated;

create function public.platform_project_action(p_auth uuid,p_session uuid,p_project uuid,p_action text,p_reason text,p_name text default null)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare project public.projects%rowtype; result jsonb;
begin
 perform app_private.require_platform_permission(p_auth,p_session,'projects.manage');
 if p_action not in ('archive','restore','delete') or p_action is null or p_reason is null or length(trim(p_reason)) not between 8 and 500 then
  raise exception 'Choose an action and provide a reason of 8–500 characters' using errcode='22023'; end if;
 select * into project from public.projects where id=p_project for update;
 if not found then raise exception 'Project not found' using errcode='P0002'; end if;
 if exists(select 1 from app_private.organization_deletions where organization_id=project.organization_id and status<>'completed') then
  raise exception 'Organization cleanup is in progress' using errcode='55000'; end if;
 if p_action='delete' and p_name is distinct from project.name then raise exception 'Type the exact project name' using errcode='22023'; end if;
 perform set_config('app.platform_actor',p_auth::text,true);
 perform set_config('app.platform_session',p_session::text,true);
 perform set_config('app.platform_project_org',project.organization_id::text,true);
 if p_action='delete' then
  delete from public.projects where id=p_project;
 else
  update public.projects set archived=(p_action='archive') where id=p_project;
 end if;
 insert into app_private.platform_audit(actor_id,organization_id,action,reason)
 values(p_auth,project.organization_id,'project.'||p_action,trim(p_reason)||' [project '||p_project::text||']');
 perform set_config('app.platform_project_org','',true);
 return jsonb_build_object('id',p_project,'action',p_action,'name',project.name);
end $$;
revoke all on function public.platform_project_action(uuid,uuid,uuid,text,text,text) from public,anon,authenticated;
grant execute on function public.platform_project_action(uuid,uuid,uuid,text,text,text) to service_role;

-- Source: 20260920115502_platform_billing_suite.sql
create table app_private.platform_billing_requests(
 id uuid primary key,actor_id uuid not null,organization_id uuid not null,payload jsonb not null,
 status text not null check(status in ('pending','completed','failed')),result jsonb,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
-- Match effective-account recovery ordering without sorting its full history.
create index platform_billing_requests_account_history on app_private.platform_billing_requests
 (organization_id,(case when status='pending' then 0 else 1 end),created_at desc);
-- The account mutex checks only unresolved receipts; completed history stays out.
create index platform_billing_requests_pending_account on app_private.platform_billing_requests
 (organization_id,id) where status='pending';
create table app_private.platform_alert_acknowledgements(actor_id uuid not null,alert_id text not null,acknowledged_at timestamptz not null default now(),primary key(actor_id,alert_id));
alter table app_private.platform_billing_requests enable row level security;
alter table app_private.platform_alert_acknowledgements enable row level security;
revoke all on app_private.platform_billing_requests,app_private.platform_alert_acknowledgements from public,anon,authenticated,service_role;
create function public.platform_billing_context(p_auth uuid,p_session uuid,p_org uuid,p_invoice uuid default null) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare account uuid:=p_org;
begin
 perform app_private.require_platform_permission(p_auth,p_session,'billing.read');
 if not exists(select 1 from public.organizations where id=p_org) then raise exception 'Organization not found';end if;
 if to_regprocedure('app_private.billing_account(uuid)') is not null then execute 'select app_private.billing_account($1)' into account using p_org;end if;
 return jsonb_build_object('billingOrganizationId',account,'subscription',(select to_jsonb(s) from public.organization_subscriptions s where organization_id=account),
 'requests',coalesce((select jsonb_agg(x) from(select id,status,payload,created_at,updated_at,result,actor_id=p_auth as can_retry,(actor_id=p_auth or exists(select 1 from app_private.platform_owners where auth_user_id=p_auth)) as can_reconcile from app_private.platform_billing_requests where organization_id=account order by case when status='pending' then 0 else 1 end,created_at desc limit 20)x),'[]'),
 'plans',coalesce((select jsonb_agg(to_jsonb(p) order by sort_order) from public.billing_plans p where is_active),'[]'),
 'invoice',(select to_jsonb(i) from public.billing_invoices i where id=p_invoice and organization_id=account));
end $$;
create function public.platform_billing_begin(p_auth uuid,p_session uuid,p_request uuid,p_org uuid,p_payload jsonb) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare r app_private.platform_billing_requests%rowtype;account uuid:=p_org;
begin
 perform app_private.require_platform_permission(p_auth,p_session,'billing.manage');
 if p_request is null or p_payload is null or p_payload->>'action' is null or p_payload->>'reason' is null or p_payload->>'action' not in ('change_plan','extend_trial','cancel_subscription','refund') or length(trim(p_payload->>'reason')) not between 8 and 500 then raise exception 'Invalid action';end if;
 if not exists(select 1 from public.organizations where id=p_org) then raise exception 'Organization not found';end if;
 if to_regprocedure('app_private.billing_account(uuid)') is not null then execute 'select app_private.billing_account($1)' into account using p_org;end if;
 perform pg_advisory_xact_lock(hashtextextended(account::text,0));
 select * into r from app_private.platform_billing_requests where id=p_request for update;
 if found then
  if r.actor_id<>p_auth or r.organization_id<>account or r.payload<>p_payload then raise exception 'Request conflict';end if;
  if r.status='completed' then return jsonb_build_object('status',r.status,'result',r.result);end if;
  if r.created_at<now()-interval '23 hours' then raise exception 'Request expired; inspect provider before a new request';end if;
  if r.status='pending' and r.updated_at>now()-interval '2 minutes' then raise exception 'Request in progress';end if;
 else
  insert into app_private.platform_billing_requests(id,actor_id,organization_id,payload,status) values(p_request,p_auth,account,p_payload,'failed');
 end if;
 if exists(select 1 from app_private.platform_billing_requests where organization_id=account and id<>p_request and status='pending') then raise exception 'Another billing operation needs reconciliation';end if;
 update app_private.platform_billing_requests set status='pending',updated_at=now() where id=p_request;
 insert into app_private.platform_audit(actor_id,organization_id,action,reason) values(p_auth,account,'billing.'||(p_payload->>'action')||'.requested',p_payload->>'reason');
 return jsonb_build_object('status','pending');
end $$;
create function public.platform_billing_finish(p_auth uuid,p_session uuid,p_request uuid,p_result jsonb,p_success boolean) returns boolean
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare r app_private.platform_billing_requests%rowtype;trial timestamptz;
begin
 perform app_private.require_platform_permission(p_auth,p_session,'billing.manage');
 select * into r from app_private.platform_billing_requests where id=p_request and (actor_id=p_auth or exists(select 1 from app_private.platform_owners where auth_user_id=p_auth)) for update;
 if not found then raise exception 'Request missing';end if;
 if r.status='completed' then return true;end if;
 if p_success and p_result->>'local'='true' then
  if r.payload->>'action'<>'extend_trial' then raise exception 'Invalid local operation';end if;
  trial:=(r.payload->>'trialEnd')::timestamptz;
  update public.organization_subscriptions set trial_end=trial,updated_at=now()
  where organization_id=r.organization_id and stripe_subscription_id is null and status='trialing' and trial>coalesce(trial_end,now()) and trial>now() and trial<=now()+interval '366 days';
  if not found then raise exception 'Only existing trials can be extended';end if;
 end if;
 update app_private.platform_billing_requests set status=case when p_success then 'completed' when p_result->>'retryable'='true' then 'pending' else 'failed' end,result=p_result,updated_at=now() where id=p_request;
 insert into app_private.platform_audit(actor_id,organization_id,action,reason) values(p_auth,r.organization_id,'billing.'||(r.payload->>'action')||case when p_success then '.completed' else '.failed' end,r.payload->>'reason');
 return true;
end $$;

create function public.platform_revenue(p_auth uuid,p_session uuid,p_from date,p_to date) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare revenue_result jsonb;starting bigint;lost bigint;
begin
 perform app_private.require_platform_permission(p_auth,p_session,'analytics.read');
 if p_from>p_to then raise exception 'Invalid dates';end if;
 select count(*) into starting from public.organization_subscriptions where created_at<p_from and (ended_at is null or ended_at>=p_from) and stripe_subscription_id is not null;
 select count(*) into lost from public.organization_subscriptions where ended_at>=p_from and ended_at<p_to+1 and created_at<p_from and stripe_subscription_id is not null;
 with recurring as (
 select coalesce(p.currency,'unknown') currency,case when count(*) filter(where p.amount_cents is null or p.billing_interval is null or p.billing_interval not in ('month','year'))>0 then null else sum(case p.billing_interval when 'month' then p.amount_cents when 'year' then p.amount_cents/12.0 else null end) end mrr
 from (select distinct on(coalesce(stripe_subscription_id,id::text)) * from public.organization_subscriptions order by coalesce(stripe_subscription_id,id::text),updated_at desc) s
 left join public.billing_plans p on p.code=s.plan_code where s.status='active' group by p.currency
 ), paid as (
 select currency,sum(coalesce(amount_paid_cents,0)) paid from public.billing_invoices where status='paid' and coalesce(issued_at,created_at)>=p_from and coalesce(issued_at,created_at)<p_to+1 group by currency
 ), outstanding as (
 select currency,sum(greatest(coalesce(amount_due_cents,0)-coalesce(amount_paid_cents,0),0)) due from public.billing_invoices where status='open' group by currency
 ), refunds_raw as (
 select result->>'id' id,result->>'currency' currency,(result->>'amount')::numeric amount,to_timestamp((result->>'created')::numeric) refunded_at,updated_at
 from app_private.platform_billing_requests where status='completed' and payload->>'action'='refund' and result->>'status'='succeeded'
 union all
 select payload#>>'{data,object,id}',payload#>>'{data,object,currency}',(payload#>>'{data,object,amount}')::numeric,to_timestamp((payload#>>'{data,object,created}')::numeric),created_at
 from public.billing_events where event_type in ('refund.created','refund.updated') and payload#>>'{data,object,status}'='succeeded'
 ), refunds as (select currency,sum(amount) refunded from (select distinct on(id) * from refunds_raw order by id,updated_at desc) x where refunded_at>=p_from and refunded_at<p_to+1 group by currency),
 currencies as (select currency from recurring union select currency from paid union select currency from outstanding union select currency from refunds)
 select coalesce(jsonb_agg(jsonb_build_object('currency',c.currency,'mrr_cents',round(case when r.currency is null then 0 else r.mrr end,2),'arr_cents',round((case when r.currency is null then 0 else r.mrr end)*12,2),'paid_cents',coalesce(p.paid,0),'refunded_cents',coalesce(f.refunded,0),'net_collected_cents',coalesce(p.paid,0)-coalesce(f.refunded,0),'outstanding_cents',coalesce(o.due,0)) order by c.currency),'[]') into revenue_result
 from currencies c left join recurring r using(currency) left join paid p using(currency) left join outstanding o using(currency) left join refunds f using(currency);
 return jsonb_build_object('currencies',revenue_result,'from',p_from,'to',p_to,'churn',jsonb_build_object('canceled',lost,'starting_subscriptions',starting,'rate',case when starting>0 then round(lost::numeric/starting*100,2) else null end),
 'notes',jsonb_build_array('MRR/ARR are current catalog-based estimates for active subscriptions; exclude trials, discounts, taxes, quantity and usage. They are not historical revenue. Missing catalog values are unavailable, not zero.','Collections use mirrored invoice dates. Outstanding is current open invoices. Currencies are never combined.','Refunds include successful console refunds and refund.created/refund.updated webhook records; enable these events in Stripe. Older external refunds may be missing.','Churn uses retained subscription rows and ended_at; deleted organizations and replaced subscriptions can leave incomplete history.'));
end $$;

create function public.platform_health(p_auth uuid,p_session uuid) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,app_private as $$
declare result jsonb;objects bigint;bytes numeric;missing bigint;
begin
 perform app_private.require_platform_permission(p_auth,p_session,'health.read');
 select count(*),sum(case when metadata->>'size' ~ '^\d+$' then (metadata->>'size')::numeric else null end),count(*) filter(where metadata->>'size' is null or metadata->>'size' !~ '^\d+$') into objects,bytes,missing from storage.objects;
 with alerts as (
 select 'payment:'||s.id||':'||coalesce(s.last_payment_at,s.updated_at)::text id,'payment_failed' kind,s.organization_id,'Subscription payment requires attention' message,s.updated_at created_at from public.organization_subscriptions s where status in ('past_due','unpaid') or last_payment_status='failed'
 union all select 'trial:'||s.id||':'||s.trial_end::text,'trial_expiry',s.organization_id,'Trial expires within seven days',s.trial_end from public.organization_subscriptions s where status='trialing' and trial_end between now() and now()+interval '7 days'
 union all select 'cleanup:'||j.id||':'||j.attempts::text,'cleanup_failed',j.organization_id,'Organization cleanup needs attention',j.created_at from app_private.organization_deletions j where j.last_error is not null and j.status<>'completed'
 ) select jsonb_build_object('summary',jsonb_build_object('failed_webhooks',(select count(*) from public.billing_events where processing_error is not null),'pending_cleanup',(select count(*) from app_private.organization_deletions where status<>'completed'),
 'stale_devices',(select count(*) from public.tracker_devices d left join public.tracker_device_presence p on p.device_id=d.id where d.revoked_at is null and d.expires_at>now() and coalesce(p.received_at,d.created_at)<now()-interval '24 hours'),
 'storage_bytes',case when missing=0 then coalesce(bytes,0) else null end,'storage_objects',objects),
 'webhooks',coalesce((select jsonb_agg(x) from(select stripe_event_id,event_type,organization_id,processing_error,created_at from public.billing_events where processing_error is not null order by created_at desc limit 100)x),'[]'),
 'devices',coalesce((select jsonb_agg(x) from(select d.id,d.organization_id,d.name,d.platform,p.received_at last_seen_at from public.tracker_devices d left join public.tracker_device_presence p on p.device_id=d.id where d.revoked_at is null and d.expires_at>now() and coalesce(p.received_at,d.created_at)<now()-interval '24 hours' order by p.received_at nulls first limit 100)x),'[]'),
 'jobs',coalesce((select jsonb_agg(x) from(select id,organization_id,organization_name,status,stage,attempts,last_error from app_private.organization_deletions where status<>'completed' order by created_at desc limit 100)x),'[]'),
 'alerts',coalesce((select jsonb_agg(x) from(select a.*,k.acknowledged_at from alerts a left join app_private.platform_alert_acknowledgements k on k.alert_id=a.id and k.actor_id=p_auth order by a.created_at desc limit 100)x),'[]'),
 'notes',jsonb_build_array('Lists show up to 100 latest records. Counts cover all records.','Stale devices have no heartbeat for 24 hours; offline machines may be intentional. This is not proof of a sync failure.','Storage bytes are object metadata totals; unknown sizes return unavailable. Alerts are evaluated when this page refreshes.')) into result;
 return result;
end $$;
create function public.platform_acknowledge_alert(p_auth uuid,p_session uuid,p_id text,p_ack boolean) returns boolean
language plpgsql security definer set search_path=pg_catalog,app_private as $$
begin
 perform app_private.require_platform_permission(p_auth,p_session,'alerts.manage');
 if length(p_id)>200 or p_id !~ '^(payment|trial|cleanup):' then raise exception 'Invalid alert';end if;
 if p_ack then insert into app_private.platform_alert_acknowledgements(actor_id,alert_id)values(p_auth,p_id)on conflict(actor_id,alert_id)do update set acknowledged_at=now();
 else delete from app_private.platform_alert_acknowledgements where actor_id=p_auth and alert_id=p_id;end if;
 return true;
end $$;
do $$declare f record;begin for f in select oid::regprocedure signature from pg_proc where pronamespace='public'::regnamespace and proname in('platform_billing_context','platform_billing_begin','platform_billing_finish','platform_revenue','platform_health','platform_acknowledge_alert')loop execute format('revoke all on function %s from public,anon,authenticated',f.signature);execute format('grant execute on function %s to service_role',f.signature);end loop;end $$;

commit;
select 'Platform admin suite installed successfully' as result;
