\set ON_ERROR_STOP on
DO $$begin
 if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated; end if;
 if not exists(select 1 from pg_roles where rolname='anon') then create role anon; end if;
 if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role bypassrls; end if;
end $$;
create schema auth; create schema storage; create schema app_private;
create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$;
create function auth_org() returns uuid language sql stable as $$select (auth.jwt()->'app_metadata'->>'organization_id')::uuid$$;
create function auth_app_user_id() returns uuid language sql stable as $$select (auth.jwt()->'app_metadata'->>'app_user_id')::uuid$$;
create table organizations(id uuid primary key,status text default 'active');
create table admin_users(id uuid primary key,organization_id uuid,auth_user_id uuid);
create table developers(id uuid primary key,organization_id uuid,auth_user_id uuid);
create table memberships(id uuid primary key default gen_random_uuid(),organization_id uuid,user_id uuid,user_type text,role text,status text);
create table user_permissions(membership_id uuid,permission_key text,allowed boolean);
create table screenshots(id int primary key,organization_id uuid,storage_path text,timestamp timestamptz,developer_id text default 'dev');
create table keyboard_stats(id int primary key,organization_id uuid,timestamp timestamptz);
create table productivity_sessions(id int primary key,organization_id uuid,start_time timestamptz,end_time timestamptz);
create table evidence(id int primary key,keyboard_id int references keyboard_stats on delete cascade);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,created_at timestamptz default now(),updated_at timestamptz default now());
alter table storage.objects enable row level security;
create policy fixture_storage on storage.objects for all to authenticated using(true) with check(true);
grant usage on schema auth,storage to authenticated;
grant select,insert,update,delete on screenshots,storage.objects to authenticated;
create function app_private.plan_limit(uuid,text) returns bigint language sql stable as $$select coalesce(nullif(current_setting('test.plan_days',true),''),'7')::bigint$$;
create function app_private.organization_deleting(uuid) returns boolean language sql stable as $$select coalesce(current_setting('test.deleting',true),'no')='yes'$$;
\ir ../../supabase/migrations/20260911180503_production_tracking_retention_jobs.sql
create function retention_denied(command text) returns void language plpgsql as $$begin
 begin execute command; exception when insufficient_privilege or object_not_in_prerequisite_state then return; end;
 raise exception 'Expected retention denial: %',command;
end$$;
do $$declare org uuid:='92000000-0000-0000-0000-000000000001'; other_org uuid:='92000000-0000-0000-0000-000000000002'; owner uuid:=gen_random_uuid(); uid uuid:=gen_random_uuid(); member uuid; job jsonb; result jsonb; changed integer; begin
 insert into organizations values(org,'active'),(other_org,'active');
 insert into admin_users values(owner,org,uid);
 insert into memberships(organization_id,user_id,user_type,role,status) values(org,owner,'admin','owner','active') returning id into member;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',uid,'app_metadata',jsonb_build_object('organization_id',org,'app_user_id',owner,'user_type','admin'))::text,true);
 insert into keyboard_stats values(1,org,now()-interval '80 days'),(2,org,now()),(3,other_org,now()-interval '80 days'),(4,org,now()-interval '80 days');
 insert into evidence values(1,4);
 insert into productivity_sessions values(1,org,now()-interval '80 days',null),(2,org,now()-interval '80 days',now()-interval '70 days');
 insert into screenshots(id,organization_id,storage_path,timestamp) values(1,org,org||'/dev/old.jpg',now()-interval '80 days'),(2,org,org||'/dev/new.jpg',now()-interval '80 days'),(3,org,'foreign-employee-photo.jpg',now()-interval '80 days');
 insert into storage.objects(bucket_id,name,created_at,updated_at) values('documents','foreign-employee-photo.jpg',now()-interval '80 days',now()-interval '80 days');
 insert into storage.objects(bucket_id,name,created_at,updated_at) values('monitoring',org||'/dev/old.jpg',now()-interval '80 days',now()-interval '80 days'),('monitoring',org||'/dev/new.jpg',now(),now());
 set local role service_role;
 result:=sweep_tracking_retention(org); if (result->>'deleted')::int<>0 then raise exception 'Unconfigured organization was purged'; end if;
 reset role;
 set local role authenticated;
 perform retention_denied(format('select sweep_tracking_retention(%L)',org));
 perform retention_denied('select * from app_private.tracking_retention_files');
 perform retention_denied(format('select set_tracking_retention(%L,''custom'',30,true)',other_org));
 perform set_tracking_retention(org,'custom',30,true);
 reset role;
 insert into user_permissions values(member,'organization.manage',false);
 set local role authenticated;
 perform retention_denied(format('select set_tracking_retention(%L,''disabled'',null,false)',org));
 reset role;delete from user_permissions;
 set local role service_role;
 result:=sweep_tracking_retention(org);
 if (result->>'deleted')::int<>2 or (result->>'queued')::int<>1 then raise exception 'Wrong sweep outcome: %',result; end if;
 reset role;
 if not exists(select 1 from keyboard_stats where id=4) or not exists(select 1 from keyboard_stats where id=3) or not exists(select 1 from productivity_sessions where id=1) then raise exception 'Referenced, foreign or open data deleted'; end if;
 set local role authenticated;
 perform retention_denied('update screenshots set timestamp=now() where id=1');
 update storage.objects set updated_at=now() where name=org||'/dev/old.jpg'; get diagnostics changed=row_count;
 if changed<>0 then raise exception 'Claimed object remained writable'; end if;
 perform set_tracking_retention(org,'disabled',null,false);
 reset role;
 set local role service_role;
 job:=claim_retention_file(org); if job->>'cancelled'<>'true' then raise exception 'Disabled policy still removed bytes'; end if;
 reset role;
 if not exists(select 1 from screenshots where id=1) then raise exception 'Policy cancellation deleted record'; end if;
 set local role authenticated;perform set_tracking_retention(org,'custom',30,true);reset role;
 set local role service_role;
 perform sweep_tracking_retention(org);job:=claim_retention_file(org);
 if job->>'remove'<>'true' then raise exception 'Expected file job'; end if;
 if finish_retention_file((job->>'id')::uuid,gen_random_uuid()) then raise exception 'Wrong lease finalized'; end if;
 if finish_retention_file((job->>'id')::uuid,(job->>'lease')::uuid,'provider failure') then raise exception 'Unconfirmed deletion finalized'; end if;
 reset role;
 set local role authenticated;result:=set_tracking_retention(org,'disabled',null,false);reset role;
 if (result->>'inFlight')::int<>1 then raise exception 'In-flight continuation not disclosed'; end if;
 if not exists(select 1 from screenshots where id=1) then raise exception 'Provider failure lost metadata'; end if;
 update app_private.tracking_retention_files set lease_until=now()-interval '1 second' where id=(job->>'id')::uuid;
 set local role service_role;job:=claim_retention_file(org);reset role;
 -- Fixture simulates confirmed Storage API removal. Production worker calls remove().
 delete from storage.objects where bucket_id=job->>'bucket' and name=job->>'path';
 set local role service_role;
 if not finish_retention_file((job->>'id')::uuid,(job->>'lease')::uuid) then raise exception 'Confirmed removal not finalized'; end if;
 reset role;
 if not exists(select 1 from storage.objects where name='foreign-employee-photo.jpg') or not exists(select 1 from screenshots where id=3) then raise exception 'Mutable legacy path authorized unrelated deletion'; end if;
 if exists(select 1 from screenshots where id=1) or not exists(select 1 from screenshots where id=2) then raise exception 'Screenshot finalization wrong'; end if;
 set local role authenticated;perform set_tracking_retention(org,'plan',null,true);reset role;
 perform set_config('test.plan_days','-1',true);
 if app_private.retention_cutoff(org) is not null then raise exception 'Unlimited plan purged'; end if;
 perform set_config('test.deleting','yes',true);
 set local role service_role;
 result:=sweep_tracking_retention(org);if (result->>'deleted')::int<>0 then raise exception 'Deleting org processed'; end if;
 reset role;
end$$;
