#!/usr/bin/env python3
"""Build the one-transaction Supabase SQL Editor upgrade from reviewed migrations."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
names = [
    '20260920115119_platform_management_access.sql',
    '20260920115133_platform_project_management.sql',
    '20260920115502_platform_billing_suite.sql',
]
parts = ["""-- Verisade platform administration suite upgrade.
-- Run ONCE in Supabase SQL Editor before deploying this application's new build.
-- Requires the existing platform-owner console migration and owner provisioning.
-- This adds management capabilities; it does not run deletions, refunds or invitations.
-- Generated by scripts/build-platform-admin-sql.py; edit the source migrations.
begin;
select pg_advisory_xact_lock(hashtextextended('verisade-platform-admin-suite-upgrade',0));
do $$ begin
 if to_regclass('app_private.platform_owners') is null then
  raise exception 'Install the existing platform-owner console setup first';
 end if;
 if to_regclass('app_private.platform_staff') is not null then
  raise exception 'Platform admin suite is already installed; do not rerun this upgrade';
 end if;
end $$;
"""]
for name in names:
    sql = (root / 'supabase' / 'migrations' / name).read_text()
    assert re.match(r'^begin;\s*', sql, re.I), name
    assert re.search(r'\s*commit;\s*$', sql, re.I), name
    sql = re.sub(r'^begin;\s*', '', sql, count=1, flags=re.I)
    sql = re.sub(r'\s*commit;\s*$', '', sql, count=1, flags=re.I)
    parts.append(f'\n-- Source: {name}\n{sql}\n')
parts.append("""
commit;
select 'Platform admin suite installed successfully' as result;
""")
output = root / 'database' / 'platform-admin-suite-setup.sql'
output.write_text(''.join(parts))
print(output)
