#!/usr/bin/env python3
"""Build the reviewed SQL Editor bundle; --check detects stale copied SQL."""
from pathlib import Path
import hashlib
import sys

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS = (
    '20260911163008_production_atomic_sprint_notifications.sql',
    '20260911163106_production_notification_entity_privacy.sql',
    '20260911163247_production_durable_actor_automation_jobs.sql',
    '20260911163440_production_atomic_proposal_decisions.sql',
    '20260911163620_production_atomic_employee_save.sql',
    '20260911164338_production_server_notification_event_guard.sql',
    '20260911170307_production_atomic_work_transition_notices.sql',
    '20260911171109_production_milestone_write_authority.sql',
)
HEADER = '''-- Generated by scripts/build-confirmed-gap-sql.py from reviewed migrations.
-- Run ONCE in Supabase SQL Editor as postgres AFTER the PR #100 prerequisites.
-- Use this bundle OR its individual migrations, never both.
-- This does not repair CLI migration history or the unresolved Storage mapping.
-- Any error rolls back this entire bundle. Do not run isolated fragments.
begin;
set local lock_timeout = '10s';
do $preflight$
begin
 if to_regclass('public.notification_recipients') is null
    or to_regclass('public.notification_inbox') is null
    or to_regprocedure('private.assignment_notice_recipient(uuid,uuid,text)') is null
    or to_regprocedure('public.auth_people_permission(text)') is null
    or to_regprocedure('app_private.org_unlocked(uuid)') is null
    or to_regprocedure('public.auth_agile_container_write(uuid,uuid)') is null
    or not exists(select 1 from information_schema.columns where table_schema='public' and table_name='projects' and column_name='manager_type') then
  raise exception 'PREREQUISITES_REQUIRED: run the read-only production-recovery-verification.sql and resolve missing earlier migrations first';
 end if;
 if to_regclass('public.automation_jobs') is not null
    or to_regclass('public.proposal_decision_emails') is not null
    or to_regprocedure('public.notify_sprint_status_transaction()') is not null then
  raise exception 'BATCH_ALREADY_STARTED: do not replay this bundle over completed individual migrations; verify which migrations have already succeeded';
 end if;
end $preflight$;
'''
parts = [HEADER]
for name in MIGRATIONS:
    source = (ROOT / 'supabase/migrations' / name).read_text()
    lines = source.strip().splitlines()
    if lines[0].strip().lower() != 'begin;' or lines[-1].strip().lower() != 'commit;':
        raise SystemExit(f'{name}: expected one outer transaction')
    digest = hashlib.sha256(source.encode()).hexdigest()
    parts.append(f'\n-- SOURCE: {name}\n-- SHA256: {digest}\n' + '\n'.join(lines[1:-1]) + '\n')
parts.append('\ncommit;\n')
output = ''.join(parts)
target = ROOT / 'scripts/sql/confirmed-gap-recovery.sql'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != output:
        raise SystemExit('SQL bundle is stale; run scripts/build-confirmed-gap-sql.py')
    print(f'SQL bundle matches {len(MIGRATIONS)} source migrations.')
else:
    target.write_text(output)
    print(f'Wrote {target.relative_to(ROOT)} ({len(MIGRATIONS)} migrations).')
