#!/usr/bin/env python3
"""Build the reviewed SQL Editor bundle; --check detects stale copied SQL."""
from pathlib import Path
import hashlib
import sys

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS = (
    '20260911180306_production_unattended_actor_automation.sql',
    '20260911180503_production_tracking_retention_jobs.sql',
    '20260911180705_production_typed_leave_authority.sql',
    '20260911180815_production_organization_deletion_lifecycle.sql',
    '20260911182229_production_existing_leave_day_contract.sql',
)
HEADER = '''-- Generated by scripts/build-lifecycle-leave-sql.py from reviewed migrations.
-- Run ONCE as postgres AFTER the PR #101 confirmed-gap migrations succeeded.
-- Use this whole bundle OR its individual migrations, never both.
-- No existing organization is opted into retention or deletion by this bundle.
-- This does not repair CLI migration history or legacy Storage mappings.
-- Any error rolls back the entire bundle; do not run isolated fragments.
begin;
set local lock_timeout = '10s';
do $preflight$
begin
 if to_regclass('public.automation_jobs') is null
    or to_regclass('public.proposal_decision_emails') is null
    or to_regclass('public.leave_requests') is null
    or to_regclass('public.attendance_records') is null
    or to_regclass('storage.objects') is null
    or to_regprocedure('public.apply_actor_automation_action(uuid,uuid)') is null
    or to_regprocedure('public.notify_project_assignment_transaction()') is null
    or to_regprocedure('public.guard_milestone_content()') is null
    or to_regprocedure('app_private.plan_feature(uuid,text)') is null
    or to_regprocedure('public.auth_override(text)') is null then
  raise exception 'PREREQUISITES_REQUIRED: verify PR #101 and earlier schema migrations before this lifecycle/leave batch';
 end if;
 if to_regclass('public.tracking_retention_policies') is not null
    or to_regclass('app_private.organization_deletions') is not null
    or to_regprocedure('public.auth_leave_permission(text)') is not null
    or to_regprocedure('private.assert_automation_executor_safe()') is not null
    or to_regprocedure('public.guard_leave_day_contract()') is not null then
  raise exception 'BATCH_ALREADY_STARTED: do not replay this bundle over completed individual migrations; reconcile completed migrations first';
 end if;
end $preflight$;
'''
parts = [HEADER]
for name in MIGRATIONS:
    source = (ROOT / 'supabase/migrations' / name).read_text()
    lines = source.strip().splitlines()
    if lines[0].strip().lower() != 'begin;' or lines[-1].strip().lower() != 'commit;':
        raise SystemExit(f'{name}: expected one outer transaction')
    digest = hashlib.sha256(source.encode()).hexdigest()
    parts.append(f'\n-- SOURCE: {name}\n-- SHA256: {digest}\n' + '\n'.join(lines[1:-1]) + '\n')
parts.append('\ncommit;\n')
output = ''.join(parts)
target = ROOT / 'scripts/sql/lifecycle-leave-deployment.sql'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != output:
        raise SystemExit('SQL bundle is stale; run scripts/build-lifecycle-leave-sql.py')
    print(f'SQL bundle matches {len(MIGRATIONS)} source migrations.')
else:
    target.write_text(output)
    print(f'Wrote {target.relative_to(ROOT)} ({len(MIGRATIONS)} migrations).')
